### PR TITLE
Enable tests with active directory client id and secret for Azure Dat…

### LINKED ISSUE #2841: Add Azure Data Explorer e2e tests with active directory credentials.
Relates to #2770, [#2882](https://github.com/kedacore/keda/pull/2822).

### PR DESCRIPTION
**Pull request by v-shenoy**
…a Explorer scaler.

Signed-off-by: Vighnesh Shenoy <vshenoy@microsoft.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Relates to #2841

### CODE REVIEW

**Comment by v-shenoy** [comment]
Was the Kusto cluster that the env variable points to, deleted? @zroubalik

**Comment by zroubalik** [comment]
@v-shenoy I am sorry, but I don't have an access to Azure resources. @tomkerkhove might help with that

**Comment by tomkerkhove** [comment]
What cluster would that be @v-shenoy?

**Comment by v-shenoy** [comment]
Could you just run this again, once?

**Comment by JorTurFer** [comment]
It works! 🥳 🥳 🥳 
Could you rebase your branch to solve the conficlts please? 🙏

**Comment by v-shenoy** [comment]
@JorTurFer Rebased. Could you just run it once more, just to ensure I didn't mess something up?

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
