### PR TITLE
Datadog: `isActive()` should react on `num > 0`

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

I confused @arapulido on https://github.com/kedacore/keda/pull/2694 to include a wrong implementation of `IsActive()` function, fixing this here.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates #2657

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]

**Comment by arapulido** [comment]
Mmm, I'm very confused about this. A metric can have a positive value, or a negative, so checking this doesn't give much information.

What's the goal?

I tested the code before this, and I was able to make to 0.

Can we wait until tomorrow morning before merging this, please?

I would like to do more testing and report

**Comment by zroubalik** [comment]
@arapulido this is just aligning the functionality with all the existing scalers, so the experience is consistent. `isActive()` should return true if there **any** activity on the scaler.  We are discussing on making this configurable (ie adding a new property for the activation threshold)

**Comment by arapulido** [comment]
> @arapulido this is just aligning the functionality with all the existing scalers, so the experience is consistent. `isActive()` should return true if there is **any** activity on the scaler. We are discussing on making this configurable (ie adding a new property for the activation threshold) -> #2800

OK, as discussed on Slack, happy to be consistent with the rest of scalers.

**Pull request merged**
