### PR TITLE
chore: refactor `scalers` package and move `ScalersConfig`

### LINKED ISSUE #5379: Refactor `scalers` package
### Proposal

We should slightly refactor `scalers` package, it is hard to create subpackages there (for example `pkg/scalers/aws`, `pkg/scalers/...`) that needs to use ScalerConfig. Because this introduces circular dependency.

We should move ScalerConfig out and refactore the package a little bit.

### Use-Case

_No response_

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zroubalik**
Getting rid of circular dependency, that might happen when we try to create subpackages in `pkg/scalers` and use `ScalerConfig` there.
- Moved `scalers.ScalersConfig` to new package: `pkg/scalers/scalersconfig.ScalersConfig`
- Moved commong GCP related stuff to `pkg/scalers/gcp`
- Moved common Kafka stuff to `pkg/scalers/kafka`
- Fixed some linter validation problems

### Checklist
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #5379

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]

**Comment by zroubalik** [comment]
Failed tests:
```
2024-01-16T14:12:36.6720642Z 	Execution of tests/scalers/aws/aws_cloudwatch_pod_identity_eks/aws_cloudwatch_pod_identity_eks_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6723578Z 	Execution of tests/scalers/aws/aws_dynamodb_pod_identity_eks/aws_dynamodb_pod_identity_eks_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6726082Z 	Execution of tests/internals/events/events_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6728669Z 	Execution of tests/scalers/aws/aws_kinesis_stream_pod_identity_eks/aws_kinesis_stream_pod_identity_eks_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6731595Z 	Execution of tests/scalers/redis/redis_sentinel_streams_lag/redis_sentinel_streams_lag_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6734431Z 	Execution of tests/scalers/aws/aws_sqs_queue_pod_identity_eks/aws_sqs_queue_pod_identity_eks_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6737811Z 	Execution of tests/scalers/redis/redis_sentinel_streams_pending_entries/redis_sentinel_streams_pending_entries_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6746359Z 	Execution of tests/scalers/redis/redis_sentinel_streams_length/redis_sentinel_streams_length_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6749425Z 	Execution of tests/scalers/aws/aws_dynamodb_streams_pod_identity_eks/aws_dynamodb_streams_pod_identity_eks_test.go, has failed after "three" attempts
2024-01-16T14:12:36.6752531Z 	Execution of tests/scalers/redis/redis_sentinel_lists/redis_sentinel_lists_test.go, has failed after "three" attempts
```

**Comment by zroubalik** [comment]
> Failed tests:
> 
> ```
> 2024-01-16T14:12:36.6720642Z 	Execution of tests/scalers/aws/aws_cloudwatch_pod_identity_eks/aws_cloudwatch_pod_identity_eks_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6723578Z 	Execution of tests/scalers/aws/aws_dynamodb_pod_identity_eks/aws_dynamodb_pod_identity_eks_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6726082Z 	Execution of tests/internals/events/events_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6728669Z 	Execution of tests/scalers/aws/aws_kinesis_stream_pod_identity_eks/aws_kinesis_stream_pod_identity_eks_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6731595Z 	Execution of tests/scalers/redis/redis_sentinel_streams_lag/redis_sentinel_streams_lag_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6734431Z 	Execution of tests/scalers/aws/aws_sqs_queue_pod_identity_eks/aws_sqs_queue_pod_identity_eks_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6737811Z 	Execution of tests/scalers/redis/redis_sentinel_streams_pending_entries/redis_sentinel_streams_pending_entries_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6746359Z 	Execution of tests/scalers/redis/redis_sentinel_streams_length/redis_sentinel_streams_length_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6749425Z 	Execution of tests/scalers/aws/aws_dynamodb_streams_pod_identity_eks/aws_dynamodb_streams_pod_identity_eks_test.go, has failed after "three" attempts
> 2024-01-16T14:12:36.6752531Z 	Execution of tests/scalers/redis/redis_sentinel_lists/redis_sentinel_lists_test.go, has failed after "three" attempts
> ```

Seems like it fails on `main` too, not related to this change.

**Pull request merged**
