### PR TITLE
chore: Improve tests

### PR DESCRIPTION
**Pull request by JorTurFer**
Changes done by this PR:

- K8s v1.26 is used for functional tests
- main e2e test are executed in an ARM64 runner as they are faster
- `WaitForNamespaceDeletion` (the helper we use in e2e test to wait until namespace is deleted) timeout has increased from 3 minutes to 10 minutes
- `run-all.sh` has been removed and another `run-all.go` script has been added to improve the test execution maintaining always X test on going instead of batches of X, having to wait until the whole batch finishes for starting the next batch
- `create_cas_volume.yml` has been removed in favor of `patch_operator.yml` which also sets the requested cpu to 1 for operator during e2e tests
- Flaky test in `controllers/keda/scaledobject_controller_test.go` has been fixed
- polling_cooldown_test has been updated because it was overloading the CPU due to a misconfiguration and duplicated test cases have been removed
- cassandra_test has been refactored as it was a flaky test (now it uses helm chart for cassandra and jobs)
- couchdb_test has been refactored as it was a flaky test
- etcd_cluster_test has been refactored as it was a flaky test
- mongodb_test has been refactored as it was a flaky test  (now it uses helm chart for mongodb)
- nats_cluster_test has been refactored to reduce errors in logs
- nats_helper has been update to retry jobs on failures
- redis_helper has been updated to use helm chart to deploy a redis cluster 
- chaos_test has been renamed as disruption_test and moved to sequential execution folder
- prometheus_metrics_test has been moved to sequential execution folder to avoid interactions from other tests
- setup_test has been refactored to optimize the spin up process deploying all the webhooks and waiting all of them at once instead of waiting them one by one before continuing

And which is the result? (ignore the building time as those steps do different things in each case)

main e2e test needs > 2 hours
image

e2e test on pr needs < 1 hour
image
image

I can expect that the needed time on main e2e tests will be similar to current times on PRs

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/2829
Fixes https://github.com/kedacore/keda/issues/4244

### CODE REVIEW

**Comment by JorTurFer** [comment]
Yeah, I have seen it.
IDK how many times I have triggered them without fails, but I still prefer to detect them here and not after merging the changes 😄

**Comment by JorTurFer** [comment]
Let's start again

**Comment by JorTurFer** [comment]
> /run-e2e **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/4590707455)

This has failed because the namespace deletions have failed. IDK if there is something that I can do to mitigate this or if it has been a transient fail: 
image

Maybe increasing the deletion timeout?

**Review by zroubalik — APPROVED** [review]
tremendous work!

**Pull request merged**
