### PR TITLE
fix: scaleobject ready condition 'False/Unknow' to 'True' requeue

### LINKED ISSUE #3096: ScaledObject ready condition changed will not fix HPA in some situation
### Report

ScaledObject:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 8
  labels:
    app: aabb-ab007
  name: aabb-ab007
  namespace: default
  ownerReferences:
  - apiVersion: basefeatures.symcn.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: BaseFeature
    name: aabb-ab007
    uid: f9ef1592-b164-4c55-a518-4eb01b832cce
spec:
  fallback:
    failureThreshold: 5
    replicas: 2
  maxReplicaCount: 3
  minReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aabb-ab007
  triggers:
  - metadata:
      app: aabb-ab007
      metricName: QPS
      scalerAddress: keda-external.default.svc:8080
      targetSize: "200"
    metricType: AverageValue
    name: QPS
    type: external
  - metadata:
      app: aabb-ab007
      value: "51"
    metricType: Utilization
    name: cpu
    type: cpu
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is performed because triggers are active
    reason: ScalerActive
    status: "True"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  externalMetricNames:
  - s0-QPS
  health:
    s0-qps:
      numberOfFailures: 0
      status: Happy
  lastActiveTime: "2022-06-01T03:21:46Z"
  originalReplicaCount: 1
  resourceMetricNames:
  - cpu
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment

```

If my own `keda-external` service offline, `Keda metrics-apiserver` logic will update HPA resource current metrics, and will trigger `Keda operator` Reconcile to update `HPA.Spec`. And then, the `keda-external` service online, `Keda operator` just update `ScaledObject` Ready condition, but if the CPU metrics is zero, HPA resource will not modify, so `ScaledObject` will not fix `HAP` resource.

### Expected Behavior

Will auto fix `HPA` resource when the `keda-external` service back to normal.

### Actual Behavior

If the CPU metrics is zero always, the `HPA` resouce will not update.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.20

### Platform

Any

### Scaler Details

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by champly**
Signed-off-by: champly <champly@outlook.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #3096 

Relates to #

### CODE REVIEW

**Review by tomkerkhove — COMMENTED** [review]
Can you update the changelog please?

**Comment by champly** [comment]
> Can you update the changelog please?

ok, already added, PTAL.

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!

**Comment by zroubalik** [comment]
Thanks for the contribution!

**Comment by zroubalik** [comment]
@champly do you think you can write some test for this scenario?

**Comment by champly** [comment]
> @champly do you think you can write some test for this scenario?

ut have been added, and an `external_mock` service is hacked to simulate `external service` exceptions. PTAL

**Review by zroubalik — COMMENTED** [review]
Looking good, nice!

The only thing, why the changed perms on the Azure scaler files?

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
