### PR TITLE
bump deps and pin k8s.io to 0.28.5

### PR DESCRIPTION
**Pull request by zroubalik**
### Checklist

- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
FOSSA issue: 
image

**Comment by zroubalik** [comment]
> FOSSA issue: image

This transitive dependency is dual licensed under BSD a GPLv2 licenses. If we assume that we are gonna use the BSD (which is a permissive open source license), then I think that we are good with ingoring this warning and proceed. But I am not a licensing expert nor lawyer :)

Thoughts? @kedacore/keda-maintainers

**Comment by JorTurFer** [comment]
> > FOSSA issue: image
> 
> This transitive dependency is a dual licensed library. Licensed under BSD a GPLv2 licenses. If we assume that we are gonna use the BSD (which is a permissive open source license), then I think that we are good with ignoring this warning and proceed. But I am not a licensing expert nor lawyer :)
> 
> Thoughts? @kedacore/keda-maintainers @joelsmith
> 
> Our dependency: [DataDog/datadog-api-client-go](https://github.com/DataDog/datadog-api-client-go) The transitive dependency causing problems: [DataDog/zstd](https://github.com/DataDog/zstd)

yes, you're right! I've updated FOSSA adding an exception for this

**Comment by JorTurFer** [comment]
but static checks and e2e tests are failing too

**Pull request merged**
