### PR TITLE
Add RabbitMQ `publishRate` trigger

### LINKED ISSUE #1643: RabbitMQ rate based trigger (Published/sec.)
### Proposal

Add a trigger based on the Published/sec. metric on a queue.

### Use-Case

We have a workload that has a Publishing rate that varies between 1k and 3k/sec. When we are keeping up with the throughput, the Ready count on the queue is 0 regardless of the Publishing rate. Even using the Unacked count, that stay around a few hundred, independent of the Publishing rate. While handling 3k/sec. requires three times the instances as 1k/sec., the metrics I can choose now look identical. I have to wait for scaling to reach min. instances (since Ready == 0), then wait for a backlog to build up (since we're running too few instances to keep up), then have the instances scale up to something (since Ready > 0 now) and keep scaling up until we're at a high enough instance count to work through the backlog, reach Ready == 0 again and scale back down to min. instances.

This keeps bouncing between min. instances and some scaled up count over and over again.

I would expect to be able to configure two triggers
- X messages/sec. per instance to scale against the Published/sec. rate on the queue (to handle the steady-state happy path)
- Y backlog (Ready/Unacked backlog) per instance (to handle cases where a dependency slowed or stopped processing for a while or otherwise failed to keep up)

### PR DESCRIPTION
**Pull request by rwkarg**
Signed-off-by: Ryan Karg <rwkarg@gmail.com>

Added an additional trigger for RabbitMQ scaling on `publishRate`.

This allows for higher throughput workloads to scale based on the incoming message rate. This is useful because the message backlog does not often correlate with the desired instance count.

Both `publishRate` and `queueLength` triggers can be specified on a single ScaledObject. I would imagine the normal case would be to use both of these triggers.

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [X] Tests have been added
~~[ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~~
- [X] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
  - https://github.com/kedacore/keda-docs/pull/388
- [X] Changelog has been updated

Fixes #1643

### CODE REVIEW

**Comment by rwkarg** [comment]
Comparison of two different but similar workloads over 24 hrs. The orange line on the graph correlates with the instance count. Both workloads are in the 1k-3k/sec. range and have smooth rates of change over the day so the instance count would expect to be smooth as well to match that.

Using only `queueLength` it bounces bewteen min. instances and a too-high instance count after a backlog builds up:
image

Using `publishRate` (as well as `queueLength`) it stays steady:
image

In the second example, we actually had an impact on a dependency that cause a backlog to build up so the `queueLength` trigger eventually resulted in a higher instance count that you can see in the two spikes at the beginning of the graph.

**Review by ahmelsayed — APPROVED** [review]
LGTM

**Review by zroubalik — APPROVED** [review]
LGTM, thanks @rwkarg !

**Comment by zroubalik** [comment]
Let's merge this once docs PR is finalized.

**Comment by tomkerkhove** [comment]
Thanks a ton @rwkarg!

**Pull request merged**
