### PR TITLE
Refactor cron scaler config

### PR DESCRIPTION
**Pull request by rickbrouwer**
- Refactor the scaler to match the new metadata guidelines.

### Checklist

- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [X] Tests have been added
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Related: [5797](https://github.com/kedacore/keda/pull/5797)

### CODE REVIEW

**Comment by rickbrouwer** [comment]
Hi @wozniakjan 

I've also refactored the cron scaler to match the new metadata guidelines. Can you please take a quick look at the code to make sure that it's matches the new metadata guidelines? 🙏

**Comment by rickbrouwer** [comment]
@wozniakjan I think only the run-e2e for cron must run, but maybe I'm wrong

**Comment by wozniakjan** [comment]
> @wozniakjan I think only the run-e2e for cron must run, but maybe I'm wrong

you are right, thanks for reminding me :)

**Comment by wozniakjan** [comment]
I think this is ok to merge, ptal @kedacore/keda-contributors

**Review by JorTurFer — APPROVED** [review]

**Pull request merged**
