### PR TITLE
feat: support TriggerAuthentication properties from ConfigMap

### PR DESCRIPTION
**Pull request by wozniakjan**
This PR proposes an implementation to support for `TriggerAuthentication` properties from `ConfigMap`.

### Checklist

- [X] Tests have been added
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [X] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) - https://github.com/kedacore/keda-docs/pull/1252
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/4830

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by wozniakjan** [comment]
/run-e2e internal
the failure of e2e tests seems unrelated to the changes, perhaps flake?
```
Failed tests:
7765
	Execution of tests/internals/scaling_modifiers/scaling_modifiers_test.go, has failed after "three" attempts
```

**Comment by zroubalik** [comment]
> /run-e2e internal the failure of e2e tests seems unrelated to the changes, perhaps flake?
> 
> ```
> Failed tests:
> 7765
> 	Execution of tests/internals/scaling_modifiers/scaling_modifiers_test.go, has failed after "three" attempts
> ```

yes :(

**Pull request merged**
