### PR TITLE
Redis cluster scalers

### LINKED ISSUE #883: Support Redis cluster topology for the Redis scaler
Support Redis cluster topology for the Redis scaler

See discussion for context: https://github.com/kedacore/keda/discussions/872#discussion-5906

### Use-Case

Right now, the Redis scaler only supports non-clustered Redis topology. In our stack, however, we use Redis cluster to provide horizontal scalability and HA. Some cloud providers such as AWS and Azure also offer Redis cluster in their offering.

See https://redis.io/topics/cluster-spec and https://redis.io/topics/cluster-tutorial for more info on the Redis cluster topology.

### Specification

- [ ] Support specifying multiple addresses in the `address` field of the trigger spec (one for each node).

Since the cluster topology requires the client to be cluster-aware, I don't know if this would be a separate scaler or if it could be integrated with the current Redis scaler with some more fields in the trigger (perhaps `topology = normal (default), OR cluster` and `addresses` (if `topology` is `cluster`).  In our applications, simply swapping for a cluster-aware client was the only require step in order to support this topology (`redis-py-cluster` instead of `redis-py`).

### PR DESCRIPTION
**Pull request by goku321**
Add Redis cluster support for Redis list and Redis streams scalers.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Tests have been added
- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs (https://github.com/kedacore/keda-docs/pull/335)
- [x] Changelog has been updated

Relates to #883

### CODE REVIEW

**Comment by goku321** [comment]
Will create the docs PR soon.

**Comment by goku321** [comment]
Docs PR - https://github.com/kedacore/keda-docs/pull/335

**Comment by zroubalik** [comment]
Looking good, I am not Redis expert though :)

@mboutet willing to take a look on this?

**Review by zroubalik — APPROVED** [review]

**Review by ahmelsayed — APPROVED** [review]
LGTM too

**Pull request merged**
