### PR TITLE
Introduce GitHub Code Scanning

### PR DESCRIPTION
**Pull request by tomkerkhove**
Introduce GitHub Code Scanning.

I'm not using Snyk here since this is built-in but if we want to use that instead (given it will do all our container scanning) I'm happy to change it.

### CODE REVIEW

**Comment by zroubalik** [comment]
Have you been thinking in incorporating hits under https://github.com/kedacore/keda/blob/v2/.github/workflows/pr-validation.yml ?

**Comment by tomkerkhove** [comment]
Honestly, no. Just wanted to keep it separate but happy to merge if you prefer!

**Comment by zroubalik** [comment]
The amount of checks is huge 😄 
checks

**Comment by tomkerkhove** [comment]
I'll move it!

**Comment by tomkerkhove** [comment]
> The amount of checks is huge 😄
> checks

YOu should have a look at how many I have here 😂 https://github.com/tomkerkhove/promitor/pull/1265

**Comment by zroubalik** [comment]
> YOu should have a look at how many I have here 😂 [tomkerkhove/promitor#1265](https://github.com/tomkerkhove/promitor/pull/1265)

No way man 😄 

I got your point, sometimes the break down is good. But the stuff you have added `CI / Static Checks` is a perfect fit.

**Review by zroubalik — APPROVED** [review]
LGTM

**Pull request merged**
