### PR TITLE
fixing example labels

### PR DESCRIPTION
**Pull request by jeffhollan**
Discovered in https://github.com/kedacore/keda/issues/158 thanks to @zach-dunton-sf

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@yaron2 You might want to look at https://github.com/apps/kubevalidator to verify these YAML in the CI to avoid this

**Comment by yaron2** [comment]
thanks @tomkerkhove will do

**Comment by tomkerkhove** [comment]
Actually I can take this up - Will create issue if you want

**Comment by yaron2** [comment]
Great

**Comment by aminebizid** [comment]
GREAT.
THANK YOU

**Comment by aminebizid** [comment]
At least, thanks to this bug, now I know how to debug GO in Kubernetes using vscode :)

**Pull request merged**
