### PR TITLE
Upgrade to the latest new-relic-go v2 client

### PR DESCRIPTION
**Pull request by smcavallo**
Upgrade to the latest new-relic-go v2 client -> https://github.com/newrelic/newrelic-client-go/releases/tag/v2.51.2
(currently using https://github.com/newrelic/newrelic-client-go/releases/tag/v1.1.0)

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Thanks a lot! Could you update the changelog with this change? it's an interesting topic to include under the section `Others`

**Comment by smcavallo** [comment]
> Thanks a lot! Could you update the changelog with this change? it's an interesting topic to include under the section `Others`

Changelog has been updated - thanks!!!!

**Review by JorTurFer — APPROVED** [review]
Thanks a lot!

**Review by wozniakjan — APPROVED** [review]
lgtm, thank you!

just curious, should we re-run e2e tests since https://github.com/kedacore/keda/pull/6326 also merged recently? just to be on the safe side?

**Comment by smcavallo** [comment]
@wozniakjan - it wouldn't hurt, thanks!!!

**Pull request merged**
