### PR TITLE
enable gocyclo in golintCI and resolve the warnings

### PR DESCRIPTION
**Pull request by girishramnani**
Signed-off-by: Girish Ramnani <girishramnani95@gmail.com>

enable gocyclo in golintCI and resolve the warnings by refactoring certain functions

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)
~~- [ ] Tests have been added~~ N/A
~~- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs~~ N/A
- [ ] Changelog has been updated

Partially https://github.com/kedacore/keda/issues/1158

### CODE REVIEW

**Comment by girishramnani** [comment]
blocked on https://github.com/kedacore/keda/pull/1337

**Comment by ahmelsayed** [comment]
@girishramnani can you rebase the change to make sure the CI passes

**Comment by girishramnani** [comment]
done @ahmelsayed

**Comment by girishramnani** [comment]
Should I update the Changelog for this PR?

**Review by ahmelsayed — APPROVED** [review]

**Comment by ahmelsayed** [comment]
Thanks again @girishramnani

**Pull request merged**
