### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by ansonauhk**
Update change log for https://github.com/kedacore/keda/pull/1073
Signed-off-by: Anson Au ansonau@gmail.com
### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [x] Changelog has been updated

Relates to #967

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, but can you fix the DCO issues please?

**Comment by ansonauhk** [comment]
> LGTM, but can you fix the DCO issues please?

Tried but face an error. Any idea?

(base) Ansons-MBP:keda anson$ git commit --amend --signoff
[patch-1 1e26138] Update CHANGELOG.md
 Author: Anson Au <ansonauhk@users.noreply.github.com>
 Date: Sun Sep 6 20:01:27 2020 +0800
 1 file changed, 1 insertion(+)
(base) Ansons-MBP:keda anson$ git push --force-with-lease origin patch-1
remote: Permission to kedacore/keda.git denied to ansonauhk.
fatal: unable to access 'https://github.com/kedacore/keda.git/': The requested URL returned error: 403

**Comment by zroubalik** [comment]
@ansonauhk could you give us output of:
```bash
git remote -v
```

**Comment by ansonauhk** [comment]
Will open new one to fix DCO

**Pull request closed without merging**
