### PR TITLE
Add information about e2e test in CONTRIBUTING

### PR DESCRIPTION
**Pull request by turbaszek**
I didn't know that we had such nice doc on e2e test 🚀 

Signed-off-by: Tomek Urbaszek <tomasz.urbaszek@polidea.com>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Comment by zroubalik** [comment]
@turbaszek yeah, running nightly https://github.com/kedacore/keda/actions?query=workflow%3A%22nightly+e2e+test%22

**Comment by tomkerkhove** [comment]
> @tomkerkhove @zroubalik do we run e2e test regularly?

I don't do code contributions since I don't master Go; #1138 is an example of that 😂

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
@turbaszek can you run doctoc please?

**Comment by turbaszek** [comment]
> @turbaszek can you run doctoc please?

I'm running it with every commit. The table of content was not updated because the default depth value is 2. I will increase it then

**Review by zroubalik — APPROVED** [review]
Thanks!

**Pull request merged**
