### PR TITLE
[v2] use unique metric for all scalers

### PR DESCRIPTION
**Pull request by AmithGanesh**
#https://github.com/kedacore/keda/issues/733
Thank you for contributing!
     
     Read more about how you can contribute in our contribution guide:
     https://github.com/kedacore/keda/blob/master/CONTRIBUTING.md
-->

_Provide a description of what has been changed_

### Checklist

- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added

Fixes #

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Hi @AmithGanesh, would you mind updating the docs as well please?

**Comment by AmithGanesh** [comment]
sure will update the documentation by the end of this week

**Comment by zroubalik** [comment]
@AmithGanesh you should rebase your fork to omit already merged commits.

And I think we should add some logic around this, as proposed in https://github.com/kedacore/keda/issues/733. For example add some check to ScaledObject and if there are multiple triggers specified, enforce users to set metric name for each one -> and add documentation for this.

**Comment by zroubalik** [comment]
@AmithGanesh could you please rebase your commit so we can move forward?

**Comment by zroubalik** [comment]
@AmithGanesh it looks like you are busy, I understand that's this could happen, not a problem :) @samuelmacko agreed to finish this feature as we hope to have this finished soon. Thanks for your contribution!

**Pull request closed without merging**
