### PR TITLE
chore: Remove deprecated AAD-Pod-Identity and AWS-KIAM auths

### PR DESCRIPTION
**Pull request by JorTurFer**
Both auth were deprecated and we have to remove it for v2.15.
I know there are still some references to ActiveDirectoyEndpoint which aren't directly required either because we won't support aad-pod-identity anymore. They will be removed as part of [this other PR](https://github.com/kedacore/keda/pull/5471) that supports new SDKs and the merge conflicts will already be terrible without removing more fields than the strictly required on this PR

### Checklist

- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/5035
Fixes https://github.com/kedacore/keda/issues/5085

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]

**Comment by vladimirglazkov** [comment]
Hey @JorTurFer !
There is an announcement that AAD Pod Identity support will be removed in 2.15.
https://keda.sh/docs/2.14/authentication-providers/azure-ad-pod-identity/
So why did you remove it in 2.14?

**Comment by JorTurFer** [comment]
> So why did you remove it in 2.14?

What do you mean? v2.14 still has support for it: https://github.com/kedacore/keda/blob/v2.14.0/pkg/scalers/azure/azure_aad_podidentity.go

**Pull request merged**
