### PR TITLE
Add GCP identity authentication when using Pubsub Scaler

### PR DESCRIPTION
**Pull request by jmalvarezf-lmes**
Hi,

This tries to partially fix this issue: https://github.com/kedacore/keda/issues/2048. Basically the fix consist on using the gcp identity framework so that when you do a request to stackdriver to get the number of undelivered messages, you use the service account associated to the machine (GCE), instead of using a service account in a secret. That allows to use this very useful scaler without creating a service account and a secret and you can use a Cluster Trigger Authentication widely to use the underlying service account. I couldn't create tests, as this relies on being executed on GCP. But I've tested it in our environment and it works.

Hope it is useful for you.

I wait for you to check this, and if it is useful, and you agree, I will change the docs to adapt to this new method.

Regards,

Jose Maria.

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Looking good! Please update Changelog and modify docs for 2.5. Thanks!

**Comment by jmalvarezf-lmes** [comment]
@zroubalik please check if everything is fine. Thank you!

**Review by zroubalik — APPROVED** [review]
LGTM, thanks for the contribution @jmalvarezf-lmes!

**Comment by jmalvarezf-lmes** [comment]
You are welcome!

**Comment by hermanbanken** [comment]
Nice, thanks!

**Comment by hermanbanken** [comment]
Did I understand correctly how to use it (see docs I attempted to create)?

**Comment by jmalvarezf-lmes** [comment]
@hermanbanken yes, that is the idea. We have it running like this in our environment. We do not use workload identity, but the functionality is exactly the same.

**Comment by hermanbanken** [comment]
I completely missed https://github.com/kedacore/keda-docs/pull/565... 😅

**Comment by zroubalik** [comment]
@hermanbanken lol 😄 but would be nice if you can add your improvements

**Pull request merged**
