### PR TITLE
feat: Add support for SAS tokens for authentication in Azure Service Bus scaler.

### LINKED ISSUE #2920: Provide support for using SAS token in Service Bus scaler
### Proposal

Provide support for using [SAS token in Service Bus scaler](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas).

### Use-Case

Different scenario for authentication, similar to https://github.com/kedacore/keda/issues/2705

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by v-shenoy**
With the SDK update, this is now supported. No changes required.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #2920 

Relates to https://github.com/kedacore/keda-docs/pull/938

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
can't we just provide sas connection string in the connection string field? I see that we use them in the same way, the client is generated using the same function.

**Comment by v-shenoy** [comment]
> can't we just provide sas connection string in the connection string field? I see that we use them in the same way, the client is generated using the same function.

You're completely right, lol.
Before I started writing code, I thought I would have to call a different SDK method, and I completely missed while implementing that I am calling the same constructor. 

This is why people should not be coding when sleep deprived. :facepalm: Might just be the dumbest piece of code I have written.

**Comment by v-shenoy** [comment]
Okay, I can just update the changelog in this PR, and we can close on the issue. (And update the docs to mention that the connection string field accepts both types).

**Comment by JorTurFer** [comment]
sounds good! 😄

**Comment by JorTurFer** [comment]
I have been thinking and I'm not sure if we need to update the changelog neither because we haven't changed anything, it's already supported. WDTY?

**Comment by v-shenoy** [comment]
> I have been thinking and I'm not sure if we need to update the changelog neither because we haven't changed anything, it's already supported. WDTY @kedacore/keda-core-contributors ?

Updating the changelog, because this was a feature not available in the previous KEDA versions. So, someone going through the release notes should know about this.

**Comment by tomkerkhove** [comment]
I agree that we should add this to the changelog as this is another authentication type.

However, maybe we should use "Shared Access Signature (SAS)" to clarify what it is @v-shenoy. Not everyone knows the abbreviations

**Review by JorTurFer — APPROVED** [review]

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
