### PR TITLE
Add singular and short names to scaledobject spec

### PR DESCRIPTION
**Pull request by lee0c**
Addresses #200 as well as adding a singular form for "scaledobjects"

I'd love input on whether these are the shortnames you'd like to see.

### CODE REVIEW

**Comment by lee0c** [comment]
@jeffhollan Any idea why kubevalidator is failing? Does it not handle helm templates? This deploys on my cluster.

**Comment by ahmelsayed** [comment]
I think you're probably right that it doesn't handle helm templates as valid yaml. I don't see any reference on their repo regarding helm or go templates.

**Comment by ahmelsayed** [comment]
personally I'd rather just have `sco` to be good citizens and not squat on too many names. I don't know how kubernetes handles conflicts with these short names.

**Comment by lee0c** [comment]
@ahmelsayed Anything else you need to merge this? The kubevalidator check is not going to succeed regardless

**Comment by tomkerkhove** [comment]
For what it's worth - LGTM

**Comment by yaron2** [comment]
lgtm

**Pull request merged**
