### PR TITLE
Kafka Scaler: add back `strings.TrimSpace()` function for saslAuthType

### PR DESCRIPTION
**Pull request by dttung2905**
Hi team, 
This PR aims to fix https://github.com/kedacore/keda/issues/4689. Not sure it could be backported to 2.10. Please advise me on this matter. :pray: 

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements] (https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog) (will update after given the LGTM from maintainers)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Nice fix!
Could you update the changelog as well?

**Comment by dttung2905** [comment]
@JorTurFer Thanks for the quick review ! Should I put the changelog under the `unreleased` or can we backport to `2.10.1` as some users have reported this issue :thinking: ?

**Review by JorTurFer — APPROVED** [review]

**Review by JorTurFer — APPROVED** [review]
LGTM!
Thanks for the fix 🙇

**Pull request merged**
