### PR TITLE
chore: Renovate configuration for single PR

### PR DESCRIPTION
**Pull request by tomkerkhove**
Use a single PR for all dependency updates

### CODE REVIEW

**Comment by zroubalik** [comment]
That's nice, but do you think that we can have k8s deps in one pr and the rest in another?

**Comment by tomkerkhove** [comment]
I'll get in touch with them

**Comment by tomkerkhove** [comment]
Opened https://github.com/renovatebot/renovate/discussions/10379

**Comment by tomkerkhove** [comment]
Wut 🤔

**Comment by tomkerkhove** [comment]
@zroubalik This should work since it uses last-one-wins

**Comment by zroubalik** [comment]
@tomkerkhove awesome! thanks a lot for this!

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
