### PR TITLE
Update devcontainer to use Python 3.

### LINKED ISSUE #2019: devcontainer is using Python 2.7 for pre-commit
### Report

When I try to execute `pre-commit run --all-files` using devcontainers I get an error related with outdated python version ([and also it's unmaintained](https://www.python.org/doc/sunset-python-2/))
There is also another problem related with the End Of Line in bash script because my local computer is windows and the container is UNIX. 

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python', '-mvirtualenv', '/root/.cache/pre-commit/repoJzxre_/py_env-python2.7', '-p', '/usr/bin/python')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
        mod_name, _Error)
      File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
        __import__(mod_name)  # Do not catch exceptions initializing package
      File "/usr/local/lib/python2.7/dist-packages/virtualenv/__init__.py", line 3, in <module>
        from .run import cli_run, session_via_cli
      File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/__init__.py", line 13, in <module>
        from .plugin.activators import ActivationSelector
      File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
        from .base import ComponentBuilder
      File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/plugin/base.py", line 5, in <module>
        from backports.entry_points_selectable import entry_points
    ImportError: No module named entry_points_selectable
    
Check the log at /root/.cache/pre-commit/pre-commit.log
```

### Expected Behavior

I expect to be able to run  `pre-commit run --all-files`  and get the linting status
The UNIX EOL should be persisted, ignoring the OS in `*.sh` (Bash in Windows should still recognize it)

### Actual Behavior

I am not able to run  `pre-commit run --all-files`  and get the linting status (and I need to run it using the GitHub Action) xD
All EOL change according the OS

### Steps to Reproduce the Problem

1. Create a fresh branch from master
2. Run Visual Studio Code with support for dev containers
3. Once the container starts, execute `pre-commit run --all-files`

### Anything else?

I'm fixing it for myself, I can create the PR

### PR DESCRIPTION
**Pull request by coderanger**
Fixes #2019

### CODE REVIEW

**Review by ahmelsayed — APPROVED** [review]

**Comment by ahmelsayed** [comment]
@coderanger DCO is missing

**Comment by coderanger** [comment]
Heh, that's what I get for taking the web edit shortcut :D Will fix locally.

**Comment by coderanger** [comment]
Closing in favor of #2021

**Comment by ahmelsayed** [comment]
> Heh, that's what I get for taking the web edit shortcut :D Will fix locally.

Last time I used web edit I caused a syntax error then a fmt error, and thought the same :)

**Pull request closed without merging**
