### PR TITLE
chore: Introduce KEDA v2.13 and estimate v2.16 in roadmap

### PR DESCRIPTION
**Pull request by tomkerkhove**
Introduce KEDA v2.13 and estimate v2.16 in roadmap.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to https://github.com/kedacore/keda/issues/5275

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
We should add this a step into release process

**Review by zroubalik — APPROVED** [review]

**Review by zroubalik — COMMENTED** [review]
Let's track this in In release tracker or release process

**Comment by tomkerkhove** [comment]
> We should add this a step into release process

This is already the case: https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md#8-prepare-next-release

**Pull request merged**
