### PR TITLE
Support for aws secret manager authentication

### PR DESCRIPTION
**Pull request by nitishchauhan0022**
Added the Support for `TriggerAuthentication` using aws secret manager
### Checklist

- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [ ] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [ ] Tests have been added
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to #4628

### CODE REVIEW

**Comment by JorTurFer** [comment]
Looking good! ❤️ 
Could you rebase the main branch (there are some merge conflicts) and also add some e2e test for this feature? We already have some e2e tests for Azure Key Vault that you could use as example: https://github.com/kedacore/keda/tree/main/tests/secret-providers
In order to have the KMS, you need to create it through the [testing-infrastructure](https://github.com/kedacore/testing-infrastructure) repo (we can help you with that if you want)
Also, this feature requires changes in docs explaining it 🙏

**Comment by JorTurFer** [comment]
Any update? We aim to cut a release next week

**Comment by nitishchauhan0022** [comment]
I am really occupied by other things. I don't have plans to do this in coming week.

**Comment by zroubalik** [comment]
Replaced by https://github.com/kedacore/keda/pull/5162

**Pull request closed without merging**
