### PR TITLE
Update CI to run build/unit tests on arm64

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

This PR enables build and unit tests on ARM64 - the job is running in docker container running on ARM64 machine.
There should be follow work to be done on some smoke e2e tests on ARM64 and on producing ARM64 images.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates: #779

### CODE REVIEW

**Comment by nlamirault** [comment]
`v2.5.0` is released. But on Docker Hub, Docker images seems to be only *amd64*

**Comment by tomkerkhove** [comment]
GitHub Container Registry is our recommended place to be.

https://github.com/kedacore/keda/discussions/1700

**Comment by tomkerkhove** [comment]
We should actually stop publishing there now that GHCR is GA.

**Comment by tomkerkhove** [comment]
However, ARM is still WIP - We run our CI on it already but not publish images yet.
See #779

**Comment by zroubalik** [comment]
@nlamirault yeah, we are looking for someone who will contribute the ARM stuff.

**Pull request merged**
