### PR TITLE
Move to getParameterFromConfigV2 for input, excluding auth

### PR DESCRIPTION
**Pull request by robpickerill**
Moves the AWS CloudWatch scaler to use getParameterFromConfigV2 for input. 

Context is from a conversation started here: https://github.com/kedacore/keda/pull/5635#discussion_r1545724939

There is one TODO here, which is to move authorization over. I'll present that in a separate PR to avoid a large PR landing, and I can spend more time to read through the authorization code.

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
LGTM! Nice improvement!
PTAL @dttung2905

**Comment by dttung2905** [comment]
Sorry I will try to take a look tomorrow morning😬

**Comment by JorTurFer** [comment]
@robpickerill ,
Could you fix DCO check? You have the resolution steps clicking in the link
image

**Review by dttung2905 — COMMENTED** [review]
Hi @robpickerill,

First of all, thank you so much for putting in effort into making this PR. Generally, its LGTM. Just one minor point that we have another PR https://github.com/kedacore/keda/pull/5319 that changes how `getParameterFromConfigV2` works.

Is this PR blocking the other PR https://github.com/kedacore/keda/pull/5635 ? We can either:

(1) wait for https://github.com/kedacore/keda/pull/5319 to be merged first , then this PR and https://github.com/kedacore/keda/pull/5635 or 

(2) we move forward with this current implementation of `getParameterFromConfigV2` in the `main` branch. I will rebase yours into https://github.com/kedacore/keda/pull/5319

WDYT? @JorTurFer I'm in favour of (1) and I will try my best to merge my PR. Its almost done tbh :D

**Comment by robpickerill** [comment]
> Hi @robpickerill,
> 
> First of all, thank you so much for putting in effort into making this PR. Generally, its LGTM. Just one minor point that we have another PR https://github.com/kedacore/keda/pull/5319 that changes how `getParameterFromConfigV2` works.
> 
> Is this PR blocking the other PR https://github.com/kedacore/keda/pull/5635 ? We can either:
> 
> (1) wait for https://github.com/kedacore/keda/pull/5319 to be merged first , then this PR and https://github.com/kedacore/keda/pull/5635 or 
> 
> (2) we move forward with this current implementation of `getParameterFromConfigV2` in the `main` branch. I will rebase yours into https://github.com/kedacore/keda/pull/5319
> 
> WDYT? @JorTurFer I'm in favour of (1) and I will try my best to merge my PR. Its almost done tbh :D 

Thanks @dttung2905, by all means take option 1 for me, feel free to tag me in the updates for when you finalize the implementation and I'll refactor this PR as needed.

**Comment by JorTurFer** [comment]
Let's wait with this and then rebase it if you agree

**Comment by dttung2905** [comment]
> @dttung2905 we can close this, right?

Yes we can

**Comment by zroubalik** [comment]
> > @dttung2905 we can close this, right?
> 
> Yes we can

Thanks for the work anyway!

**Pull request closed without merging**
