### PR TITLE
refactor: Replace lib/pq with pgx in a PostgreSQL scaler

### LINKED ISSUE #4704: Provide a way to use multihost connection in a PostgreSQLScaler
### Proposal

Right now the PostgreSQL scaler uses a `lib/pq` library which is outdated and doesn't support a lot of features we are used to in the C version of `libpq` and its derivatives.

One of them and critical in my eyes is a lack of multi-host connection to highly available PostgreSQL instances.

Right now in case of failover of the master node we have to somehow inform KEDA operator that it should use another connection string/host to pull metrics. That's annoying. 

One of the easiest way to fix it - just to replace `lib/pq` with `pgx` I guess.

### Use-Case

I would like to have a possibility to use multi-host connection strings like this `postgresql://airflow:xxxxx@host1,host2:6432/airflow?sslmode=verify-full&target_session_attrs=read-write` in a PostgreSQL scaler.

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by a-narsudinov**
The development of `lib/pq` is over and the library doesn't receive any fixes or new features. This is sad because nowadays `lib/pq` lacks a of lot of features we are get used to in the C version of `libpq` and its derivatives.

I've experienced troubles with this unimplemented stuff in `lib/pq`:
- Multi-host connection, which is important for a high availability
- Support of parsing CA certificate of PostgreSQL server stored in a `~/.postgresql` folder that led to a negative user experience

I believe there are more missing features.

These things will be never fixed in `lib/pq`, so in this patch, we replace the abandoned `lib/pq` with an actively developing `pgx`.

I tested this patch in my environment and got that I needed: high avaliabillity with help of multihost connection which just works in `pgx` driver.

I think that it mustn't have a breaking changes and may be merged easily.

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4704

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
@a-narsudinov nice, thanks for the contribution. Could you please add a test to cover the multihost scenario which is discussed in the issue?

**Comment by a-narsudinov** [comment]
@zroubalik I believe I can add for this scenario, but could you please help me figure out how to implement it better? I guess the proper way to test it is to modify the current end-to-end `postgresql_test.go` test and make it run a master-replica PostgreSQL setup. Am I right?

**Comment by zroubalik** [comment]
> @zroubalik I believe I can add test for this scenario, but could you please help me figure out how to implement it better? I guess the proper way to test it is to modify the current end-to-end `postgresql_test.go` test and make it run a master-replica PostgreSQL setup. Am I right?

Yeah, that's what I was thinking about https://github.com/kedacore/keda/blob/main/tests/scalers/postgresql/postgresql_test.go

Also, do you think it makes sense to add unit test for parsing the multihost setup?

**Comment by a-narsudinov** [comment]
To be honest, I didn't even test the case when we parse the data from separate fields and use it to build a connection string via strings joiner.  By the way it should work nicely right now, but I suppose we should add a unit test for this scenario just so we won't forget about this very nice feature during the next refactoring and won't break it.  This is not so much work compared to the e2e test, so we just may do it, even if it isn't essential now.

**Comment by a-narsudinov** [comment]
I'm really interested in merging this PR into the mainline until the upcoming release, how much time do I have to do the tests? :D

**Comment by zroubalik** [comment]
> I'm really interested in merging this PR into the mainline until the upcoming release, how much time do I have to do the tests? :D

😄 We plan to do release later this week (Wed-Thu). The best would be to include the test by Tuesday EOD.

**Comment by a-narsudinov** [comment]
Hi @zroubalik! I think that this PR looks good now with a new tests. Could you please have a look? :)

**Comment by a-narsudinov** [comment]
I'm sorry, I made a typo in my email and I had to re-push one more time :(

**Review by zroubalik — APPROVED** [review]
LGTM

thanks for the contribution!

**Pull request merged**
