### PR TITLE
Rabbitmq scaler: Allow providing separate parameters for user and password

### PR DESCRIPTION
**Pull request by xoanmm**
Add the possibility to use username/password as separate parameters for the RabbitMQ scaler, as well as domain

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #

Relates to #2513

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@xoanmm Any thought if we can close this PR soon? We are planning to release in 2 weeks.

**Comment by xoanmm** [comment]
> @xoanmm Any thought if we can close this PR soon? We are planning to release in 2 weeks.

@tomkerkhove Sorry the big delay, I'll try to tackle this PR in the following days

**Review by zroubalik — COMMENTED** [review]
Any update here?

**Comment by tomkerkhove** [comment]
Closing due to inactivity for a long period, feel free to re-open if you have time to complete it anyway.

**Pull request closed without merging**
