### PR TITLE
fix: respect all required demands in azure pipeline scaler

### PR DESCRIPTION
**Pull request by EugeneLugovtsov**
Fix issue with Azure Pipelines Scaler. When Azure DevOps does not provide `Agent.Version` keda may scale a wrong agent.

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #
[#4404](https://github.com/kedacore/keda/issues/4404)
Relates to #

### CODE REVIEW

**Comment by EugeneLugovtsov** [comment]
@zroubalik may I ask you to review this PR?

**Comment by JorTurFer** [comment]
@Eldarrin, could you take a look?

**Review by Eldarrin — CHANGES_REQUESTED** [review]
Can you replace the function with this and resubmit, may fix the issue.

`
func stripAgentVFromArray(array []string) []string {
	var result []string
	for _, item := range array {
		if !strings.HasPrefix(item, "Agent.Version") {
			result = append(result, item)
		}
	}
	return result
}

func getCanAgentDemandFulfilJob(jr JobRequest, metadata *azurePipelinesMetadata) bool {
	countDemands := 0
	demandsInJob := stripAgentVFromArray(jr.Demands)
	demandsInScaler := stripAgentVFromArray(strings.Split(metadata.demands, ","))
	for _, demandInJob := range demandsInJob {
		for _, demandInScaler := range demandsInScaler {
			if demandInJob == demandInScaler {
				countDemands++
			}
		}
	}
	if metadata.requireAllDemands {
		return countDemands == len(demandsInJob) && countDemands == len(demandsInScaler)
	} else {
		return countDemands == len(demandsInJob)
	}
}
`

**Comment by EugeneLugovtsov** [comment]
@Eldarrin thanks for your help. I updated PR

**Comment by EugeneLugovtsov** [comment]
@Eldarrin could you please help with it?
image

**Comment by Eldarrin** [comment]
> @Eldarrin could you please help with it? image

HI @EugeneLugovtsov I can't see anything wrong with it, @JorTurFer is there some sort of idiomatic thing I'm missing or is it possible to //nolint this?

**Comment by zroubalik** [comment]
> > @Eldarrin could you please help with it? image
> 
> HI @EugeneLugovtsov I can't see anything wrong with it, @JorTurFer is there some sort of idiomatic thing I'm missing or is it possible to //nolint this?

What is potentially suspicious, that we are comparing the same property `countDemands` against 2 values and we have `AND` there. If this is really what we want to have, then we should add exception to https://github.com/kedacore/keda/blob/main/.golangci.yml

**Comment by EugeneLugovtsov** [comment]
@zroubalik yep, we want to be sure, that `countDemands`, `len(demandsInJob)`, and `len(demandsInScaler)` are the same.

**Comment by Eldarrin** [comment]
> /run-e2e azure* **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/4543896660)

@zroubalik can you do the e2e with pipelines, not the whole of azure? looks like those are failing.

Cheers :)

**Comment by EugeneLugovtsov** [comment]
@JorTurFer @Eldarrin do I need to do something? do I need to add this [commit](https://github.com/kedacore/keda/commit/f5995bafa6095e3dbf5aa6db98d4657ad14752cb) ?

**Comment by Eldarrin** [comment]
> @JorTurFer @Eldarrin do I need to do something? do I need to add this [commit](https://github.com/kedacore/keda/commit/f5995bafa6095e3dbf5aa6db98d4657ad14752cb) ?

Think you just need to complete the task list by checking the boxes at the top.

**Comment by EugeneLugovtsov** [comment]
@JorTurFer @Eldarrin could you help with the next steps? what do we need to do?

**Review by Eldarrin — APPROVED** [review]
Approved from my end, all looks good

**Review by JorTurFer — APPROVED** [review]
LGTM! Thanks for the fix! ❤️

**Comment by JorTurFer** [comment]
The e2e tests are failing due to expired PAT, I'll fix it asap

**Pull request merged**
