### PR TITLE
[v2] go 1.15.1 & bump deps

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

- go 1.15.1 was released (CGI related security fixes) https://golang.org/doc/devel/release.html#go1.15
- updating deps

### CODE REVIEW

**Comment by kashifsoofi** [comment]
Missing go version update in `.devcontainer` dockerfile?

**Comment by zroubalik** [comment]
> Missing go version update in `.devcontainer` dockerfile?

@kashifsoofi Good catch, looking at the file, it deserves a proper update, not just Go version. Better to cover this in a separate PR. Are you willing to pick it up?

**Comment by zroubalik** [comment]
Created a separate issue for `.devcontainer` https://github.com/kedacore/keda/issues/1114

**Comment by kashifsoofi** [comment]
> 
> 
> > Missing go version update in `.devcontainer` dockerfile?
> 
> @kashifsoofi Good catch, looking at the file, it deserves a proper update, not just Go version. Better to cover this in a separate PR. Are you willing to pick it up?

Yep why not would be some good practice :)

**Review by ahmelsayed — APPROVED** [review]

**Pull request merged**
