### PR TITLE
enable gofmt,golint and fix lint errors

### PR DESCRIPTION
**Pull request by silenceper**
Signed-off-by: silenceper <silenceper@gmail.com>

enable gofmt,golint for golangci, and fix lint errors. 

gofmt  file `pkg/scalers/azure/azure_monitor_test.go`
```
gofmt -w -s pkg/scalers/azure/azure_monitor_test.go 
```
### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Fixes #

### CODE REVIEW

**Comment by zroubalik** [comment]
How does this works with this:

https://github.com/kedacore/keda/blob/v2/Makefile#L199-L215

**Comment by silenceper** [comment]
@zroubalik 
- `make revive` can change to `make golangci`
- To be consistent, use `gofmt` instead of  `go fmt` , because gofmt tool is used in golangci.

**Comment by zroubalik** [comment]
@silenceper ok, would you mind changing the Makefile accordingly, please?

**Comment by silenceper** [comment]
@zroubalik
 
PTAL

**Review by ahmelsayed — APPROVED** [review]
I'm not I understand why the previous one was missing those files. from the help, it seems that `go fmt` runs `gofmt -l -w`. Maybe it's the `-s` for simplify code? Anyway, this looks good to me. Thanks @silenceper again.

**Comment by silenceper** [comment]
Yes, I add -s for gofmt.

**Review by zroubalik — APPROVED** [review]
LGTM

**Pull request merged**
