### PR TITLE
add scaledobject.spec.triggers.passowrd, fix bug #3600

### PR DESCRIPTION
**Pull request by spwangxp**
Signed-off-by: XP <24298044+spwangxp@users.noreply.github.com>

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #

Relates to #

### CODE REVIEW

**Review by tomkerkhove — CHANGES_REQUESTED** [review]
I don't think we should do this as this would mean there are hardcoded passwords, we should use trigger authentication instead (which should already be supported I think)

**Comment by spwangxp** [comment]
`trigger  authentication` and `passwordFromEnv` both support, but set the var `password` for which scene？the [doc](https://github.com/kedacore/keda-docs/blame/main/content/docs/2.9/scalers/postgresql.md#L81) also confused me.

**Comment by tomkerkhove** [comment]
The docs that you are referring to is purely for TriggerAuthentication and not for trigger metadata.

**Comment by JorTurFer** [comment]
Agreed with @tomkerkhove , TriggerAuthentication is the way, you can specify the environment variables as source if you want. Getting them from environment directly is good enough from security POV, but having passwords hard-coded in clear text shouldn't be an option IMO

**Pull request closed without merging**
