### PR TITLE
Move release process to Markdown in repo

### PR DESCRIPTION
**Pull request by tomkerkhove**
Move release process to Markdown in repo to use PRs as review process.

Last piece before we can remove the wiki (#460)

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Adding @anirudhgarg since he was working on it

**Comment by anirudhgarg** [comment]
@tomkerkhove where would be a good place to move it ?

**Comment by tomkerkhove** [comment]
It's already done here in the PR, but it's just a suggestion!

**Comment by anirudhgarg** [comment]
Yes looks good to me.

**Pull request merged**
