### PR TITLE
enable ARM deployment

### LINKED ISSUE #160: Release ARM container image to support Edge deployments
KEDA can run on edge ARM devices.
All we need to do is publish an armv7 container image.

The image can then be set via Helm.

### PR DESCRIPTION
**Pull request by yaron2**
Closes #160

### CODE REVIEW

**Comment by yaron2** [comment]
We now have an ARM image under ```kedacore/keda:arm```

**Comment by yaron2** [comment]
@asavaritayal @jeffhollan

**Comment by yaron2** [comment]
@ahmelsayed

**Comment by krvarma** [comment]
Sorry, for reopening the closed issue.

Does KEDA support ARM now, kedacore/keda:arm is not working. 

I am trying to install KEDA on K3S running on RPi 4, it seems the latest version does not support ARM, could someone clarify?

**Comment by tomkerkhove** [comment]
Can you open a dedicated issue for this please?

**Comment by krvarma** [comment]
> Can you open a dedicated issue for this please?

Sure

**Pull request merged**
