### PR TITLE
reduce gRPC connection create

### PR DESCRIPTION
**Pull request by champly**
Signed-off-by: champly <champly@outlook.com>

- Reduce gRPC connections and `scalerAddress` multiplexing connections with the same address.
- Fix `WaitGroup is reused before previous Wait has returned` panic error.

Fix: #3193 

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

### CODE REVIEW

**Comment by JorTurFer** [comment]
hey @champly 
Thanks for the improvement!
e2e tests fail after this change, could you take a look? 🙏

**Comment by champly** [comment]
> hey @champly Thanks for the improvement! e2e tests fail after this change, could you take a look? 🙏

already to fix, PTAL.

**Review by JorTurFer — COMMENTED** [review]
Looking good ❤️ 
Only small nit related with changelog

**Review by JorTurFer — APPROVED** [review]

**Pull request merged**
