### PR TITLE
Redis host port params

### LINKED ISSUE #694: Allow providing separate host/port parameters for Redis scaler
### Use-Case

The config for the Redis Lists scaler requires the following format for the host/port:
```
address: REDIS_HOST # Required host:port format
```

In our deployments we have separate env vars for hosts and ports, so would like to have an alternative to provide this information in separate parameters, similarly to how it is allowed for PostgreSQL and MySQL scalers.

### Specification

- [ ] Keep `address` param working as is
- [ ] Add `host` and `port` parameters (look at implementation of MySQL/PostgreSQL as example)
- [ ] Add config check and log an error if both `address` and `host/port` provided

### PR DESCRIPTION
**Pull request by inuyasha82**
This should implement #694 

How does it works:

now the redis scaler accept 2 new parameters: host and port in addition of the already existing. 

If address is specified it use the address, otherwise it checks the host and port parameters, they must be difned both, otherwise an error will be returned. 

If address and host and port are all specified, address will get priority. 

I'll update the documentaton and create a PR soon.

### Checklist

- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [x] Tests have been added

Fixes #694

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks! Let me know when the PR is up for the docs.

Can you add some tests as well please?

**Comment by inuyasha82** [comment]
Pr for documentation created https://github.com/kedacore/keda-docs/pull/125

**Comment by inuyasha82** [comment]
Tests added!

**Comment by inuyasha82** [comment]
@zroubalik test added.

**Comment by zroubalik** [comment]
@inuyasha82 thanks, looking good! One thing left, could you please sing your commit? See the **DCO** check failed. https://github.com/kedacore/keda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work

**Comment by inuyasha82** [comment]
@zroubalik  i tried to solve signoff the changes, but when i run the signoff command i'm getting a conflict errorr with the following error:


```
CONFLICT (content): Merge conflict in pkg/scalers/redis_scaler_test.go
error: Failed to merge in the changes.
Patch failed at 0009 Add test to scaler
hint: Use 'git am --show-current-patch' to see the failed patch
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```


Of course i tried to fix the conflict following the instrructions, but everytime i try to continue the rebase it still complain about adding the file (step that i have done):

```
You must edit all merge conflicts and then
mark them as resolved using git add
```

I trried with and without committing the merge (that according to the instructions commit is not necessary. 

Plus if i do git status: 

```
You are currently rebasing branch 'redis-host-port-params' on 'b919a4d'.
  (all conflicts fixed: run "git rebase --continue")

```

but then git rebase --continue still complains...
Can you help me please?

**Comment by zroubalik** [comment]
sometimes it could be tricky, especially if you are performing merge during your work and not rebase.

I'd recommend you to checkout your branch again, squash all your commits into one and sing this commit, squashing: https://www.internalpointers.com/post/squash-commits-into-one-git

If you have further problems, you can ask me on #keda slack.

**Comment by inuyasha82** [comment]
Ok probably better just to creaet a new branchand make a single commit and create a new PR, i see that this one has been completely messed up :)

**Pull request closed without merging**
