### PR TITLE
Refactor AWS DynamoDB Streams scaler configuration

### PR DESCRIPTION
**Pull request by omerap12**
Refactor DynamoDB Streams scaler configuration 

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to #5797

### CODE REVIEW

**Comment by omerap12** [comment]
> /run-e2e aws_dynamodb **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/11937080962)

Friendly ping :)

**Review by wozniakjan — APPROVED** [review]
lgtm, thank you!

**Review by JorTurFer — APPROVED** [review]

**Pull request merged**
