### PR TITLE
fix: Refactor adapter startup to ensure proper log initilization

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes https://github.com/kedacore/keda/issues/2316

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
Looking good. Feel free to merge this once you are able to confirm this in the next couple days.

**Comment by JorTurFer** [comment]
> Looking good. Feel free to merge this once you are able to confirm this in the next couple days.

I'll keep it there for 2-3 days and if I don't see any trace, I'll merge it, but even do that, I can't guarantee that it's the fix and not just luck

**Pull request merged**
