### PR TITLE
Use ghcr images instead of dockerhub images for e2e tests

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Related https://github.com/kedacore/governance/issues/16

### CODE REVIEW

**Comment by JorTurFer** [comment]
The e2e tests has failed because mysql image doesn't contain the tag `824031e` in ghcr. I have removed all pinned version related with that commit

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
