### PR TITLE
chore: add manifest verification and use server-side for CRDs

### PR DESCRIPTION
**Pull request by JorTurFer**
This PR adds a manifest up-to-date verification and also deploys the CRDs using `server-side` as part of e2e deployment

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Would be nice if we can sometimes skip this check. Some diffs are only caused by different versions and nothing relevant is changed

**Comment by JorTurFer** [comment]
> Would be nice if we can sometimes skip this check. Some diffs are only caused by different versions and nothing relevant is changed

I don't think that's easily done tbh. In any case, the fix is just executing a command. Also, manifests aren't like generated code where versions can change, I mean, if the CRD changes, changes. It's because we have bumped any dep or any field, and it has changed for the future too

**Comment by JorTurFer** [comment]
when do you see a problem with executing the diff always? We have been doing it with `clientset-verify` for years xD

**Comment by zroubalik** [comment]
> when do you see a problem with executing the diff always? We have been doing it with `clientset-verify` for years xD

Yeah :D but that's a different thing. The clientset isn't changed that much, but for crd resources there are often just bumps in the kubecontroller version. This might confuse contributors.

Eg:
https://github.com/kedacore/keda/blob/1e4a8609bcc73fd596a9d873adb8e3599e20167c/config/crd/bases/keda.sh_clustertriggerauthentications.yaml#L6

**Comment by JorTurFer** [comment]
And I don't think that it's confusing, basically the CI will fail, showing a message with a clear instruction:
`Please run 'make manifests`

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
