### PR TITLE
feat: Support for Kubernetes v1.30 in KEDA v2.14

### PR DESCRIPTION
**Pull request by tomkerkhove**
Support for Kubernetes v1.30 in KEDA v2.14

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to https://github.com/kedacore/keda/issues/5828

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
k8s 1.30 isn't still available on Azure, I'd wait until it's available to test that KEDA works well

**Comment by tomkerkhove** [comment]
Totally agree!

**Comment by pavlospt** [comment]
> k8s 1.30 isn't still available on Azure, I'd wait until it's available to test that KEDA works well

Is that a reasonable action path though? Kubernetes 1.30 is available in other Cloud providers 🤔

**Comment by tomkerkhove** [comment]
Well we don't have test clusters there so 🤷‍♂️

**Comment by pavlospt** [comment]
> Well we don't have test clusters there so 🤷‍♂️

KEDA is a CNCF Graduated project. I am sure there should be something like open source credits for the other cloud providers too. Why not apply for such programs in order to have a better test bed?

**Comment by tomkerkhove** [comment]
We do have these, but maintaining e2e tests across 3 clusters in 3 cloud providers is not something we have today. Additionally, these credits are not infinite.

We are open to feedback, but do rely on the community so if this is something you want to contribute than I am sure @kedacore/keda-maintainers are open to review suggestions.

**Comment by pavlospt** [comment]
> We do have these, but maintaining e2e tests across 3 clusters in 3 cloud providers is not something we have today. Additionally, these credits are not infinite.
> 
> We are open to feedback, but do rely on the community so if this is something you want to contribute than I am sure @kedacore/keda-maintainers are open to review suggestions.

So you would need help in the infrastructure side of this? Open to help in any way I can!

**Comment by tomkerkhove** [comment]
Please open a seperate issue for this, but first @kedacore/keda-maintainers need to decide if we want to go there and if it's worth the overhead. We have very little integration with cloud providers, actually almost none for clusters so it needs to be worth it.

The changes would involve:
- Infra structure
- Testing integration & workflows
- Increased PR duration
- ...

One does not simply do this =)

**Comment by pavlospt** [comment]
> Please open a seperate issue for this, but first @kedacore/keda-maintainers need to decide if we want to go there and if it's worth the overhead. We have very little integration with cloud providers, actually almost none for clusters so it needs to be worth it.
> 
> The changes would involve:
> 
> * Infra structure
> * Testing integration & workflows
> * Increased PR duration
> * ...
> 
> One does not simply do this =)

Ok but if it's not a matter of effort then but a matter of opinion, this would lock KEDA compatibility to the Kubernetes version availability on AKS, which to me also sounds a bit restricting in comparison to increased PR duration, but wider cloud provider check!

**Comment by tomkerkhove** [comment]
> Please open a seperate issue for this

☝️

**Comment by JorTurFer** [comment]
> this would lock KEDA compatibility to the Kubernetes version availability on AKS

I don't think so tbh. KEDA works on multiple k8s versions, the only point is that we don't say that it's officially supported  until we have test coverage with a real k8s cluster. You can use it with k8s 1.30 as you can use it with k8s 1.26.

We are willing to change and use other providers (or include them), but it requires an effort and also to maintain them. Azure gave us a great budget and other providers gave us a limited budget that we need to organice as better as we can to not waste it because we need it for testing the services themselves.

As @tomkerkhove  has said, please open an issue to talk about this, if you have a proposal that covers these things, we can do it 😄

**Review by Ahmadkashif — APPROVED** [review]

**Comment by JorTurFer** [comment]
I think that this isn't needed anymore @tomkerkhove , we shipped v2.14.1 last week (reopen it if you think it's still necessary)

**Pull request closed without merging**
