### PR TITLE
[v2] add support for multiple redis list types in redis list scaler 

### PR DESCRIPTION
**Pull request by ilyamor**
added support for multiple redis "list" types scaling, including : zset,hash,set and list

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Tests have been added
- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [x] Changelog has been updated

Fixes #

### CODE REVIEW

**Comment by ilyamor** [comment]
original discussion
https://github.com/kedacore/keda/pull/1013

**Review by zroubalik — APPROVED** [review]
I am not redi-list expert, but LGTM

**Comment by ilyamor** [comment]
how is the merge process works?when is v2 suppose to be out?

**Comment by zroubalik** [comment]
Could you plese fix hour PR on the docs? I think that we can merge this one then.

@ilyamor v2 should be out in the next couple of weeks. Feel free to join community meetup later today, to get more details.

**Pull request merged**
