### PR TITLE
refactor aws_kinesis_stream_scaler

### LINKED ISSUE #5797: Refactor Scalers with new declarative scaler config
### Proposal

We can take turn implement the changes in this PR https://github.com/kedacore/keda/pull/5676. This is related to the original issue here https://github.com/kedacore/keda/issues/5037. I can take the kafka one since I have been working on something similar in https://github.com/kedacore/keda/pull/5319

- [x] activemq_scaler.go https://github.com/kedacore/keda/pull/5799
- [x] apache_kafka_scaler.go https://github.com/kedacore/keda/pull/5804
- [x] arangodb_scaler.go https://github.com/kedacore/keda/pull/5808
- [x] artemis_scaler.go https://github.com/kedacore/keda/pull/5836
- [x] aws_cloudwatch_scaler.go https://github.com/kedacore/keda/pull/5852
- [x] aws_dynamodb_scaler.go https://github.com/kedacore/keda/pull/5961
- [ ] aws_dynamodb_streams_scaler.go
- [ ] aws_kinesis_stream_scaler.go
- [ ] aws_sqs_queue_scaler.go
- [ ] azure_app_insights_scaler.go
- [ ] azure_blob_scaler.go
- [ ] azure_data_explorer_scaler.go
- [ ] azure_eventhub_scaler.go
- [ ] azure_log_analytics_scaler.go
- [ ] azure_monitor_scaler.go
- [ ] azure_pipelines_scaler.go
- [ ] azure_queue_scaler.go
- [ ] azure_servicebus_scaler.go
- [ ] cassandra_scaler.go
- [ ] couchdb_scaler.go
- [ ] cpu_memory_scaler.go
- [ ] cron_scaler.go
- [ ] datadog_scaler.go
- [ ] elasticsearch_scaler.go
- [ ] etcd_scaler.go
- [ ] external_mock_scaler.go
- [ ] external_scaler.go
- [ ] gcp_cloud_tasks_scaler.go
- [ ] gcp_pubsub_scaler.go
- [ ] gcp_stackdriver_scaler.go
- [ ] gcp_storage_scaler.go
- [ ] github_runner_scaler.go
- [ ] graphite_scaler.go
- [ ] huawei_cloudeye_scaler.go
- [x] ibmmq_scaler.go https://github.com/kedacore/keda/pull/6034
- [ ] influxdb_scaler.go
- [ ] kafka_scaler.go
- [ ] kubernetes_workload_scaler.go
- [ ] liiklus_scaler.go
- [ ] loki_scaler.go
- [ ] metrics_api_scaler.go
- [ ] mongo_scaler.go
- [ ] mssql_scaler.go
- [ ] mysql_scaler.go
- [ ] nats_jetstream_scaler.go
- [ ] newrelic_scaler.go
- [ ] openstack_metrics_scaler.go
- [ ] openstack_swift_scaler.go
- [ ] postgresql_scaler.go
- [x] predictkube_scaler.go https://github.com/kedacore/keda/pull/6282
- [ ] prometheus_scaler.go
- [ ] pulsar_scaler.go
- [ ] rabbitmq_scaler.go
- [ ] redis_scaler.go
- [ ] redis_streams_scaler.go
- [ ] selenium_grid_scaler.go
- [ ] solace_scaler.go
- [x] solr_scaler.go https://github.com/kedacore/keda/pull/5818
- [ ] stan_scaler.go

### Use-Case

_No response_

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by omerap12**
Refactor aws kinesis stream scaler configuration
### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #5797 

Relates to #

### CODE REVIEW

**Review by wozniakjan — APPROVED** [review]
lgtm, thank you!

**Comment by omerap12** [comment]
@wozniakjan Can you please re-approve? I had to rebase :)

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
