### PR TITLE
Automatically determine the RabbitMQ protocol when possible

### PR DESCRIPTION
**Pull request by coderanger**
And support setting the protocol via TriggerAuthentication since if overriding host, you will probably want that too at some point (if the new auto-detection doesn't handle it for you).

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Tests have been added
- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [x] Changelog has been updated

### CODE REVIEW

**Comment by coderanger** [comment]
Honestly I'm not 100% sure there's a reason to leave `protocol` as a configurable thing rather than making it always automatic. The URLs that are accepted by either `httpclient.Get()` or `amql.Dial()` are limited to these specific schemes I think? There might be some cases for taking an HTTP URL and forcing it to an AMQP connection, but that's all I can think of and not even 100% sure Dial will accept that.

**Review by tomkerkhove — APPROVED** [review]
LGTM but will leave it up to @zroubalik to do a final sweep

**Review by zroubalik — COMMENTED** [review]
Looking good.

> Honestly I'm not 100% sure there's a reason to leave protocol as a configurable thing rather than making it always automatic. 

So what if we make the `auto` protocol a default value and thus protocol an optional parameter? By no means I am an not a RabbitMQ expert, but from what you are saying, it shouldn't do any harm and if anyone wants to specify the protocol, there's still a way.

**Comment by coderanger** [comment]
I did change the default to auto so that is exactly the case now.

**Comment by zroubalik** [comment]
Could please rebase this PR?

**Review by ahmelsayed — APPROVED** [review]

**Pull request merged**
