### PR TITLE
Provide Notes.txt for Helm chart

### LINKED ISSUE #102: Add information to NOTES.txt in helm chart
Add installation notes, next steps, methods to see output, etc to NOTES.txt - some general information that would be useful to someone who has just installed the chart.

Most likely: note about config-ing scaledobjects, note about seeing which External Metrics are in use via apis/external.metrics... link, how to see current hpas, etc

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide Notes.txt for Helm chart that helps new folks get started.

Info on the dashboard is not included yet as we don't have it, but we can use the [Prometheus approach](https://github.com/helm/charts/blob/master/stable/prometheus/templates/NOTES.txt#L4).

Will create a separate issue to track this when merged.

Closes #102, #202

<details>
<summary>Example Helm output</summary>

```shell
⚡ tkerkhove@CLT-TKERKHOVE  C:\Code\GitHub\keda\chart   features/helm-chart ≣ +1 ~0 -0 ! 
❯ helm install .\keda\  --devel --set logLevel=debug --namespace keda --name keda                           
NAME:   keda                                                                                                
LAST DEPLOYED: Fri Aug  2 09:25:42 2019                                                                     
NAMESPACE: keda                                                                                             
STATUS: DEPLOYED                                                                                            
                                                                                                            
RESOURCES:                                                                                                  
==> v1/ClusterRoleBinding                                                                                   
NAME                           AGE                                                                          
hpa-controller-custom-metrics  1s                                                                           
keda                           1s                                                                           
                                                                                                            
==> v1/Deployment                                                                                           
NAME  READY  UP-TO-DATE  AVAILABLE  AGE                                                                     
keda  0/1    1           0          1s                                                                      
                                                                                                            
==> v1/Pod(related)                                                                                         
NAME                   READY  STATUS             RESTARTS  AGE                                              
keda-849cb767cb-xg4dg  0/1    ContainerCreating  0         1s                                               
                                                                                                            
==> v1/Service                                                                                              
NAME  TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)         AGE                                           
keda  ClusterIP  10.106.114.134  <none>       443/TCP,80/TCP  1s                                            
                                                                                                            
==> v1/ServiceAccount                                                                                       
NAME                 SECRETS  AGE                                                                           
keda-serviceaccount  1        1s                                                                            
                                                                                                            
==> v1beta1/APIService                                                                                      
NAME                             AGE                                                                        
v1beta1.external.metrics.k8s.io  1s                                                                         
                                                                                                            
                                                                                                            
NOTES:                                                                                                      
Get started by deploying Scaled Objects to your cluster:                                                    
    - Information about Scaled Objects : https://github.com/kedacore/keda/blob/master/spec/ScaledObject.md  
    - Samples: https://github.com/kedacore/keda/wiki/Samples-and-Blog-posts                                 
                                                                                                            
Get information about the deployed ScaledObjects:                                                           
  kubectl get ScaledObjects [--namespace <namespace>]                                                       
                                                                                                            
Get details about a deployed ScaledObject:                                                                  
  kubectl describe scaledobject <scaled-object-name> [--namespace <namespace>]                              
                                                                                                            
Get an overview of the Horizontal Pod Autoscalers (HPA) that KEDA is using behind the scenes:               
  kubectl get hpa [--all-namespaces] [--namespace <namespace>]                                              
                                                                                                            
For more information on running KEDA, visit:                                                                
https://github.com/kedacore/keda/                                                                           
```
</details>

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@lee0c 	@jeffhollan 	might be interested in having a look as well

**Comment by jeffhollan** [comment]
This is a great start. I like this. Thanks tom

**Comment by tomkerkhove** [comment]
Any feedback on this @ahmelsayed 	@Aarthisk 	@yaron2 	?

**Comment by ahmelsayed** [comment]
@tomkerkhove can you update the branch? It might be easier to just take your changes on top of master again.

**Comment by tomkerkhove** [comment]
Sure, #329 is a clean approach - Sorry for that @ahmelsayed 	!

**Pull request closed without merging**
