### PR TITLE
Add redis ssl

### PR DESCRIPTION
**Pull request by inuyasha82**
Hi guys, 

i'm working on adding the SSL connection for redis (see issue #240).
So far i managed to get the redis-scaler to connect to a redis server using ssl. 

But i need some help to finish this work. 
What is happening at the moment is that the scaler is correctly checking the queue, getting the length, scaling down to 0, and eventually create a pod when. the watched list is being populated, the problem is that no matter how many items are in the queue, it always create only one pod (so it's not scaling up)

The interesting thing is that apparently it is happening only with the ssl queue. When using my code on a redis server without ssl enabled, it is correctly scaling up and down. 

What could be the reason? 

Do i need to change the code somewhere else?

As you can see in this pull request i'm printing out some debug InformatIon, i checked that the list length reported is correct.

### CODE REVIEW

**Comment by inuyasha82** [comment]
So found the reason of why it was not scaling to more than one, is explained on issue #240, shortly i was deploying only the custom keda image, and not the custom metricserver, once deployed both custom keda and metricserver it is correctly scaling up and down.

**Comment by marchmallow** [comment]
@ahmelsayed does this look good to go in or want us to make further changes? We depend upon using TLS to deploy keda in our production environment

**Comment by ahmelsayed** [comment]
Sorry for the delay in getting back, sorry for not helping with the issue you're seeing, but looks like you're able to figure out :) 

The change looks good to me. I'll merge it in a minute.

**Comment by tomkerkhove** [comment]
@inuyasha82 Would you mind sending a PR to update the docs for this please?

https://github.com/kedacore/keda-docs

**Comment by inuyasha82** [comment]
@tomkerkhove sure, i'll do it today!

**Comment by tomkerkhove** [comment]
Awesome, thanks!

**Comment by inuyasha82** [comment]
@tomkerkhove created: https://github.com/kedacore/keda-docs/pull/73

**Pull request merged**
