### PR TITLE
For the getScaler method wished to pass the entire scaler object since some parameters are required for new scalers. Currently, only scaledObject name and namespace is passed.

### PR DESCRIPTION
**Pull request by ckuduvalli**
_Provide a description of what has been changed_

### Checklist

- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Tests have been added

Fixes #

### CODE REVIEW

**Comment by zroubalik** [comment]
@ckuduvalli is there any specific need for this? I don't see the point.

**Comment by ckuduvalli** [comment]
@zroubalik I am writing a new scaler for which I need deployment name, namespace to be passed in to the scaler. Instead of again defining it in the metadata, I wanted to use them. Hence I made this change.

**Comment by zroubalik** [comment]
OK, what kind of scaler it is? I think that it is better to include this change into the PR with your scaler, to keep things consistent.

**Comment by ckuduvalli** [comment]
Its a cron scaler. To scale up and scale down the pods at a scheduled time. Do you think its a good use case to check in the cron scaler so that people can use it?

**Comment by zroubalik** [comment]
@ckuduvalli interesting. Could you please open an issue first? Describe the scaler you are proposing and open the PR then, thanks! I'll close this one for now.

**Comment by ckuduvalli** [comment]
@zroubalik Have opened an issue: https://github.com/kedacore/keda/issues/812

**Pull request closed without merging**
