### PR TITLE
fix: stop scale loop for pause Scaledbject

### LINKED ISSUE #4253: The paused-replicas annotation not fully respected
### Report

Althogh the **scaledobject** annotation **autoscaling.keda.sh/paused-replicas** does pause the autoscaling as expected, keda will still log error messages originating from triggers for such paused scaledobjects. This is a problem if you are managing multiple environments that are being fully scaled down (to 0), including the data sources for the scaled object triggers - in our case mysql database is also scaled down so the database connection failure is all the time logged.

### Expected Behavior

No error messages will be created whatsoever for scaledobjects that are paused.

### Actual Behavior

many errors are logged in loop - see logs from keda operator

### Steps to Reproduce the Problem

1. to pause, type
```bash
kubectl annotate scaledobject session-scaler autoscaling.keda.sh/paused-replicas="0"
```
2. to checkout the operator logs:

k logs -l app=keda-operator -f

4.

### Logs from KEDA operator

```
2023-02-20T14:36:52Z	ERROR	mysql_scaler	Found error when pinging database: dial tcp 100.64.186.148:3306: connect: connection refused	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "error": "dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scalers.NewMySQLScaler
	/workspace/pkg/scalers/mysql_scaler.go:53
github.com/kedacore/keda/v2/pkg/scaling.buildScaler
	/workspace/pkg/scaling/scale_handler.go:431
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers.func1
	/workspace/pkg/scaling/scale_handler.go:325
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scale_handler.go:328
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	scalehandler	error resolving auth params	{"scalerIndex": 0, "object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler"}, "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Error getting scalers	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Failed to create new HPA resource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "HPA.Namespace": "invu-sre", "HPA.Name": "keda-hpa-keda-session-scaler", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Failed to check HPA for possible update	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Failed to ensure HPA is correctly created for ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "KEDAScalerFailed", "message": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
2023-02-20T14:36:52Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "ScaledObjectCheckFailed", "message": "Failed to ensure HPA is correctly created for ScaledObject"}
2023-02-20T14:36:52Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3"}
2023-02-20T14:36:55Z	DEBUG	Parsed Group, Version, Kind, Resource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "GVK": "apps/v1.Deployment", "Resource": "deployments"}
2023-02-20T14:36:55Z	DEBUG	scalehandler	cannot resolve env to a value. fieldRef and resourceFieldRef env are skipped	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "env-var-name": "INSTANCE"}
2023-02-20T14:36:55Z	DEBUG	scalehandler	cannot resolve env to a value. fieldRef and resourceFieldRef env are skipped	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "env-var-name": "MY_POD_NAMESPACE"}
2023-02-20T14:36:55Z	ERROR	mysql_scaler	Found error when pinging database: dial tcp 100.64.186.148:3306: connect: connection refused	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "error": "dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scalers.NewMySQLScaler
	/workspace/pkg/scalers/mysql_scaler.go:53
github.com/kedacore/keda/v2/pkg/scaling.buildScaler
	/workspace/pkg/scaling/scale_handler.go:431
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers.func1
	/workspace/pkg/scaling/scale_handler.go:325
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scale_handler.go:328
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	scalehandler	error resolving auth params	{"scalerIndex": 0, "object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler"}, "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Error getting scalers	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Failed to create new HPA resource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "HPA.Namespace": "invu-sre", "HPA.Name": "keda-hpa-keda-session-scaler", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Failed to check HPA for possible update	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Failed to ensure HPA is correctly created for ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "KEDAScalerFailed", "message": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
2023-02-20T14:36:55Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "ScaledObjectCheckFailed", "message": "Failed to ensure HPA is correctly created for ScaledObject"}
2023-02-20T14:36:55Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234

```

### KEDA Version

2.8.1

### Kubernetes Version

1.25

### Platform

Amazon Web Services

### Scaler Details

mysql

### Anything else?

willing to help fix this

### PR DESCRIPTION
**Pull request by tobotg**
In the controller in the reconcile loop, when a scaledObject is paused (annotated with ), this fix stops the scaling logic (to prevent attempt to connect the to scalers), and deletes the generated HPA (so it is not querying KEDA Metric Server for metrics)

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4253

### CODE REVIEW

**Comment by JorTurFer** [comment]
The new test [is failing](https://github.com/kedacore/keda/actions/runs/4788469328/jobs/8517229422?pr=4470#step:12:58), could you take a look?

**Comment by tobotg** [comment]
@JorTurFer sure thing. I'll take a look.

**Review by tomkerkhove — APPROVED** [review]

**Comment by tobotg** [comment]
@JorTurFer is there anything expected from me wrt the FOSS / build failures? Just checking.

**Comment by zroubalik** [comment]
> @JorTurFer is there anything expected from me wrt the FOSS / build failures? Just checking.

no, ignore this for now

**Comment by zroubalik** [comment]
@tobotg seems like the e2e test is [failing](https://github.com/kedacore/keda/actions/runs/4819967110/jobs/8584143929), could you please double check?

https://github.com/kedacore/keda/blob/main/tests/internals/pause_scaling/pause_scaling_test.go

**Comment by tobotg** [comment]
@zroubalik I tried to have a look, but can't find the detail of the test run that failed. Would you be able to help? Thanks

**Comment by JorTurFer** [comment]
You can see the execution log, clicking the link in the comment:
image
but in this case, the error is here: https://github.com/kedacore/keda/actions/runs/4819967110/jobs/8584143929#step:8:378
The scaling out test is failing

**Comment by tobotg** [comment]
@JorTurFer @zroubalik Thank you.
I looked and tested, and found that the tests fail consistently with a wait time of 1 min for `WaitForDeploymentReplicaReadyCount`, but succeed when I increase that wait time to 2 or 3 min. The behaviour seems fragile when the load (all the e2e tests launched) increases. 
Would you agree to increase the wait time periods in the `pause_scaling_test.go` to fix this test?

**Comment by JorTurFer** [comment]
Could you rebase main too? There are changes required for executing e2e tests

**Comment by tobotg** [comment]
@JorTurFer it should be fine now I guess. But this [test](https://github.com/kedacore/keda/actions/runs/4865041679/jobs/8674837263?pr=4470#step:12:823) is failing now. Do you mind triggering the e2e to check what when wrong? Thanks

**Review by zroubalik — COMMENTED** [review]
@tobotg could you please make sure that the PR contain only your commits?

**Comment by tobotg** [comment]
I ended up closing this and resubmitting a new PR.

**Pull request closed without merging**
