### PR TITLE
docs: Provide guidance on how to contribute an authentication source

### LINKED ISSUE #2313: Provide guidance on how to contribute an authentication source
Provide guidance on how to contribute an authentication source as part of our contribution guide so that the community knows what to do.

Relates to #900

### PR DESCRIPTION
**Pull request by abhinav2712**
Updated contributing file by adding steps to contribute to an authentic source with the perspective of a beginner which would be very useful if someone is doing their contribution for the first time.

## Changes 
In the CONTRIBUTING.md file, a section called "how to contribute?" has been added which has the steps to guide any contributor to contribute in this project

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
(https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
(https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #2313

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Hi, thanks for the PR but I don't see much content about contributing an authentication source - Can you elaborate a bit more on this please?

For the rest I think this is very useful, but we might want to simplify it and use links to GitHub their docs to avoid being out of date.

**Comment by abhinav2712** [comment]
@tomkerkhove Hi, I actually found these steps to be missing from the docs hence I added them,  I would need a bit more on what exactly you mean particularly by 'authentication sources'?
My PR is related to what a normal contributions  steps are like, hence I need more clarification, thank you

**Review by zroubalik — COMMENTED** [review]
@abhinav2712 your contribution is great, though it is not much about authentication sources. Could you please change your contribution a little bit, to make it a generic contribution guide (and not guide about adding an authentication source)?

It would be a great addition to our docs.

**Comment by abhinav2712** [comment]
> @abhinav2712 your contribution is great, though it is not much about authentication sources. Could you please change your contribution a little bit, to make it a generic contribution guide (and not guide about adding an authentication source)?
> 
> It would be a great addition to our docs.

Sure , I will see what I can do...

**Comment by zroubalik** [comment]
Stale, please reopen with the new content if you want to proceed this direction.

**Pull request closed without merging**
