### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by zroubalik**

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]

**Comment by zroubalik** [comment]
> 

@JorTurFer @Eldarrin seems like there's some problem with the GitHub scaler. It keeps failing on the `main` branch, I try it in this PR and we can see that it fails.

**Comment by Eldarrin** [comment]
spinning it up at home to check

**Comment by JorTurFer** [comment]
It was a transient error deploying KEDA, not related with GH

**Comment by zroubalik** [comment]
> It was a transient error deploying KEDA, not related with GH

hmmm, but that problem on main was there consistent. Sorry @Eldarrin for the confusion.

**Comment by Eldarrin** [comment]
No problem

**Pull request merged**
