### PR TITLE
fix: Validate empty array value of triggers in ScaledObject/ScaledJob creation

### PR DESCRIPTION
**Pull request by SpiritZhou**
Add validation in  ValidateTriggers() to prevent an empty array value of triggers so that some unexpected HPA will not be created

### Checklist

- [X] Tests have been added
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #

Relates to # https://github.com/kedacore/keda/issues/5520

### CODE REVIEW

**Comment by JorTurFer** [comment]
Can we extend this PR to cover ScaledJobs too?

**Comment by SpiritZhou** [comment]
> Can we extend this PR to cover ScaledJobs too?

Extended ScaledJob too

**Review by zroubalik — COMMENTED** [review]
Could you please also add a validation into controllers? in case webhooks are disabled. Thanks!

**Comment by SpiritZhou** [comment]
> Could you please also add a validation into controllers? in case webhooks are disabled. Thanks!

Added a validation in the controller

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!

**Comment by joebowbeer** [comment]
This is a breaking change for users such as myself who have been depending on ScaledObject to implicitly add CPU and Memory scalers to ScaledObject even when there are no other triggers.

Is there no way to disable or configure it?

**Pull request merged**
