### PR TITLE
Add KEDA svg logo with lightning

### PR DESCRIPTION
**Pull request by turbaszek**
The blur around the lighting is similar to the orginal one but not the same:
https://github.com/turbaszek/keda/blob/add-keda-logo-svg/images/keda-word-bolt-blur.svg

The .eps has some weird color - do we need this format? 

Signed-off-by: Tomek Urbaszek <tomasz.urbaszek@polidea.com>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Relates to #650

### CODE REVIEW

**Comment by zroubalik** [comment]
Looking good!

**Review by tomkerkhove — COMMENTED** [review]
LGTM but:
- We don't need the EPS so if it's not ideal for you, feel free to leave it out
- Would be nice to update `images/keda-icon.svg` as well (for example for docs)

Do you have the bandwidth to pick this up as well?

**Comment by turbaszek** [comment]
I will do this over the weekend 👌

**Comment by tomkerkhove** [comment]
That would be awesome! Thanks!

**Comment by tomkerkhove** [comment]
In terms of the EPS file, is that to generate the SVG or do you edit it directly?

Sorry, I'm a newbie on this front 😁

**Comment by turbaszek** [comment]
> Sorry, I'm a newbie on this front 😁

I'm not an expert too 😄 

> In terms of the EPS file, is that to generate the SVG or do you edit it directly?

You can edit the SVG directly, the eps is just another file format. I added it because I saw that there are always both .svg and .eps graphics. Probably I just have to figure out the color space as now it's slightly faded.

**Comment by tomkerkhove** [comment]
Oh OK, thanks! Then I think we can removed the ESP indeed.

**Comment by zroubalik** [comment]
@turbaszek do you think you could nail [this one](https://github.com/kedacore/keda/blob/master/images/keda-icon.svg) as well?

**Comment by turbaszek** [comment]
I've updated the images, please let me know if there's anything to change or we are good good to go. Once it's approved I will open PR to docs repo.
https://github.com/turbaszek/keda/blob/add-keda-logo-svg/images/keda-word-bolt.svg
https://github.com/turbaszek/keda/blob/add-keda-logo-svg/images/keda-icon-bolt.svg

**Comment by tomkerkhove** [comment]
Is there a reason why we are introducing new files instead of replacing the current ones?

**Comment by turbaszek** [comment]
> Is there a reason why we are introducing new files instead of replacing the current ones? 

The logo is part of KEDA branding and as I'm not perfectly sure what is the official logo (KEDA with or without the lightning bolt) I don't want to remove any files.

We can use this PR to sort this and I am happy to describe it somewhere so people will be able to find some info in future.

**Comment by tomkerkhove** [comment]
Don't hesitate to ask next time!

Sith lightning bolt is the official logo so feel free to replace it.

**Comment by tomkerkhove** [comment]
Will do it as part of #1090, thanks for the tip!

I recall having seen a version where the bolt is more explicit by making the bolt itself yellow. What do you think about that? 

/cc @zroubalik @jeffhollan @ahmelsayed @anirudhgarg

**Comment by turbaszek** [comment]
Screenshot 2020-09-06 at 11 58 43

**Comment by zroubalik** [comment]
I prefer the version 3, version 1 as a backup, in case there would be a problem with the blur.

**Comment by turbaszek** [comment]
> I prefer the version 3, version 1 as a backup, in case there would be a problem with the blur.

Make sense to me. I would say that version 3 is general-purpose but the 1 should be used for print and black-white version (required sometimes so I can provide one).

**Comment by tomkerkhove** [comment]
I would say #4 but don't have much of a preference.

**Comment by zroubalik** [comment]
@tomkerkhove for me, the version 4 is too much leaning towards Azure Functions logo :)

**Comment by turbaszek** [comment]
> @tomkerkhove for me, the version 4 is too much leaning towards Azure Functions logo :)

I even wanted to use Azure Function yellow color 😄

**Comment by tomkerkhove** [comment]
> @tomkerkhove for me, the version 4 is too much leaning towards Azure Functions logo :)

Heh, fair enough! For me 3 is ok as default logo with 1 for print indeed.

**Comment by zroubalik** [comment]
@turbaszek don't you want to target this to v2 branch? We can then cherry pick relevant changes to the master (soon to be v1 branch).

**Comment by turbaszek** [comment]
@zroubalik I change the target branch. I should be able to prepare all graphics in the next few days

**Comment by turbaszek** [comment]
All svg images are here: https://github.com/turbaszek/keda/tree/add-keda-logo-svg/images

Please let me know if everything is ok, then I can prepare png files if we need

**Comment by tomkerkhove** [comment]
LGTM, just a few suggestions:
- `keda-word-simple.svg` --> `keda-word-print.svg`
- `keda-icon-simple.svg` --> `keda-icon-print.svg`
- `keda-word.svg` --> `keda-word-colour.svg`
- `keda-icon.svg` --> `keda-icon-colour.svg`

Maybe it's good to move them to a `logos` folder to put some structure in that folder maybe? WDYT @zroubalik ?

**Comment by zroubalik** [comment]
Looking good, `images/logos` directory is a good idea!

**Comment by zroubalik** [comment]
Looking good, can we continue with the png images @tomkerkhove @jeffhollan ?

**Review by zroubalik — APPROVED** [review]

**Review by tomkerkhove — COMMENTED** [review]
PNGs would be great as @zroubalik suggests and have replacements for these instead of removing them:
image

**Comment by zroubalik** [comment]
> PNGs would be great as @zroubalik suggests and have replacements for these instead of removing them:
> image

Yeah, this change comes with the need of updating the Readme.md and maybe other files, that are consuming these images.

**Comment by turbaszek** [comment]
Yes, I will do the png if we are good with all logo versions. Just wanted to avoid replication of work in case of change requests

**Comment by turbaszek** [comment]
pngs added, and README looks good I think:
https://github.com/turbaszek/keda/tree/add-keda-logo-svg

**Comment by tomkerkhove** [comment]
> PNGs would be great as @zroubalik suggests and have replacements for these instead of removing them:
> image

Can you re-add these as well please @turbaszek?

**Comment by turbaszek** [comment]
> > PNGs would be great as @zroubalik suggests and have replacements for these instead of removing them:
> 
> > image
> 
> 
> 
> Can you re-add these as well please @turbaszek?

By re-adding do you mean replacing them with new once with same name or restoring the old one?

**Comment by tomkerkhove** [comment]
Replacing them with the new ones indeed!

**Comment by turbaszek** [comment]
I understand the need of having one with a white background, but why should we have two logos with transparent bg? Are those files used somewhere else outside the repo?

**Comment by tomkerkhove** [comment]
They are used by us and others indeed. Here is usage on GitHub alone - https://github.com/search?q=keda-logo-transparent.png&type=Code

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks @turbaszek!

**Review by zroubalik — APPROVED** [review]
LGTM, thanks for the this!

**Pull request merged**
