### PR TITLE
find the stream leader the old way if nodes are not advertised

### LINKED ISSUE #4524: NATS JetStream scaler broke if nodes are not advertised
### Report

@rayjanoka report the NATS JetStream scaler broke on their setup because the nodes are not advertised which result in `connect_urls` return empty https://github.com/kedacore/keda/pull/4102#issuecomment-1530613127

### Expected Behavior

NATS JetStream scaler works as before

### Actual Behavior

NATS JetStream scaler returns runtime error 

### Steps to Reproduce the Problem

1. Setup NATS cluster via load balancer and node advertise disable
2. Use NATS JetStream scaler as usual

### Logs from KEDA operator

```
result: runtime error: invalid memory address or nil pointer dereference
```

### KEDA Version

2.10.1

### Kubernetes Version

None

### Platform

None

### Scaler Details

NATS JetStream

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mfadhlika**
_Provide a description of what has been changed_

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4524

### CODE REVIEW

**Comment by JorTurFer** [comment]
Unit test are failing, could you check them? 
https://github.com/kedacore/keda/actions/runs/4878814964/jobs/8704797046#step:12:707

**Comment by rayjanoka** [comment]
thanks @mfadhlika! - I'll try to get some time to give this a test on my system.

**Comment by mfadhlika** [comment]
@JorTurFer I have updated the test

**Comment by rayjanoka** [comment]
nice1, tested good on my system. 🎉 🎉 🎉

**Review by JorTurFer — APPROVED** [review]
LGTM!
Thanks for the improvement! ❤️

**Pull request merged**
