### PR TITLE
Fix scale with windows nodes in cluster

### LINKED ISSUE #4908: The Selenium Grid Scaler incorrectly scales Linux pods when Windows nodes are present in the cluster.
### Report

When there are no Windows nodes in the cluster, the deployment of the requested browser scales to a number equal to the quantity of tests. However, as soon as Windows nodes appear, scaling occurs to a number equal to the quantity of tests minus the number of Windows nodes. This is regardless of the browser versions.

Example:
No Windows nodes in the cluster: Request 7,  7 new pod's.
Windows nodes present in the cluster (2 in total): Request 7, 5 new pod's.

### Expected Behavior

Request 7,  7 new pod's.

### Actual Behavior

Request 7, 5 new pod's.

### Steps to Reproduce the Problem

1. Deploy Selenium Grid
2. Deploy KEDA
3. Create and connect to Grid Windows node(on VM)

### Logs from KEDA operator

```
no logs about this
```

### KEDA Version

2.11.1

### Kubernetes Version

1.23

### Platform

Other

### Scaler Details

Selenium Grid Scaler

### Anything else?
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"labels":{"deploymentName":"selenium-chrome-node-v115"},"name":"selenium-grid-chrome-115-scaledobject","namespace":"selenium4"},"spec":{"advanced":{"horizontalPodAutoscalerConfig":{"behavior":{"scaleUp":{"policies":[{"periodSeconds":1,"type":"Pods","value":220}]}}}},"cooldownPeriod":30,"maxReplicaCount":220,"minReplicaCount":1,"pollingInterval":5,"scaleTargetRef":{"name":"selenium-chrome-node-v115"},"triggers":[{"metadata":{"browserName":"chrome","browserVersion":"115","platformName":"Linux","sessionBrowserName":"chrome","unsafeSsl":"false","url":"http://selenium-router.selenium4.svc:4444/graphql"},"type":"selenium-grid"}]}}
  creationTimestamp: "2023-08-14T06:11:58Z"
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    deploymentName: selenium-chrome-node-v115
    scaledobject.keda.sh/name: selenium-grid-chrome-115-scaledobject
  name: selenium-grid-chrome-115-scaledobject
  namespace: selenium4
  resourceVersion: "534407573"
  uid: fe52380c-23ab-4fd4-b564-822abf710f1b
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          policies:
          - periodSeconds: 1
            type: Pods
            value: 220
  cooldownPeriod: 30
  maxReplicaCount: 220
  minReplicaCount: 1
  pollingInterval: 5
  scaleTargetRef:
    name: selenium-chrome-node-v115
  triggers:
  - metadata:
      browserName: chrome
      browserVersion: "115"
      platformName: Linux
      sessionBrowserName: chrome
      unsafeSsl: "false"
      url: http://selenium-router.selenium4.svc:4444/graphql
    type: selenium-grid
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  - status: Unknown
    type: Paused
  externalMetricNames:
  - s0-seleniumgrid-chrome
  health:
    s0-seleniumgrid-chrome:
      numberOfFailures: 0
      status: Happy
  hpaName: keda-hpa-selenium-grid-chrome-115-scaledobject
  lastActiveTime: "2023-08-24T08:29:39Z"
  originalReplicaCount: 1
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
```

Windows node
```
08:07:08.060 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox","browserVersion": "115.0","platformName": "windows","se:noVncPort": 5901,"se:vncEnabled": true} 6 times
08:07:08.060 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","browserVersion": "115.0","platformName": "windows","se:noVncPort": 5901,"se:vncEnabled": true} 6 times
08:07:08.060 INFO [NodeOptions.report] - Adding MicrosoftEdge for {"browserName": "MicrosoftEdge","browserVersion": "115.0","platformName": "windows","se:noVncPort": 5901,"se:vncEnabled": true} 6 times
```

### PR DESCRIPTION
**Pull request by Doofus100500**
Fix scale with windows nodes in cluster

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4908

Relates to #

### CODE REVIEW

**Comment by JorTurFer** [comment]
I think that @Wolfe1 checked something similar some time ago, Am I right?

**Comment by Doofus100500** [comment]
Would be fixed in https://github.com/kedacore/keda/pull/6169

**Pull request closed without merging**
