### PR TITLE
Add additional manifest checks to detect missing CRDs & CRs

### LINKED ISSUE #5920: CRD & sample CR manifest data for downstream OLM operator incomplete
### Report

While working on the KEDA OLM operator, I noticed the following 3 issues:
* CRD `config/crd/bases/keda.sh_clustertriggerauthentications.yaml` does not have a sample CR `config/samples/keda_v1alpha1_clustertriggerauthentication.yaml`
* CR `config/samples/keda_v1alpha1_clustertriggerauthentication.yaml` is not listed in the resources section of `config/samples/kustomization.yaml`
* CR `config/samples/eventing_v1alpha1_cloudeventsource.yaml` is not listed in the resources section of `config/samples/kustomization.yaml`

Also, it would be nice if we had a check to detect these sorts of problems.

### Expected Behavior

No missing CRDs or CRs, neither the manifests nor the references to them in the `kustomization.yaml`

### Actual Behavior

As described in the above description

### Steps to Reproduce the Problem

Compare the repo `config/crds/bases/*.yaml` with `config/crds/kustomize.yaml`, `config/samples/kustomize.yaml` and `config/samples/*.yaml`

### Logs from KEDA operator

_No response_

### KEDA Version

2.14.0

### Kubernetes Version

1.29

### Platform

Red Hat OpenShift

### Scaler Details

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joelsmith**
This PR has three parts:
1. Add additional PR checks to make sure that every CRD is listed in the CRD `kustomize.yaml` file and that every CRD also has a sample CR for each of its API versions and is similarly listed in the `kustomize.yaml` file for sample CR files.
2. Add missing sample CRs, CRDs and references.
3. Update existing sample CR for `triggerauthentication` which had the old API group of `keda.k8s.io` instead of the new `keda.sh`

### Checklist

- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [X] Tests have been added
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #5920

### CODE REVIEW

**Comment by joelsmith** [comment]
The check seems to be working. For example: https://github.com/kedacore/keda/actions/runs/9708520106/job/26795477554?pr=5921

```
Run make verify-manifests
./hack/verify-manifests.sh
ERROR: CR config/samples/eventing_v1alpha1_cloudeventsource.yaml is not listed in the resources section of config/samples/kustomization.yaml
ERROR: CRD config/crd/bases/keda.sh_clustertriggerauthentications.yaml does not have a sample CR config/samples/keda_v1alpha1_clustertriggerauthentication.yaml
ERROR: CR config/samples/keda_v1alpha1_clustertriggerauthentication.yaml is not listed in the resources section of config/samples/kustomization.yaml
make[1]: Entering directory '/__w/keda/keda'
...
./hack/../config up to date.
Check failed due to previous errors. See output above
make: *** [Makefile:1[5](https://github.com/kedacore/keda/actions/runs/9708520106/job/26795477554?pr=5921#step:12:6)3: verify-manifests] Error 1
Error: Process completed with exit code 2.
```

So now I need to add another commit to add the missing manifests and references.

**Review by zroubalik — APPROVED** [review]
LGTM, thanks

**Comment by joelsmith** [comment]
Sorry for the last-minute change. I just noticed that the sample CR I copied (triggerauthentication) had an API group of `keda.k8s.io` instead of `keda.sh` so I fixed the new clustertriggerauthentication one and also fixed the existing triggerauthentication.

**Review by tomkerkhove — APPROVED** [review]
Thank you!

**Pull request merged**
