### PR TITLE
Improve Redis support

### PR DESCRIPTION
**Pull request by jerbob92**
This pull request:

- Upgrades the Go Redis library from v6.15.9 to v8.11.4 
- Adds support for username, for ACL support in Redis 6+
- Adds support for Redis Sentinel

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated

### CODE REVIEW

**Comment by jerbob92** [comment]
@zroubalik
I'm quite far with the e2e tests, but I'm a little puzzled where these images are coming from:

- goku321/redis-cluster-list:v1.7
- goku321/redis-cluster-streams:v2.5 
- kedacore/tests-redis-lists:824031e
- abhirockzz/redis-streams-producer

**Comment by zroubalik** [comment]
The sources should be here: https://github.com/kedacore/test-tools/tree/master/e2e/images/redis

But the reference to https://github.com/orgs/kedacore/packages?repo_name=test-tools registry hasnt been changed yet in the current redis e2e tests. Would you mind changing it in your PR?

I hope that all sources are there.
Thanks!

**Comment by jerbob92** [comment]
> > > Overall this looks excellent.
> > > My one, fairly large all request is to remove the global `var ctx = context.Background()` and add it as a parameter to whatever function(s) requires a `context.Context`. I noted a few (bot not all) places where that would be appropriate
> > 
> > 
> > I have updated some of the code to use the context that Keda provides (in `IsActive()` and `GetMetrics()`) . The other places still use `context.Background()` since Keda doesn't provide a context in `buildScaler`/`buildScalers`/`GetScalers`. There is a context at some point when you go back more, that could eventually be passed into the `create*Scaler` methods, but that requires a significant rewrite of code outside the Redis code so it would probably good to create a separate task to implement context correctly in the codebase and pass it to all scalers since Redis probably isn't the only scaler that allows using context.
> 
> I agree, we should tackle the context propagation in a separate task. @jerbob92 would you mind opening an issue for this? Thanks!

Done: #2190

Just FYI: 
I have added the e2e tests, but I'm still waiting for the source code of the other e2e tests to finish it up. However, all checks are green now. Shouldn't pull requests be e2e tested too?

**Review by zroubalik — APPROVED** [review]

**Comment by jerbob92** [comment]
@zroubalik What do I have to do to get the images from test-tools? I'd like to run the e2e tests. The MR in test-tools has been marged but the new packages don't show up.

**Comment by zroubalik** [comment]
@jerbob92 I can see the images here: https://github.com/orgs/kedacore/packages?tab=packages&q=sent 

Do you need anything else?

**Comment by zroubalik** [comment]
@jerbob92 the e2e tests are running here: https://github.com/kedacore/keda/runs/4068547564?check_suite_focus=true

**Comment by jerbob92** [comment]
> @jerbob92 I can see the images here: https://github.com/orgs/kedacore/packages?tab=packages&q=sent
> 
> Do you need anything else?

They don't show up for me. Are they private by default?

**Comment by zroubalik** [comment]
@jerbob92 you are right, sorry I missed that. Fixing now, thanks!

**Comment by zroubalik** [comment]
```
2021-11-01T14:59:31.2034189Z >>> scalers/redis-sentinel-lists.test.ts.log <<<
2021-11-01T14:59:31.2034870Z 
2021-11-01T14:59:31.2035611Z namespace/redis-sentinel created
2021-11-01T14:59:31.2036545Z "bitnami" already exists with the same configuration, skipping
2021-11-01T14:59:31.2037742Z NAME: redis-sentinel
2021-11-01T14:59:31.2038501Z LAST DEPLOYED: Mon Nov  *** ***4:34:06 202***
2021-11-01T14:59:31.2039398Z NAMESPACE: redis-sentinel
2021-11-01T14:59:31.2040110Z STATUS: deployed
2021-11-01T14:59:31.2040728Z REVISION: ***
2021-11-01T14:59:31.2041304Z TEST SUITE: None
2021-11-01T14:59:31.2041875Z NOTES:
2021-11-01T14:59:31.2042444Z CHART NAME: redis
2021-11-01T14:59:31.2043062Z CHART VERSION: ***5.5.3
2021-11-01T14:59:31.2043683Z APP VERSION: 6.2.6
2021-11-01T14:59:31.2044066Z 
2021-11-01T14:59:31.2044806Z ** Please be patient while the chart is being deployed **
2021-11-01T14:59:31.2045375Z 
2021-11-01T14:59:31.2046252Z Redis&trade; can be accessed via port 6379 on the following DNS name from within your cluster:
2021-11-01T14:59:31.2047099Z 
2021-11-01T14:59:31.2048565Z     redis-sentinel.redis-sentinel.svc.cluster.local for read only operations
2021-11-01T14:59:31.2049675Z 
2021-11-01T14:59:31.2050782Z For read/write operations, first access the Redis&trade; Sentinel cluster, which is available in port 26379 using the same domain name above.
2021-11-01T14:59:31.2051682Z 
2021-11-01T14:59:31.2052011Z 
2021-11-01T14:59:31.2052311Z 
2021-11-01T14:59:31.2052878Z To get your password run:
2021-11-01T14:59:31.2053301Z 
2021-11-01T14:59:31.2054833Z     export REDIS_PASSWORD=$(kubectl get secret --namespace redis-sentinel redis-sentinel -o jsonpath="{.data.redis-password}" | base64 --decode)
2021-11-01T14:59:31.2056190Z 
2021-11-01T14:59:31.2056773Z To connect to your Redis&trade; server:
2021-11-01T14:59:31.2057230Z 
2021-11-01T14:59:31.2057886Z ***. Run a Redis&trade; pod that you can use as a client:
2021-11-01T14:59:31.2058366Z 
2021-11-01T14:59:31.2060007Z    kubectl run --namespace redis-sentinel redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD  --image docker.io/bitnami/redis:6.2.6-debian-***0-r2*** --command -- sleep infinity
2021-11-01T14:59:31.2061125Z 
2021-11-01T14:59:31.2061764Z    Use the following command to attach to the pod:
2021-11-01T14:59:31.2062240Z 
2021-11-01T14:59:31.2063000Z    kubectl exec --tty -i redis-client \
2021-11-01T14:59:31.2063935Z    --namespace redis-sentinel -- bash
2021-11-01T14:59:31.2064405Z 
2021-11-01T14:59:31.2064988Z 2. Connect using the Redis&trade; CLI:
2021-11-01T14:59:31.2066130Z    redis-cli -h redis-sentinel -p 6379 -a $REDIS_PASSWORD # Read only operations
2021-11-01T14:59:31.2067425Z    redis-cli -h redis-sentinel -p 26379 -a $REDIS_PASSWORD # Sentinel access
2021-11-01T14:59:31.2068028Z 
2021-11-01T14:59:31.2068841Z To connect to your database from outside the cluster execute the following commands:
2021-11-01T14:59:31.2069485Z 
2021-11-01T14:59:31.2070511Z     kubectl port-forward --namespace redis-sentinel svc/redis-sentinel 6379:6379 &
2021-11-01T14:59:31.2071704Z     redis-cli -h ***27.0.0.*** -p 6379 -a $REDIS_PASSWORD
2021-11-01T14:59:31.2072448Z Waiting for 3 pods to be ready...
2021-11-01T14:59:31.2073134Z Waiting for 2 pods to be ready...
2021-11-01T14:59:31.2074000Z error: timed out waiting for the condition
2021-11-01T14:59:31.2074631Z ***0.0.***86.235
2021-11-01T14:59:31.2075590Z namespace/redis-sentinel-lists-test created
2021-11-01T14:59:31.2076778Z secret/redis***
2021-11-01T14:59:31.2078512Z triggerauthentication.keda.sh/keda-redis-sentinel-list-triggerauth created
2021-11-01T14:59:31.2080064Z secret/redis-config created
2021-11-01T14:59:31.2081915Z triggerauthentication.keda.sh/keda-redis-sentinel-list-triggerauth-host-port created
2021-11-01T14:59:31.2083957Z deployment.apps/redis-worker-test-hostport created
2021-11-01T14:59:31.2085497Z scaledobject.keda.sh/redis-worker-test-hostport created
2021-11-01T14:59:31.2087000Z deployment.apps/redis-worker-test-address created
2021-11-01T14:59:31.2088515Z scaledobject.keda.sh/redis-worker-test-address created
2021-11-01T14:59:31.2090285Z deployment.apps/redis-worker-test-hostport-triggerauth created
2021-11-01T14:59:31.2092112Z scaledobject.keda.sh/redis-worker-test-hostport-triggerauth created
2021-11-01T14:59:31.2093349Z   ✖ before hook 
2021-11-01T14:59:31.2098450Z Error from server (NotFound): jobs.batch "redis-writer-host-port-ref" not found
2021-11-01T14:59:31.2100083Z Error from server (NotFound): jobs.batch "redis-writer-address-ref" not found
2021-11-01T14:59:31.2103536Z Error from server (NotFound): jobs.batch "redis-writer-host-port-trigger-auth" not found
2021-11-01T14:59:31.2105958Z scaledobject.keda.sh "redis-worker-test-hostport" deleted
2021-11-01T14:59:31.2107548Z scaledobject.keda.sh "redis-worker-test-address" deleted
2021-11-01T14:59:31.2109338Z scaledobject.keda.sh "redis-worker-test-hostport-triggerauth" deleted
2021-11-01T14:59:31.2111474Z triggerauthentication.keda.sh "keda-redis-sentinel-list-triggerauth" deleted
2021-11-01T14:59:31.2114202Z triggerauthentication.keda.sh "keda-redis-sentinel-list-triggerauth-host-port" deleted
2021-11-01T14:59:31.2116256Z deployment.apps "redis-worker-test-address" deleted
2021-11-01T14:59:31.2117958Z deployment.apps "redis-worker-test-hostport-triggerauth" deleted
2021-11-01T14:59:31.2119687Z deployment.apps "redis-worker-test-hostport" deleted
2021-11-01T14:59:31.2121018Z secret "redis-password" deleted
2021-11-01T14:59:31.2122273Z namespace "redis-sentinel-lists-test" deleted
2021-11-01T14:59:31.2123365Z release "redis-sentinel" uninstalled
2021-11-01T14:59:31.2124331Z namespace "redis-sentinel" deleted
2021-11-01T14:59:31.2125525Z   ✖ 6 tests remaining in scalers/redis-sentinel-lists.test.ts
2021-11-01T14:59:31.2126439Z   ─
2021-11-01T14:59:31.2126753Z 
2021-11-01T14:59:31.2127248Z   before hook
2021-11-01T14:59:31.2127586Z 
2021-11-01T14:59:31.2128125Z   Difference:
2021-11-01T14:59:31.2128477Z 
2021-11-01T14:59:31.2129035Z   - 0
2021-11-01T14:59:31.2129536Z   + ***
2021-11-01T14:59:31.2129836Z 
2021-11-01T14:59:31.2130778Z   › scalers/redis-sentinel-lists.test.ts:4***:6
2021-11-01T14:59:31.2131404Z 
2021-11-01T14:59:31.2131964Z   ─
2021-11-01T14:59:31.2132258Z 
2021-11-01T14:59:31.2132757Z   *** hook failed
```


```
2021-11-01T14:59:31.1350861Z >>> scalers/redis-sentinel-streams.test.ts.log <<<
2021-11-01T14:59:31.1351478Z 
2021-11-01T14:59:31.1352233Z namespace/redis-sentinel-streams created
2021-11-01T14:59:31.1353132Z "bitnami" already exists with the same configuration, skipping
2021-11-01T14:59:31.1354059Z NAME: redis-sentinel-streams
2021-11-01T14:59:31.1354747Z LAST DEPLOYED: Mon Nov  *** ***4:34:06 202***
2021-11-01T14:59:31.1355562Z NAMESPACE: redis-sentinel-streams
2021-11-01T14:59:31.1356198Z STATUS: deployed
2021-11-01T14:59:31.1356696Z REVISION: ***
2021-11-01T14:59:31.1357185Z TEST SUITE: None
2021-11-01T14:59:31.1357650Z NOTES:
2021-11-01T14:59:31.1358106Z CHART NAME: redis
2021-11-01T14:59:31.1358622Z CHART VERSION: ***5.5.3
2021-11-01T14:59:31.1359119Z APP VERSION: 6.2.6
2021-11-01T14:59:31.1359441Z 
2021-11-01T14:59:31.1360041Z ** Please be patient while the chart is being deployed **
2021-11-01T14:59:31.1360501Z 
2021-11-01T14:59:31.1361213Z Redis&trade; can be accessed via port 6379 on the following DNS name from within your cluster:
2021-11-01T14:59:31.1361783Z 
2021-11-01T14:59:31.1363370Z     redis-sentinel-streams.redis-sentinel-streams.svc.cluster.local for read only operations
2021-11-01T14:59:31.1364964Z 
2021-11-01T14:59:31.1366177Z For read/write operations, first access the Redis&trade; Sentinel cluster, which is available in port 26379 using the same domain name above.
2021-11-01T14:59:31.1367052Z 
2021-11-01T14:59:31.1367334Z 
2021-11-01T14:59:31.1367629Z 
2021-11-01T14:59:31.1368157Z To get your password run:
2021-11-01T14:59:31.1368545Z 
2021-11-01T14:59:31.1370182Z     export REDIS_PASSWORD=$(kubectl get secret --namespace redis-sentinel-streams redis-sentinel-streams -o jsonpath="{.data.redis-password}" | base64 --decode)
2021-11-01T14:59:31.1371342Z 
2021-11-01T14:59:31.1371928Z To connect to your Redis&trade; server:
2021-11-01T14:59:31.1372387Z 
2021-11-01T14:59:31.1373038Z ***. Run a Redis&trade; pod that you can use as a client:
2021-11-01T14:59:31.1373518Z 
2021-11-01T14:59:31.1375657Z    kubectl run --namespace redis-sentinel-streams redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD  --image docker.io/bitnami/redis:6.2.6-debian-***0-r2*** --command -- sleep infinity
2021-11-01T14:59:31.1376955Z 
2021-11-01T14:59:31.1377513Z    Use the following command to attach to the pod:
2021-11-01T14:59:31.1377943Z 
2021-11-01T14:59:31.1378671Z    kubectl exec --tty -i redis-client \
2021-11-01T14:59:31.1379589Z    --namespace redis-sentinel-streams -- bash
2021-11-01T14:59:31.1380084Z 
2021-11-01T14:59:31.1380597Z 2. Connect using the Redis&trade; CLI:
2021-11-01T14:59:31.1381678Z    redis-cli -h redis-sentinel-streams -p 6379 -a $REDIS_PASSWORD # Read only operations
2021-11-01T14:59:31.1382966Z    redis-cli -h redis-sentinel-streams -p 26379 -a $REDIS_PASSWORD # Sentinel access
2021-11-01T14:59:31.1384170Z 
2021-11-01T14:59:31.1385041Z To connect to your database from outside the cluster execute the following commands:
2021-11-01T14:59:31.1385733Z 
2021-11-01T14:59:31.1387057Z     kubectl port-forward --namespace redis-sentinel-streams svc/redis-sentinel-streams 6379:6379 &
2021-11-01T14:59:31.1388711Z     redis-cli -h ***27.0.0.*** -p 6379 -a $REDIS_PASSWORD
2021-11-01T14:59:31.1389513Z Waiting for 3 pods to be ready...
2021-11-01T14:59:31.1390256Z Waiting for 2 pods to be ready...
2021-11-01T14:59:31.1390996Z Waiting for *** pods to be ready...
2021-11-01T14:59:31.1391783Z error: timed out waiting for the condition
2021-11-01T14:59:31.1392466Z ***0.0.***0.***53
2021-11-01T14:59:31.1393529Z namespace/redis-sentinel-streams-test created
2021-11-01T14:59:31.1394814Z secret/redis***
2021-11-01T14:59:31.1399117Z triggerauthentication.keda.sh/keda-redis-stream-triggerauth created
2021-11-01T14:59:31.1402150Z deployment.apps/redis-streams-consumer created
2021-11-01T14:59:31.1405750Z scaledobject.keda.sh/redis-streams-scaledobject created
2021-11-01T14:59:31.1408566Z   ✖ before hook expected rollout status for redis to finish successfully
2021-11-01T14:59:31.1411159Z scaledobject.keda.sh "redis-streams-scaledobject" deleted
2021-11-01T14:59:31.1414370Z triggerauthentication.keda.sh "keda-redis-stream-triggerauth" deleted
2021-11-01T14:59:31.1417351Z secret "redis-password" deleted
2021-11-01T14:59:31.1419481Z deployment.apps "redis-streams-consumer" deleted
2021-11-01T14:59:31.1422034Z Error from server (NotFound): jobs.batch "redis-streams-producer" not found
2021-11-01T14:59:31.1424575Z namespace "redis-sentinel-streams-test" deleted
2021-11-01T14:59:31.1426913Z release "redis-sentinel-streams" uninstalled
2021-11-01T14:59:31.1429096Z namespace "redis-sentinel-streams" deleted
2021-11-01T14:59:31.1431000Z   ✖ 2 tests remaining in scalers/redis-sentinel-streams.test.ts
2021-11-01T14:59:31.1432144Z   ─
2021-11-01T14:59:31.1432455Z 
2021-11-01T14:59:31.1432947Z   before hook
2021-11-01T14:59:31.1433284Z 
2021-11-01T14:59:31.1433988Z   expected rollout status for redis to finish successfully
2021-11-01T14:59:31.1434527Z 
2021-11-01T14:59:31.1435032Z   Difference:
2021-11-01T14:59:31.1435396Z 
2021-11-01T14:59:31.1435952Z   - 0
2021-11-01T14:59:31.1436458Z   + ***
2021-11-01T14:59:31.1436771Z 
2021-11-01T14:59:31.1437714Z   › scalers/redis-sentinel-streams.test.ts:30:7
2021-11-01T14:59:31.1438374Z 
2021-11-01T14:59:31.1438930Z   ─
2021-11-01T14:59:31.1439445Z 
2021-11-01T14:59:31.1439962Z   *** hook failed
```

**Pull request merged**
