### PR TITLE
allow users to specificy a topic regexp

### LINKED ISSUE #2447: More flexible Kafka topic configuration
### Proposal

Today, Kafka scaler only allow to scale based on the lag of one topic.

A lot of streaming applications uses multiple topics, using the Kafka scaler can be cumbersome if using tens of topics, or a regex of topics.

Multiple improvements can be added if the underlying Kafka client support them to configure multiple topics wich lags will be sumed:
- Configuring a list of topics
- Configuring a topic regex
- Taking into accound the lag of all topics of the configured consumer group

### Use-Case

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by VerstraeteBert**
Signed-off-by: Bert Verstraete <bertverstraete22@gmail.com>

Allow users to use a regexp to select the kafka topics they wish to scale from

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated

Fixes #2447

### CODE REVIEW

**Comment by zroubalik** [comment]
@VerstraeteBert any update on this please?

**Comment by VerstraeteBert** [comment]
> @VerstraeteBert any update on this please?

@zroubalik Been quite busy lately, have some time this weekend to write tests etc. :-)

**Comment by VerstraeteBert** [comment]
Might pick this back up at a later time.

**Comment by kriegster108** [comment]
@VerstraeteBert could you pick this back up at some point? We would love to have this support as our kafka solution uses a tenant-per-topic pattern and would make our KEDA implementation a lot less complicated with use of regex. We need this in order to scale to 0 with KEDA because of the race condition that occurs in kafka when a brand new topic does not have any offset set yet.

**Pull request closed without merging**
