### PR TITLE
GCP Storage scaler: Add Prefix and Delimiter support

### LINKED ISSUE #3756: Add prefix support to Google Cloud Platform Storage scaler
### Proposal

Add prefix support to Google Cloud Platform Storage scaler.

Similar to `blobPrefix` in [Azure Blob Storage](https://keda.sh/docs/2.8/scalers/azure-storage-blob/).

This value is currently hardcoded to `""` in the code: https://github.com/kedacore/keda/blob/main/pkg/scalers/gcp_storage_scaler.go#L194

### Use-Case

This allows us to only watch part of a bucket.

### Anything else?

I might be able to contribute this myself but I thought I'd already open the issue to see if this is acceptable.

### PR DESCRIPTION
**Pull request by wrdls**
Signed-off-by: Ward Loos <ward.loos@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [X] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [X] Tests have been added
- [X] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #3756

Relates to [#963](https://github.com/kedacore/keda-docs/pull/963)

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Looking good! Could you solve DCO issues? All commits need to be signed.
Should we add an e2e test for this feature?

Also, I'd like to share that we have some issues with GCP account that we're solving with CNCF support, so atm we cannot trigger GCP e2e test, so before merging this PR I prefer to solve them and trigger GCP e2e test.

Of course, thanks for the contribution! ❤️

**Review by JorTurFer — APPROVED** [review]

**Comment by wrdls** [comment]
Thanks @JorTurFer for the approval ❤️

**Comment by JorTurFer** [comment]
Thanks to you for the improvement!! ❤️❤️❤️

**Pull request merged**
