### PR TITLE
Add more info about scalers and GetMetricsin README.md

### PR DESCRIPTION
**Pull request by eashi**
This change will add more explanation on how the scalers work, specifically explaining the idea that Kubernetes HPA will poll GetMetrics function in scalers.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks, is some good info!

However, not sure if we should add it to the README or a more detailed doc on this topic?

**Comment by eashi** [comment]
@tomkerkhove makes sense, should I create a specific page for scalers in the wiki?

**Comment by ahmelsayed** [comment]
As much as I like wikis, the github workflow for wiki contributions [is a bit awkward](https://stackoverflow.com/a/11481887/3234163). I'm not sure what's the best way to do this other than a `docs` folder in the repo, or add the wiki repo as a sub tree or something.

**Comment by eashi** [comment]
@ahmelsayed Just "thinking out loud" here, could we have a folder on the root for wiki, and through GitHub actions we push the changes to the official Git wiki repo?

**Comment by eashi** [comment]
Ok, I will create a folder in the root called `docs` and add a 'scalers.md' file and move that block there as a starting point. Does this align with your vision? 

We can think about automating synchroizing this folder with the wiki repo later then :)

**Pull request merged**
