### PR TITLE
Migrate e2e test for CPU scaler to Go.

### LINKED ISSUE #3169: Migrate e2e test for CPU scaler to Go.
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

### Use-Case

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aviadlevy**
Resolve #3169

Signed-off-by: aviadlevy <aviadlevy1@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #3169

### CODE REVIEW

**Comment by aviadlevy** [comment]
Wasn't sure if changelog entry is still necessary here

**Comment by JorTurFer** [comment]
> Wasn't sure if changelog entry is still necessary here

Yes please, use the section # Others (if there is an issue, there should be an update)

**Review by JorTurFer — COMMENTED** [review]
LGTM!
Please update the changelog and that's all ❤️

**Comment by JorTurFer** [comment]
merge conflict 😥

**Review by JorTurFer — APPROVED** [review]

**Comment by zroubalik** [comment]
> > Wasn't sure if changelog entry is still necessary here
> 
> Yes please, use the section # Others (if there is an issue, there should be an update)

Maybe we can use general entry in the # Others section for scalers migration. Otherwise the list could be pretty long. And the migration is not that important from users perspective, WDYT? @JorTurFer

**Comment by JorTurFer** [comment]
> Maybe we can use general entry in the # Others section for scalers migration. Otherwise the list could be pretty long. And the migration is not that important from users perspective, WDYT? @JorTurFer

Could be, maybe all of them under the general issue?

**Pull request merged**
