### PR TITLE
Temporal Scaler

### LINKED ISSUE #4724: Add Temporal.io Scaler
### Proposal

Add a Temporal.io Scaler to Keda so that workers can scale when the number of Open Workflows increases.

### Scaler Source

https://temporal.io/

### Scaling Mechanics

Calling the Temporal SDK ListOpenWorkflows method and scaling based on the value

### Authentication Source

mTLS

### Anything else?

https://github.com/temporalio/temporal/issues/33

### PR DESCRIPTION
**Pull request by ross-p-smith**
Added a scaler for [https://temporal.io/](https://temporal.io/)

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) https://github.com/kedacore/keda-docs/pull/1163
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4724

Relates to [Docs 1163](https://github.com/kedacore/keda-docs/pull/1163)

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
@ross-p-smith thanks for the contribution! I haven't done the full review yet, though there is one main thing missing - e2e tests. It's a hard requirement for us to accept a new scaler. Thanks!

https://github.com/kedacore/keda/blob/main/tests/README.md

**Comment by ross-p-smith** [comment]
Moving to draft whilst I schedule writing the e2e tests - @ScruffyFurn

**Comment by tomkerkhove** [comment]
@ross-p-smith based on https://github.com/kedacore/keda/pull/4863#issuecomment-1670277068, can we close this PR then?

**Comment by zroubalik** [comment]
Closing based on https://github.com/kedacore/keda/pull/4863#issuecomment-1670277068

**Pull request closed without merging**
