### PR TITLE
[WIP] Add info on how to build KEDA and deploy it local cluster

### PR DESCRIPTION
**Pull request by eashi**
A small paragraph on how to build KEDA and deploy it on a local cluster.

This will bring developers one step closer to contributing to KEDA. Of course there will be more effort in writing the docs for the scalers themselves.

### CODE REVIEW

**Comment by balchua** [comment]
I never found much use of `KedaScaleController.yaml`, i was using `helm template` instead.

Separate yamls tends to lead to it being stale.

Wdyt?

**Comment by eashi** [comment]
I agree, I will change it once I reach my PC.

On another front, if no one should use that deployment file then we should remove it. I might create another PR for that to keep concerns separate.

**Comment by eashi** [comment]
Thanks @balchua for the input, done :).

**Comment by eashi** [comment]
This PR is complete waiting for review. Upcoming documentation is going to be in another PR.

**Comment by eashi** [comment]
I am abandoning this PR in favour of new one based on latest 'master' #443 .

**Pull request closed without merging**
