### PR TITLE
Migrate MS SQL Scaler e2e test to Go

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added

Fixes https://github.com/kedacore/keda/issues/3242

Relates to #2737

### CODE REVIEW

**Comment by zroubalik** [comment]
@cgillum do you happen to have sources of this image: `docker.io/cgillum/mssqlscalertest:latest`? It has been used by e2e tests currently written in TS, we are migrating to Go and I'd like to tweak the producer a little bit. Or maybe even better to include it directly into the test code. Would help me a lot if you can share the sources, thanks!

**Comment by cgillum** [comment]
Hi @zroubalik, yes, I was able to find the source code for this. It's in C#. Let me know if you need the full project that builds and I can try to put it in a GitHub repo somewhere.

```csharp
namespace MSSQLScalerTest
{
    using System;
    using System.ComponentModel;
    using System.Linq;
    using System.Threading;
    using Microsoft.Data.SqlClient;

    class Program
    {
        static int Main(string[] args)
        {
            Console.WriteLine($"Received arguments: [{string.Join(' ', args)}]");
            try
            {
                if (args.FirstOrDefault()?.ToLower() == "producer")
                {
                    Producer();
                }
                else if (args.FirstOrDefault()?.ToLower() == "consumer")
                {
                    Consumer();
                }
                else
                {
                    Console.Error.WriteLine("Expected either 'producer' or 'consumer' as a command-line argument.");
                    return -1;
                }
            }
            catch (ApplicationException e)
            {
                Console.Error.WriteLine($"ERROR: {e.Message}");
                return -2;
            }

            return 0;
        }

        static void Producer()
        {
            const int ItemCount = 10;

            using var connection = GetAndOpenConnection();

            Console.WriteLine($"Inserting {ItemCount} items into the 'tasks' table...");

            for (int i = 0; i < 10; i++)
            {
                SqlCommand insertCommand = connection.CreateCommand();
                insertCommand.CommandText = "INSERT INTO tasks ([status]) VALUES ('queued')";
                insertCommand.ExecuteNonQuery();
            }

            Console.WriteLine($"Inserting {ItemCount} records successfully!");
        }

        static void Consumer()
        {
            using SqlConnection connection = GetAndOpenConnection();
            bool waiting = false;

            while (true)
            {
                // Read and update the status in a single statement
                using SqlCommand getTaskCommand = connection.CreateCommand();
                getTaskCommand.CommandText = "UPDATE TOP (1) tasks SET [status] = 'running' OUTPUT inserted.[id] WHERE [status] = 'queued'";

                using SqlDataReader reader = getTaskCommand.ExecuteReader();
                if (reader.Read())
                {
                    waiting = false;

                    int id = (int)reader["id"];
                    Console.WriteLine($"Executing task {id}...");
                    reader.Close();

                    // Simulate work
                    Thread.Sleep(TimeSpan.FromSeconds(30));

                    using SqlCommand completeTaskCommand = connection.CreateCommand();
                    completeTaskCommand.CommandText = "UPDATE tasks SET [status] = 'complete' WHERE [id] = @id";
                    completeTaskCommand.Parameters.AddWithValue("@id", id);
                    completeTaskCommand.ExecuteNonQuery();
                }
                else
                {
                    if (!waiting)
                    {
                        Console.WriteLine($"Waiting for tasks to process...");
                    }

                    waiting = true;
                    Thread.Sleep(TimeSpan.FromSeconds(5));
                }
            }
        }

        static SqlConnection GetAndOpenConnection()
        {
            const string EnvVariableName = "SQL_CONNECTION_STRING";
            string connectionString = Environment.GetEnvironmentVariable(EnvVariableName);
            if (string.IsNullOrEmpty(connectionString))
            {
                throw new ApplicationException($"Could not find an environment variable named {EnvVariableName}!");
            }

            var connection = new SqlConnection(connectionString);

            Console.WriteLine($"Opening connection to '{connection.Database}' at '{connection.DataSource}'...");
            connection.Open();
            return connection;
        }
    }
}

```

**Comment by zroubalik** [comment]
@cgillum do you think that you can push new image where the number of items in producer is parametrized? We will use that image as a temporary solution to complete the migration to Go.

Then we will most likely create a new issue for rewrite the producer/consumer code in Go and directly run in the testsuite.

**Comment by zroubalik** [comment]
And put the sources here please: https://github.com/kedacore/test-tools/tree/main/e2e/images

**Review by JorTurFer — APPROVED** [review]

**Comment by zroubalik** [comment]
Follow up: https://github.com/kedacore/keda/issues/3401

**Pull request merged**
