### PR TITLE
chore: Improve azure podIdentity logs

### PR DESCRIPTION
**Pull request by JorTurFer**
This PR adds some logs to the azure chained provider to help on cases as https://github.com/kedacore/keda/issues/5006

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to https://github.com/kedacore/keda/issues/5006

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by JorTurFer** [comment]
As my last commit was for adding a whitespace (to split import groups) and the other commit passed the e2e tests, I have skipped e2e test

**Pull request merged**
