### PR TITLE
Template variable for e2e log

### LINKED ISSUE #3192: Templates name aren't clear in the output in the error log for the latest e2e testing.
### Report

While doing negative testing on the latest migrated code for the e2e testing, the output for a test with erroneous template was this: 
 
`cannot apply file - error: error parsing /tmp/tempTemplateFile393652011: error converting YAML to JSON: yaml: line 31: could not find expected ':'`

This proves to be confusing in case we have scalers with multiple templates.

### Expected Behavior

The expected behavior was something like this:

`cannot apply file - error: error parsing /tmp/deploymentTemplateFile393652011: error converting YAML to JSON: yaml: line 31: could not find expected ':'`

or as mentioned by @JorTurFer it could also be printing the template itself in the error log.

### Actual Behavior

The error log doesn't provide clarity to which exact template file is causing error and the error is like this:

```	
Error Trace:	helper.go:170
        	            				helper.go:178
        	            				helper.go:209
        	            				cpu_test.go:127
        	Error:      	Received unexpected error:
        	            	error: error parsing /tmp/tempTemplateFile1287392103: error converting YAML to JSON: yaml: line 31: could not find expected ':'
```

### Steps to Reproduce the Problem

1. make an error in templateFile.
2. Run go test on the test file with : `go test -v ./scalers_go/scalerName/scalerName_test.go`
3. find the error in output

### Logs from KEDA operator

None

### KEDA Version

2.7.1

### Kubernetes Version

1.23

### Platform

Any

### Scaler Details

Any

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Ritikaa96**
Added a variable for template name in /tests/helper/helpers.go to clarify any erroneous template file developer is applying.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added

Fixes #3192

### CODE REVIEW

**Comment by Ritikaa96** [comment]
Hi @JorTurFer , the e2e run seems to be cancelled.

**Comment by Ritikaa96** [comment]
@JorTurFer should I add this into the changelog? it's a bug we are improving. not sure if should add to the changelog or not.

**Comment by v-shenoy** [comment]
Could you also rebase once onto main? There are some tests that were added  which will also require changes.

**Comment by Ritikaa96** [comment]
@JorTurFer and what about CHANGELOG? should i just remove it from task list ?

**Comment by Ritikaa96** [comment]
@v-shenoy @JorTurFer Updated  the Readme and new scaler tests. PTAL

> Could you also rebase once onto main? There are some tests that were added which will also require changes.



> Looking good! Please also update https://github.com/kedacore/keda/blob/main/tests/README.md with the new parameters

**Comment by Ritikaa96** [comment]
@JorTurFer Any idea why would the CI/Validate PR be failing here?

**Comment by JorTurFer** [comment]
> @JorTurFer and what about CHANGELOG? should i just remove it from task list ?

you don't need to modify it for this I think

**Review by JorTurFer — APPROVED** [review]
❤️

**Comment by Ritikaa96** [comment]
Thanks @JorTurFer :)

**Pull request merged**
