### PR TITLE
Expose prometheus metrics at ScaledJob like ScaledObject

### PR DESCRIPTION
**Pull request by yoongon**
_Provide a description of what has been changed_
Expose prometheus metrics at ScaledJob like ScaledObject
Refer to : https://github.com/kedacore/keda/issues/4798

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #
https://github.com/kedacore/keda/issues/4798

Relates to #

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Thanks for the contribution!

As the goal is adding new metrics, we should create [new counters here](https://github.com/kedacore/keda/blob/main/pkg/prommetrics/prommetrics.go) for them and update those counters instead of reusing already existing counters for ScaledObjects. Otherwise,  It could be confusing

**Comment by yoongon** [comment]
Thanks for the feedback. I will update the code again.

**Comment by yoongon** [comment]
> Thanks for the contribution!
> 
> As the goal is adding new metrics, we should create [new counters here](https://github.com/kedacore/keda/blob/main/pkg/prommetrics/prommetrics.go) for them and update those counters instead of reusing already existing counters for ScaledObjects. Otherwise, It could be confusing

@JorTurFer 
=> I updated the code with new counters for ScaledJob. Could you check again? Thanks.

**Review by JorTurFer — COMMENTED** [review]
We can't rename the already existing metrics because that's a breaking change and our deprecation policy requires 2 version between deprecation and removal.
I'm thinking in 2 different option for this:
- Use a new label to  inform if it's ScaledObject or ScaledJobs on metrics where the name isn't clear, such as 'keda_scaler_active' or `keda_scaler_metrics_value`, and duplicating the metrics with clear name, for example `keda_scaled_object_errors` with `keda_scaled_job_errors`
- Duplicate all the metrics for the ScaledJobs

In both cases, we should maintain current metrics, but I'm not sure about which is the best approach for new metrics, I don't have any strong opinion but personally I prefer the labels option. WDYT @kedacore/keda-core-contributors ?

In any case, we have to add e2e test coverage to these metrics: https://github.com/kedacore/keda/blob/main/tests/sequential/prometheus_metrics/prometheus_metrics_test.go

**Comment by yoongon** [comment]
> We can't rename the already existing metrics because that's a breaking change and our deprecation policy requires 2 version between deprecation and removal. I'm thinking in 2 different option for this:
> 
> * Use a new label to  inform if it's ScaledObject or ScaledJobs on metrics where the name isn't clear, such as 'keda_scaler_active' or `keda_scaler_metrics_value`, and duplicating the metrics with clear name, for example `keda_scaled_object_errors` with `keda_scaled_job_errors`
> * Duplicate all the metrics for the ScaledJobs
> 
> In both cases, we should maintain current metrics, but I'm not sure about which is the best approach for new metrics, I don't have any strong opinion but personally I prefer the labels option. WDYT @kedacore/keda-core-contributors ?
> 
> In any case, we have to add e2e test coverage to these metrics: https://github.com/kedacore/keda/blob/main/tests/sequential/prometheus_metrics/prometheus_metrics_test.go

You are right. I shouldn't have changed that. I will take a look at better solution.

**Comment by yoongon** [comment]
> * Use a new label to  inform if it's ScaledObject or ScaledJobs on metrics where the name isn't clear, such as 'keda_scaler_active' or `keda_scaler_metrics_value`, and duplicating the metrics with clear name, for example `keda_scaled_object_errors` with `keda_scaled_job_errors`

@JorTurFer 
I have a question for the above comment. Are you suggesting these steps?
```
1. Preserve existing metrics such as **keda_scaler_metrics_value** for ScaledObject
2. Creating new metrics like **keda_scaler_scaled_object_metrics_value**  and **keda_scaler_scaled_jobe_metrics_value**
3. Deprecate **keda_scaler_metrics_value**  in the future.
```

Do I understand right?

**Comment by JorTurFer** [comment]
> I have a question for the above comment. Are you suggesting these steps?
> 
> ```
> 1. Preserve existing metrics such as **keda_scaler_metrics_value** for ScaledObject
> 2. Creating new metrics like **keda_scaler_scaled_object_metrics_value**  and **keda_scaler_scaled_jobe_metrics_value**
> 3. Deprecate **keda_scaler_metrics_value**  in the future.
> ```
> 
> Do I understand right?

Sorry for the slow response (the summer break xD)

No, I meant that metrics like `keda_scaler_metrics_value` (which doesn't say anything related with ScaledObject) can be extended using labels for adding the extra information about if it's from ScaledObject or ScaledJob, duplicate them it's not necessary.

For labels whose have scaledobject in the naming such us `keda_scaled_object_errors`, we can duplicate the for scaledjobs , for example `keda_scaled_object_errors` and `keda_scaled_job_errors`. Or maybe unifying both in something like `keda_scalable_object_errors`, using labels to clarify if the metric is for so or sj

**Comment by yoongon** [comment]
@JorTurFer 
Thanks for the feedback. It becomes much clear for me.
I updated. PLTAL.
Thanks!

**Comment by yoongon** [comment]
Using GitHub sync break the changes. 
I will reopen a new PR.

**Comment by yoongon** [comment]
I opened a new PR here.
https://github.com/kedacore/keda/pull/4913

**Pull request closed without merging**
