### PR TITLE
Add logic to scale to zero on invalid offset even with earliest offsetResetPolicy

### PR DESCRIPTION
**Pull request by dttung2905**
_Provide a description of what has been changed_

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/4910

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
@dttung2905 what is the status of this? This would be a really great addition to our next release.

**Comment by dttung2905** [comment]
@zroubalik Thanks for helping me running the e2e test. This is my first time running it so I was checking with @JorTurFer last night if I could run it myself :laughing: . I have found out the root cause why the e2e test failed. I will try to make changes tomorrow

What's left of this PR are just :crossed_fingers: 
- Changelog
- Fix e2e test cases

**Comment by dttung2905** [comment]
I think most of the E2E test cases have passed except 1 or 2 - `testOneOnInvalidOffsetWithEarliestOffsetResetPolicy` is one of them . Let me take more time to look into that

**Review by JorTurFer — APPROVED** [review]
LGTM! Thanks for the improvement ❤️ 
@zroubalik PTAL 🙏

**Review by zroubalik — APPROVED** [review]
LGTM, great job!

**Pull request merged**
