### PR TITLE
Provide support for Huawei Cloud CloudEye scaler

### PR DESCRIPTION
**Pull request by iyacontrol**
add support for huaweicloud cloudeye scaler.

### CODE REVIEW

**Comment by iyacontrol** [comment]
[samples and docs ](https://github.com/kedacore/keda-docs/pull/50)

**Comment by tomkerkhove** [comment]
Awesome, thanks @iyacontrol!

**Comment by iyacontrol** [comment]
hi @tomkerkhove , can you review my code ? thanks.

**Comment by tomkerkhove** [comment]
I'll leave this up to @ahmelsayed

**Comment by ahmelsayed** [comment]
sorry for the delay, I was out last week. I'll take a look at the PR this week

**Comment by iyacontrol** [comment]
hi @ahmelsayed . If you can review my code this week, I would really appreciate it.

**Pull request merged**
