### PR TITLE
Add support for AWS temporary credentials

### LINKED ISSUE #2495: Add support for temporary AWS IAM credentials (using session tokens) from secrets
Hello,

In my environment there are situations where temporary (sts-generated) IAM role credentials are stored in Kubernetes secrets and updated as needed. In this environment IRSA is unavailable, and we cannot permit KEDA to assume-role.

Instead, it'd be great if we could use the existing static credentials mechanism, and add support for specifying session tokens (needed for temporary credentials). For example:

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: keda-test
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: test-secrets            # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: test-secrets            # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
  - parameter: awsSessionToken # Optional.
    name: test-secrets # Optional.
    key: AWS_SESSION_TOKEN # Optional.
```

If this proposal is acceptable, I can craft the PR. Adding support for the extra value seems to be straightforward. I just need to research how credential refreshing would be implemented (assuming it's needed), as these temporary creds would obviously expire after some time.

### PR DESCRIPTION
**Pull request by JacobHenner**
Add support for AWS temporary credentials by allowing session tokens to
be specified.

Assuming Secrets are kept up-to-date with valid session tokens, scalers
using temporary credentials will error once after token expiration. The
scaler cache for the corresponding ScaledObject will be cleared, the
scaler will be rebuilt using the updated temporary credentials, and the
scaler will resume operation.

Signed-off-by: Jacob Henner <code@ventricle.us>

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [X] Tests have been added
- [X] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) 
  - https://github.com/kedacore/keda-docs/pull/642 
- [x] Changelog has been updated

Fixes #2495

### CODE REVIEW

**Comment by JacobHenner** [comment]
> Assuming Secrets are kept up-to-date with valid session tokens, scalers using temporary credentials will error once after token expiration. The scaler cache for the corresponding ScaledObject will be cleared, the scaler will be rebuilt using the updated temporary credentials, and the scaler will resume operation.

I am looking for feedback on whether waiting for an error is an acceptable way to trigger a credential refresh (i.e. reread the contents of the k8s Secret, which has presumably been updated). This approach worked in my testing, but I do realize there are at least a few potentially unwanted effects:

* Scaler cache needs to be invalidated/rebuilt (probably not a big deal, but worth mentioning)
* An HPA Scaler Error will be recorded each time a temporary credential expires (potentially a bigger deal, depending on the expectations of users consuming this metric)

https://github.com/kedacore/keda/blob/6b72e85fdac4de2c1f9dd3834164912b587cb225/pkg/provider/provider.go#L122-L132

**Comment by zroubalik** [comment]
>     * An HPA Scaler Error will be recorded in the metrics each time a temporary credential expires (potentially a bigger deal, depending on the expectations of users consuming this metric)

Are you able to distinguish the error caused by expired credentials? We might want to add a check in here to not include that in the metric or maybe better would be to introduce a new type of metrics for credentials expiration?

**Comment by JacobHenner** [comment]
> Are you able to distinguish the error caused by expired credentials? We might want to add a check in here to not include that in the metric or maybe better would be to introduce a new type of metrics for credentials expiration?

The logs reflect a 403 "ExpiredToken", but I haven't explored if the library that interacts with AWS parses the specifics of the error (or if it's just returning error text from the API), or how the specifics could be propagated back to KEDA.

Assuming the error can be propagated back, how would we prefer to handle it?

We could:

* Create a new type of metric for creds expiration - but I think that'd be similarly confusing (one event at expiration time is expected, > 1 event at expiration time is bad and indicates actual scaler failure). 
* Only report a failure for credential expiration errors if there are >= 2 consecutive failures
  * We might want to consider a similar approach for static credentials too, as they can also be rotated (generally with a much lower frequency).
* Build an independent credential refresh mechanism - e.g. #511, #563
* (something else?)

**Comment by zroubalik** [comment]
> > Are you able to distinguish the error caused by expired credentials? We might want to add a check in here to not include that in the metric or maybe better would be to introduce a new type of metrics for credentials expiration?
> 
> The logs reflect a 403 "ExpiredToken", but I haven't explored if the library that interacts with AWS parses the specifics of the error (or if it's just returning error text from the API), or how the specifics could be propagated back to KEDA.
> 
> Assuming the error can be propagated back, how would we prefer to handle it?
> 
> We could:
> 
>     * Create a new type of metric for creds expiration - but I think that'd be similarly confusing (one event at expiration time is expected, > 1 event at expiration time is bad and indicates actual scaler failure).
> 
>     * Only report a failure for credential expiration errors if there are >= 2 consecutive failures
>       
>       * We might want to consider a similar approach for static credentials too, as they can also be rotated (generally with a much lower frequency).
> 
>     * Build an independent credential refresh mechanism - e.g. [Watch created HPA and TriggerAuthentication resources #511](https://github.com/kedacore/keda/issues/511), [TriggerAuthentication Secret is not reloaded when Secret changes #563](https://github.com/kedacore/keda/issues/563)
> 
>     * (something else?)

Those are all good questions, I think we can go ahead with this change as it is now and open an issue for the follow up?
I will do a proper review tomorrow, but could you please update the Changelog as well? 
Thanks!

**Comment by JacobHenner** [comment]
> Those are all good questions, I think we can go ahead with this change as it is now and open an issue for the follow up?
> I will do a proper review tomorrow, but could you please update the Changelog as well? 
> Thanks!

Yep, that's fine by me. I'll make the changelog addition in a bit. Thanks!

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by zroubalik** [comment]
@JacobHenner could you please open follow up issue with the concerns we raised here?

**Comment by JacobHenner** [comment]
> @JacobHenner could you please open follow up issue with the concerns we raised here?

https://github.com/kedacore/keda/issues/2578

**Pull request merged**
