### PR TITLE
fix: Register only the wanted Azure credential in the chain

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge.turrado@scrm.lidl>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/4123

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Looking good, please update Changelog.

**Comment by JorTurFer** [comment]
> Looking good, please update Changelog.

Done! :)

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
