### PR TITLE
Change ClusterRoleBinding name to align with industry standard

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR changes the name of the ClusterRoleBinding. This appeared after running https://github.com/helm/chart-testing on the kedacore/charts repository.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)* https://github.com/kedacore/charts/pull/123
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated

### CODE REVIEW

**Comment by ubergesundheit** [comment]
I'll leave this PR open until https://github.com/kedacore/charts/pull/84 is merged if you don't mind

**Review by ahmelsayed — APPROVED** [review]

**Comment by ahmelsayed** [comment]
@tomkerkhove is this good to merge?

**Comment by tomkerkhove** [comment]
This relates to https://github.com/kedacore/charts/pull/84, shall we go ahead with this @zroubalik?

This could be considered as breaking, though.

**Comment by zroubalik** [comment]
@tomkerkhove I think that we can go with this one, but should mention somewhere, that there might be a leftover ClusterRoleBinding `keda:system:auth-delegator` when users will be updating from KEDA < 2.4

**Comment by tomkerkhove** [comment]
Sounds good to me - @ubergesundheit would you mind rebasing main branch and adding an extra note to the changelog please?

**Comment by ubergesundheit** [comment]
> Sounds good to me - @ubergesundheit would you mind rebasing main branch and adding an extra note to the changelog please?

sure :)

**Comment by ubergesundheit** [comment]
The changelog entry now reads `Fix `keda-system-auth-delegator` ClusterRoleBinding name ([#1616](https://github.com/kedacore/keda/pull/1616). Upgrading may leave a stray ClusterRoleBinding with the old name `keda:system:auth-delegator` behind.`

**Comment by zroubalik** [comment]
> The changelog entry now reads `Fix `keda-system-auth-delegator`ClusterRoleBinding name ([#1616](https://github.com/kedacore/keda/pull/1616). Upgrading may leave a stray ClusterRoleBinding with the old name`keda:system:auth-delegator` behind.`

Would you mind moving it to `## Breaking Changes` section? thx!

**Comment by ubergesundheit** [comment]
Are you going to squash this PR? Should I squash?

**Comment by tomkerkhove** [comment]
No it's ok - I'll squash it!

**Comment by tomkerkhove** [comment]
Are you willing to update our chart as well @ubergesundheit?

**Comment by ubergesundheit** [comment]
@tomkerkhove you already have an open PR (created by you :stuck_out_tongue: ) https://github.com/kedacore/charts/pull/84

**Comment by tomkerkhove** [comment]
😂

I'm a moron - Thank you!

**Comment by gldraphael** [comment]
Hi, I'm currently on v2.3.2

Running a `kubectl get clusterrolebindings` returns the following:

```
NAME                                                   ROLE                                                               AGE
keda-operator                                          ClusterRole/keda-operator                                          50d
keda-operator-hpa-controller-external-metrics          ClusterRole/keda-operator-external-metrics-reader                  50d
keda-operator:system:auth-delegator                    ClusterRole/system:auth-delegator                                  50d
```

Is `keda:system:auth-delegator` a typo? Was it meant to be `keda-operator:system:auth-delegator` instead?

**Pull request merged**
