### PR TITLE
Add AWS Kinesis Stream Scaler e2e test

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Relates to https://github.com/kedacore/keda/issues/1526

### CODE REVIEW

**Comment by zroubalik** [comment]
seems like there is some problem in the scaler itself: 
https://github.com/kedacore/keda/runs/5712186540?check_suite_focus=true

**Comment by JorTurFer** [comment]
I'd say that yesterday we reached the API rate limit:
```
LimitExceededException: Rate exceeded for stream keda-steam under account 58976***922677.
```
Maybe we should keep the stream created all the time, but tbh, I prefer to don't keep infra created if it's not needed.
Mybe we could check how it works during the next days and if it's a flaky test in due to that, I'll update it for not destroying the infra. (ofc, now the test has to pass in order to do this)
WDYT?

**Comment by zroubalik** [comment]
> I'd say that yesterday we reached the API rate limit:
> 
> ```
> LimitExceededException: Rate exceeded for stream keda-steam under account 58976***922677.
> ```
> 
> Maybe we should keep the stream created all the time, but tbh, I prefer to don't keep infra created if it's not needed. Mybe we could check how it works during the next days and if it's a flaky test in due to that, I'll update it for not destroying the infra. (ofc, now the test has to pass in order to do this) WDYT?
+1

Though we should properly handle that part in the scaler as well -> don't cause panic, but return error instead.

**Comment by JorTurFer** [comment]
You are right! I didn't see the panic error in the metrics server logs

**Comment by JorTurFer** [comment]
Do you think that I should fix it in the context of this PR or maybe another issue and PR split?

**Comment by zroubalik** [comment]
I'd create a separate one.

**Comment by JorTurFer** [comment]
> I'd create a separate one.

Sure!
https://github.com/kedacore/keda/issues/2833

**Comment by JorTurFer** [comment]
I got the problem... Reusing the same name for all the streams, the API limit is 10 request every 24 to update the shards. I have updated the PR to generate a new stream on every PR (and delete at the end)

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
