### PR TITLE
fix(kafka): Handle Sarama errors properly

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

This PR adds extra traces to log Sarama errors but even they are errors that we aren't "catching" I haven't modified the behaviour to  avoid breaking changes introduced by different error handling. 

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes https://github.com/kedacore/keda/issues/3056

### CODE REVIEW

**Comment by JorTurFer** [comment]
Should I return them as regular errors and break the cycle instead of maintaining current behaviour? 
WDYT @zroubalik ?

**Review by zroubalik — COMMENTED** [review]
Do you think you can try to get more detailed errors from the client creation?
Usually when there is a problem in conecting to Kafka Broker, there is just a generic error message stating, that client is not able to connect. Would be nice if we could get more detailed error info there.

**Comment by zroubalik** [comment]
> Should I return them as regular errors and break the cycle instead of maintaining current behaviour? WDYT @zroubalik ?

As a first step, I'd try to get as much (error) information as possible without breaking the current behaviour.

**Comment by JorTurFer** [comment]
> Do you think you can try to get more detailed errors from the client creation? Usually when there is a problem in conecting to Kafka Broker, there is just a generic error message stating, that client is not able to connect. Would be nice if we could get more detailed error info there.

checking

**Comment by JorTurFer** [comment]
AFAI can see, we can't get more info because client creation doesn't bring any KError, so we only can check the standard error. 
I have tried creating an authorized broker connection without credentials and I can see the authentication errors on the first call to the broker (not in the client creation but in the call to DescribeTopics)

**Comment by zroubalik** [comment]
> AFAI can see, we can't get more info because client creation doesn't bring any KError, so we only can check the standard error. I have tried creating an authorized broker and connecting KEDA without credentials and I can see the authentication errors (from Kerror) on the first call to the broker (not in the client creation but in the call to DescribeTopics)

ack, thanks!

**Review by zroubalik — APPROVED** [review]

**Comment by zroubalik** [comment]
@JorTurFer please fix changelog and merge :)

**Pull request merged**
