### PR TITLE
chore: Add testing documentation

### PR DESCRIPTION
**Pull request by JorTurFer**
I have ported the documentation that we provided during graduation DD to the repository in order to make it publicly accessible and easy to find

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/4173

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]

**Comment by SpiritZhou** [comment]
Just want to share something when writing e2e tests. When I try to run my new e2e tests locally, the setup command ("go test -v -tags e2e ./utils/setup_test.go") deployed the official KEDA image, which is not convenient for debugging new tests with a changed KEDA. I suggest adding a parameter in the setup command for deploying the custom image repository so that developers can use their KEDA repository for debugging.

**Comment by JorTurFer** [comment]
> Just want to share something when writing e2e tests. When I try to run my new e2e tests locally, the setup command ("go test -v -tags e2e ./utils/setup_test.go") deployed the official KEDA image, which is not convenient for debugging new tests with a changed KEDA. I suggest adding a parameter in the setup command for deploying the custom image repository so that developers can use their KEDA repository for debugging.

It's already supported but not properly documented I think. As KEDA is deployed using make, and Makefile uses variables, you can set those envs (globally o for the command) and that's all. 
Let me update the PR with that info

**Comment by JorTurFer** [comment]
@SpiritZhou @zroubalik  PTAL

**Comment by SpiritZhou** [comment]
> @SpiritZhou @zroubalik PTAL

It looks great now!

**Review by SpiritZhou — APPROVED** [review]

**Comment by JorTurFer** [comment]
lol, although I requested a revision of @zroubalik , looks like GH already took into account the previous approval and the automerger did its job. I guess that I had to dismiss the approval instead or request another review :/
image

**Pull request merged**
