### PR TITLE
Use a different cluster for pr e2e runs

### PR DESCRIPTION
**Pull request by ahmelsayed**
Signed-off-by: Ahmed ElSayed <ahmed@elsayed.io>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated

Fixes #

### CODE REVIEW

**Comment by JorTurFer** [comment]
This is super nice @ahmelsayed !!
Thanks! ❤️

**Review by JorTurFer — CHANGES_REQUESTED** [review]
This is super nice @ahmelsayed !!
Thanks! ❤️ 
Only 1 small nit, if we will have 2 clusters, one for main/scheduled e2e tests and another for pr-e2e test, could you update the concurrency for this last one? 
https://github.com/kedacore/keda/blob/main/.github/workflows/pr-e2e.yml#L42

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
thanks @ahmelsayed ! ❤️

**Review by zroubalik — APPROVED** [review]
This is great, thanks @ahmelsayed !

**Pull request merged**
