### PR TITLE
fix: apply semgrep suggestions

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

Fix some code alerts generated by semgrep

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to https://github.com/kedacore/keda/issues/3961

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by JorTurFer** [comment]
> LGTM

I have to add a lot of extra changes for the rule `[Semgrep found a possible error wrong wrapped](https://github.com/kedacore/keda/security/code-scanning/534)`. If you agree, I'll merge the PR once I have done them and e2e tests pass

**Comment by zroubalik** [comment]
> > LGTM
> 
> I have to add a lot of extra changes for the rule `[Semgrep found a possible error wrong wrapped](https://github.com/kedacore/keda/security/code-scanning/534)`. If you agree, I'll merge the PR once I have done them and e2e tests pass

yeah :)

**Pull request merged**
