### PR TITLE
gcp_pubsub: fix scaled object default value (#5093)

### LINKED ISSUE #5093: Issue with GCP PubSub scaledObject
### Discussed in https://github.com/kedacore/keda/discussions/4751

<div type='discussions-op-text'>

<sup>Originally posted by **raghu-manne** June 29, 2023</sup>
I am trying to test out keda with GCP pubsub andd the getting below error. Any insights where am i doing wrong?
`2023-06-29T11:26:13Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"test","namespace":"default"}, "namespace": "default", "name": "test", "reconcileID": "5b54cc98-02bf-4dea-a270-125a70a957b5", "error": "HorizontalPodAutoscaler.autoscaling \"keda-hpa-test\" is invalid: spec.metrics[0].external.target.averageValue: Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:\"0\", Format:\"DecimalSI\"}: must be positive"}
`
My scaledobject looks like this

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pubsub-test
  namespace: default
spec:
  scaleTargetRef:
    name: consume-pubsub-messages #Target Workload Name
  triggers:
  - type: gcp-pubsub
    authenticationRef:
      name: test
    metadata:
      subscriptionName: "keda-test-subscription" # Required
````

Scaledobject events says this
```
Events:
  Type     Reason                   Age                    From           Message
  ----     ------                   ----                   ----           -------
  Warning  ScaledObjectCheckFailed  2m6s (x16 over 4m50s)  keda-operator  failed to ensure HPA is correctly created for ScaledObject
```</div>

### PR DESCRIPTION
**Pull request by jimgus**
Fix that the default value of `value` is used when default value of `mode` is used for GCP pubsub scaler.

### Checklist

- [N/A] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [N/A] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [N/A] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #5093

Relates to #

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
Sorry, I missed this PR 🤦 
Could you rebase the PR to fix the conflict?

**Comment by JorTurFer** [comment]
Last commit has broken the DCO check. You need to sign it 🙏

**Review by zroubalik — COMMENTED** [review]
@jimgus could you please fix the DCO so we can go ahead and merge this?

**Pull request merged**
