### PR TITLE
Redis Streams Scaler

### LINKED ISSUE #746: KEDA scaler for Redis Streams
[Redis Streams](https://redis.io/topics/streams-intro), a data type introduced with Redis 5.0 is an append-only log data structure. One of its features includes "consumer groups" that allows a group of clients to co-operate consuming a different portion of the same stream of messages.

This scaler can check the Pending Entries List (see `XPENDING` https://redis.io/commands/xpending) for a specific Consumer Group of a Redis Stream and scale-out the Deployment as per the count returned (by `XPENDING` command). If you have a Redis Streams consumer application that is unable to keep up with the rate of production, KEDA can help by auto-scaling the no. of instances (part of the same consumer group) so that it can start sharing the processing workload. 

  - **Scaler Source:** Redis Streams (Pending Entries List aka *PEL*)
  - **Authentication:** Password-based authentication supported by Redis

### PR DESCRIPTION
**Pull request by abhirockzz**
[Redis Streams](https://redis.io/topics/streams-intro), a data type introduced with Redis 5.0 is an append-only log data structure. One of its features includes "consumer groups" that allows a group of clients to co-operate consuming a different portion of the same stream of messages.

This scaler can check the Pending Entries List (see `XPENDING` https://redis.io/commands/xpending) for a specific Consumer Group of a Redis Stream and scale-out the Deployment as per the count returned (by `XPENDING` command). If you have a Redis Streams consumer application that is unable to keep up with the rate of production, KEDA can help by auto-scaling the no. of instances (part of the same consumer group) so that it can start sharing the processing workload. 

### Checklist

- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Tests have been added

Fixes #746

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks man - Let me know when there are docs to review!

**Comment by abhirockzz** [comment]
> Thanks man - Let me know when there are docs to review!

Docs PR - https://github.com/kedacore/keda-docs/pull/147

**Comment by zroubalik** [comment]
@abhirockzz do you think it would be possible to add e2d tests for Redis Streams Scaler?

https://github.com/kedacore/keda/tree/master/tests#adding-tests

**Comment by abhirockzz** [comment]
> @abhirockzz do you think it would be possible to add e2d tests for Redis Streams Scaler?
> 
> https://github.com/kedacore/keda/tree/master/tests#adding-tests

will try my best @zroubalik :) let me look into this

**Comment by zroubalik** [comment]
@abhirockzz just FYI, similar tests for RabbitMQ were just added, so you can check them out: https://github.com/kedacore/keda/pull/810

**Comment by abhirockzz** [comment]
> @abhirockzz just FYI, similar tests for RabbitMQ were just added, so you can check them out: #810

Thanks! I am not familiar with TS, so an existing impl should be helpful

**Comment by zroubalik** [comment]
@abhirockzz any update on this please? Or do you need any help?

**Comment by abhirockzz** [comment]
> @abhirockzz any update on this please? Or do you need any help?

sorry for the delay. I am working on this and will keep you posted

**Comment by zroubalik** [comment]
@abhirockzz no worries, I was just concerned whether you need some help. Thanks!

**Comment by zroubalik** [comment]
@idvoretskyi @ahmelsayed FOSSA failed here for missing FOSSA API key again? 🤷‍♂️

**Comment by idvoretskyi** [comment]
@zroubalik the same issue, I assume. The secrets are not passed to the PR from fork.

**Comment by zroubalik** [comment]
@idvoretskyi so we should do something about this, failing checks in PR are no ideal. How is the FOSSA done in other projects?

**Comment by idvoretskyi** [comment]
Ref on the FOSSA check - https://github.com/kedacore/keda/issues/808#issuecomment-642562581

**Pull request merged**
