### PR TITLE
Backport fixes to release 2.8

### LINKED ISSUE #4132: Release v2.8.2
Due to the reduced k8s versions supported for KEDA v2.9, we have decided to do an exceptional release for v2.8, back porting all the fixes and CVEs we have already solved.

This issue will track all the needed PR for being back ported:

| Merged at			  | Number | SHA									 | Back ported? |
|----------------------|------|------------------------------------------|----|
| 2022-09-27T06:11:08Z | #3693 | 4c19b384ba4b4e25ab05bcf599316a36ae865b1a |  Yes  |
| 2022-10-10T11:13:44Z | #3694 | 322ff425f2ab64b437b081870e33febc7d929497 |  Yes  |
| 2022-11-04T14:58:08Z | #3762 | 7af095399587e5266cf5b0a6f5bae027c7f40f96 |  Yes  |
| 2022-11-09T07:51:30Z | #3809 | 971ab94858880d7f9b0c4ae9a38d757e640b2618 |  Yes  |
| 2022-12-02T08:06:05Z | #3946 | a489ca7cd18c8e99067587ce712287736821b83f |  Yes  |
| 2022-12-05T17:22:48Z | #3788 | d5f33499cf33cf7225442ba9f48dd4a10856b6d9 |  Yes  |
| 2022-12-07T14:20:21Z | #3599 | 5953f7b0a0616583afd94b9a376596a59fac4192 |  Yes  |
| 2022-12-08T16:47:41Z | #3954 | 455eab32135d95668305e07957c79580471b2c50 |  Yes  |
| 2022-12-09T10:42:37Z | #3989 | 3e40fc6533328ecc2a23c8905694cc44d9c237a3 |  Yes  |
| 2022-12-15T09:38:52Z | #4012 | 06f6f7d444a1ea6ed66b350bdad5be20f319462c |  WONT FIX  |
| 2022-12-16T10:18:26Z | #4006 | 6c49e261865dbcddc00c2e37e908628b2b9e7c42 |  WONT FIX  |
| 2022-12-24T11:56:14Z | #4039 | b7607fcc1809d066cb280261994481455fefaf9b |  WONT FIX  |

Additionally, we need to solve this issue during the release, fixing the v2.8 helm chart

- [ ] https://github.com/kedacore/keda/issues/4126

### PR DESCRIPTION
**Pull request by pedro-stanaka**
I am backporting a list of fixes to the release 2.8, so we can tag and release a patch version 2.8.2.

Relates to https://github.com/kedacore/keda/issues/4132

### Checklist

- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [ ] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [ ] Tests have been added
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4132

### CODE REVIEW

**Comment by zroubalik** [comment]
@pedro-stanaka could you please run `make clientset-generate` on this branch and make a new commit containing this change?

**Comment by zroubalik** [comment]
oh I see, there's an itendation problem in those files caused by different go versions and operating systems :( 🤯  It has been resolved recently. So we should hack this:

Could you please copy these files from `release/v2.8 branch` to your local branch and commit them into this PR?
Here are direct links to correctly intended files:
https://github.com/kedacore/keda/blob/12783c1340a13ba6776d1d6a64127d88e7828aab/pkg/generated/clientset/versioned/fake/register.go
https://github.com/kedacore/keda/blob/12783c1340a13ba6776d1d6a64127d88e7828aab/pkg/generated/clientset/versioned/scheme/register.go

**Comment by pedro-stanaka** [comment]
> oh I see, there's an itendation problem in those files caused by different go versions and operating systems :( 🤯 It has been resolved recently. So we should hack this:
> 
> Could you please copy these files from `release/v2.8` branch to your local branch and commit them into this PR? Here are direct links to correctly intended files: https://github.com/kedacore/keda/blob/12783c1340a13ba6776d1d6a64127d88e7828aab/pkg/generated/clientset/versioned/fake/register.go https://github.com/kedacore/keda/blob/12783c1340a13ba6776d1d6a64127d88e7828aab/pkg/generated/clientset/versioned/scheme/register.go

CI seems happier now, I forgot which step failed before, but I think it passed now.

**Comment by zroubalik** [comment]
@pedro-stanaka could you please enforce update of the packages identified in the check: https://github.com/kedacore/keda/actions/runs/3947682302/jobs/6756786914 ?

**Comment by pedro-stanaka** [comment]
> 

Sure thing. Let me try it.

**Comment by zroubalik** [comment]
@pedro-stanaka it is better to do it through replace directive (at least for the go net package) https://github.com/kedacore/keda/blob/a25f1a4b951b52f6f76f0b1aaa96e509fce466fb/go.mod#L92

**Comment by pedro-stanaka** [comment]
Hum this CVE: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMAWSAWSSDKGOSERVICES3S3CRYPTO-598253 
sounds like a false-positive. We are on 1.44 and it says it should be resolved in 1.34+.

**Comment by zroubalik** [comment]
@JorTurFer ^

**Comment by zroubalik** [comment]
it's most likely configuration error on our side

**Comment by JorTurFer** [comment]
I have to check because there are multiple things failing...
You can ignore these missing checks, it's normal because they are checks introduced in main branch
image

WRT e2e test, it's something that it's failing, and I have an idea (I think it's related with the migration to the new testing-infrastructure repo), I need to check it better.

Trivy check is still failing due to aws dep

**Comment by JorTurFer** [comment]
For solving e2e test, [this PR](https://github.com/kedacore/keda/pull/3753) is required. Let me cherry-pick it before and then rebase your branch

**Comment by JorTurFer** [comment]
> I can rebase as well, just let me know when you rebased your PR.

I have already merged the PR into `release/v2.8` branch, please rebase your branch from it

**Comment by JorTurFer** [comment]
predictkube e2e test is failing because this change is missing:
image

It's part from other PR because it started to fail suddenly, could you apply change those lines in your PR? I think it's the only thing left to start the release process :)

**Comment by JorTurFer** [comment]
Thanks for your help @pedro-stanaka

**Pull request merged**
