### PR TITLE
Add complex scaling logic for custom formula & external scaling via grpc server

### LINKED ISSUE #2440: Support custom formula for multiple metrics
### Proposal

- KEDA metrics server knows how to get multiple metrics from various sources.
- Currently, the desired size computation works for each scaler individually and the final value is decided according to MAX.
- In real-world - sometimes you need to make decisions with more complex logic.

I think that a "Composed Scaler" that allows to put in a simple formula that references multiple other metrics - can be super useful.

This would make Keda a powerful tool not only for collecting external metrics but also for making smart decisions based on multiple conditions.

([discussed original here](https://github.com/kedacore/keda/discussions/2431))

### Use-Case

Here's a real-world problem: I have a backend process that consumes "write" tasks from a queue and persists them to DB. My DB has a single writer node that is CPU-bound. A task may implicit varying load on the CPU (depending on the content of the write).

I have 2 relevant metrics to determine the replica count:
```
q := queue-length
cpu := DB-writer CPU utilization
```

Composed metric formula: `ceil((1-cpu) * q)` can promise that replicas would grow if the queue is high but avoid growing if CPU is loaded. Right now the only option for me to do it is to create my own service that exposes that metric.

### Anything else?

In the [original discussion](https://github.com/kedacore/keda/discussions/2431), we started talking about how the ScaledObject spec would look like in the custom logic case.

First I suggested this:
```yaml
triggers:
  - type: composed
    metadata:
      metrics:
        q_length: 
          type: aws-cloudwatch
          metadata:
            namespace: AWS/SQS
            ... # SQS length
        cpu_util:
          type: aws-cloudwatch
          metadata:
            namespace: AWS/Neptune
            ... # neptune writer CPU
      formula: "ceil((1 - $cpu_util) * $q_length)"
      targetMetricValue: "5"
      minMetricValue: "0"

```

then @zroubalik suggested this (better IMO):
```yaml
scaledObject.spec:
  ...
  mutlipleTriggersCalculation:    ### we should find a better name for this probably
      formula: "ceil((1 - $cpu_util) * $q_length)"
      targetMetricValue: "5"
      minMetricValue: "0"
  triggers:
    - type: aws-cloudwatch
       name: q_length     ### name added here
       metadata:
            namespace: AWS/SQS
            ... # SQS length
    - type: aws-cloudwatch
       name: cpu_util       ### name added here
       metadata:
            namespace: AWS/Neptune
            ... # neptune writer CPU
```

Finally, it's valuable to read @tomkerkhove 's [comment](https://github.com/kedacore/keda/discussions/2431#discussioncomment-1905982) about it.

### LINKED ISSUE #3567: Provide support for using AND logic for triggers
### Proposal

Allows end-users to scale out/in when the queue depth is high enough, and it is within a given time window, for example

### Use-Case

Provide support for using AND logic for triggers so that it scales when all triggers meet the criteria

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gauron99**
# UPDATE
Ive separated 2 functions in this PR into 2 and am keeping this as draft only for references as references
- new feat: formula [here](https://github.com/kedacore/keda/pull/4821)
- new feat: grpc servers as external calculations [here](https://github.com/kedacore/keda/pull/4859)
### Summary
adds new structure in SO that describes how to modify/alter fetched metrics. User can describe new `target` to scale on within this structure. IF this is defined, new `composite-scaler-metric` is created and passed on to HPA (`hpa.go`). HPA will ask for only this one metric and internally all external metrics will be fetched and used in `scale_handler.go`.
2 new features within this struct are `formula` and `external calculations` (user-defined grpc server).
- formula -> define formula with trigger names to modify metrics how ever you want using https://github.com/antonmedv/expr. Value returned from this will be attached to `composite-scaler` metric and returned as a final metric.
- external calc -> user can defined grpc server and call it via url. New .proto file was created to match this. KEDA (as client) will try to connect to this server and pass its metrics via method `Calculate`.

one can chain multiple external calcs together when they define multiple. (its an array of grpc servers)

**Order of execution**: Fetch all external metrics from triggers -> external calcs execute in order (from top to bottom) as given in SO -> apply formula (you can use last name of grpc server if you want to manipulate its returned metric further)

### Checklist
- [x] implement timeout & fallback for EC (e2e test)
- [x] create more test scenarios ( unit tests fallback)
- [x] create more test scenarios ( unit tests scale_handler)
- [x] admission webhook checkers
- [x]  security for grpc connection
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is done to update the documentation on ([docu-link](https://github.com/kedacore/keda-docs/pull/1189)) 
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #3567
Fixes #2440

### CODE REVIEW

**Comment by carlreid** [comment]
Hey, first of all, not to push you at all regarding the work on this PR. I am wondering what kind of priority these changes have, so I can see if I should wait for this to be released to use `AND` logic in KEDA, or look into some other potential solutions in the short term

**Comment by gauron99** [comment]
@carlreid hello, Im working on this now daily. All functions are implemented, working on tests and some other specifics now to comply with PR standards. Im expecting to finish in few days then add few days for reviews etc.

**Comment by carlreid** [comment]
Hey @gauron99, thanks for the update! Then it makes sense for me to pause working on changes my side and use the great work you're doing here 👍

**Review by gauron99 — COMMENTED** [review]
Sorry for this big PR, shouldve separated grpc servers into its own PR. Ive made some self-reviews and what i thought were important points

**Review by tomkerkhove — COMMENTED** [review]
I think it would have been nice to have a design review on the proposed configuration/approach first, if I may be frank.

Given the big addition/difference, I'd like to review this in depth but am on holiday for 2.5w now so might be delayed.

This feature can be powerful, but needs to be accessible as well.

**Comment by gauron99** [comment]
marked this PR draft to serve as a unity of 2 new functionalities but will separate into 2 PRs

**Comment by zroubalik** [comment]
Closing in favor 2 separate PRs

**Pull request closed without merging**
