### PR TITLE
Fix GCP PodIdentity not considered with WorkloadIdentity

### PR DESCRIPTION
**Pull request by juldrixx**
_Provide a description of what has been changed_

### Checklist

- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

https://github.com/kedacore/keda/issues/5011

Relates to #

### CODE REVIEW

**Comment by JorTurFer** [comment]
Hello,
The changes look good, but there is a test failing because that [function you have changed is covered by a test](https://github.com/kedacore/keda/blob/main/pkg/scaling/resolver/scale_resolvers_test.go#L240). You have to add `expectedPodIdentity: kedav1alpha1.AuthPodIdentity{Provider: kedav1alpha1.PodIdentityProviderNone},` to the test cases where the expectdPodIdentity isn't set.
About how to cover this PR with a test for the future, there are 2 options actually:
- Adding a test case that executes `ResolveAuthRefAndPodIdentity` and validates the output in [this file](https://github.com/kedacore/keda/blob/main/pkg/scaling/resolver/scale_resolvers_test.go)
- Covering it with e2e test, adding another test case to the secret-provider folder using podIdentity with a CRD, such as Argo Rollouts. You can do it mixing any podIdentity test (for example [this](https://github.com/kedacore/keda/blob/main/tests/secret-providers/azure_workload_identity_user_assigned/azure_workload_identity_user_assigned_test.go)) with the custom resource test (like [this](https://github.com/kedacore/keda/blob/main/tests/internals/subresource_scale/subresource_scale_test.go)). Basically, you can use the workload definition from the second-one, with the ScaledObject + process from the first one

**Comment by sammaxwellxyz** [comment]
Hi @JorTurFer 

given this is a fix, to merge this PR, is the extra e2e required or a nice to have?

@juldrixx are you still working on this? I may be able to fork and fix the failing test but wouldn't be able to add the e2e in the short term

Cheers both

**Comment by juldrixx** [comment]
> Hi @JorTurFer
> 
> given this is a fix, to merge this PR, is the extra e2e required or a nice to have?
> 
> @juldrixx are you still working on this? I may be able to fork and fix the failing test but wouldn't be able to add the e2e in the short term
> 
> Cheers both

I'm currently rather busy, but I might have some time next week to look at the test part. But if you want to do it before then, no worries you can.

**Comment by JorTurFer** [comment]
> given this is a fix, to merge this PR, is the extra e2e required or a nice to have?

Any kind of test is required for preventing regressions and in this case, I'd say that e2e test is the easiest way because that code it's quite coupled and there isn't any other test already done that you can use as base for having all the test setup ready, you'd need to prepare all the unit test setup, which probably requires more time than writing an e2e test (but it's not mandatory an e2e test)

**Comment by zroubalik** [comment]
Replaced by: https://github.com/kedacore/keda/pull/5255

**Pull request closed without merging**
