### PR TITLE
feat: add logic for prometheus scaler X-Scope-OrgID header

### LINKED ISSUE #2667: Support for X-Scope-OrgID header in Prometheus scaler
### Proposal

Need to add support for `X-Scope-OrgID` header as part of the query to a multi tenant cortex (prometheus metrics), since it's not possible to get a response without it when multi tenancy is enabled.

### Use-Case

We're using scalers from type prometheus, and recently moved to a multi tenant cortex to serve metrics from multiple different prometheus instances in different clusters. To support multi tenancy, we need to provide `X-Scope-OrgID` header for cortex to know which prometheus data to return.
We need to pass this header in keda's prometheus scaler as well if we want to use cortex endpoint (which we do).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xoanmm**
Signed-off-by: Xoán Mallón <xoanmallon@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs/pull/714
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #2667

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by aberenshtein** [comment]
when will this be released?

**Comment by JorTurFer** [comment]
Next release will be on May @aberenshtein

**Pull request merged**
