### PR TITLE
Handle password value correctly; add tests.

### LINKED ISSUE #1938: Username used in place of password in IBM MQ scaler
It looks like the username variable "val" is used instead of the password variable "value" in the IBM MQ scaler, which makes authentication fail in many (most?) cases.

https://github.com/kedacore/keda/blob/a84c5cc1534bec5a9bc5e027fcebedd3673ac3d3/pkg/scalers/ibmmq_scaler.go#L140

passwordFromEnv would work as expected.

### PR DESCRIPTION
**Pull request by tdolby-at-uk-ibm-com**
Signed-off-by: Trevor Dolby <tdolby@uk.ibm.com>

Use passwords from secrets correctly.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [N/A] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [N/A] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated

Fixes #1938

### CODE REVIEW

**Comment by tdolby-at-uk-ibm-com** [comment]
Seemed a bit too trivial a change for me to update the Changelog, but I can do so if it would help.

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!

**Comment by zroubalik** [comment]
> Seemed a bit too trivial a change for me to update the Changelog, but I can do so if it would help.

Yeah it's trivial, but it is fixing a bug, so I prefer to have it in the Changelog, thanks!

**Comment by tdolby-at-uk-ibm-com** [comment]
Changelog update

**Pull request merged**
