### PR TITLE
enable golint: unparam,varcheck

### PR DESCRIPTION
**Pull request by mdeggies**
Signed-off-by: Michele <mdeggies@gmail.com>

Enables golint for unparam and varcheck. I don't believe this will require any downstream docs changes, and tests are still passing, but let me know if there's any other changes needed!

### Checklist

- [ X ] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Fixes # https://github.com/kedacore/keda/issues/1158

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by zroubalik** [comment]
@mdeggies could you please resolve the conflict in redis_scaler.go?

**Comment by mdeggies** [comment]
Hey @zroubalik, this should be good to go now!

**Review by ahmelsayed — APPROVED** [review]

**Comment by ahmelsayed** [comment]
Thanks @mdeggies!

**Pull request merged**
