### PR TITLE
fix: Use pinned version for all the pending tasks

### PR DESCRIPTION
**Pull request by JorTurFer**
I'm fixing semgrep detections and this is one of them as not using versions pinned by commit sha is vulnerable to tampering

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Comment by JorTurFer** [comment]
I skip the e2e tests because these changes won't apply until they are merged, so doesn't make sense to execute the e2e suite

**Comment by rickbrouwer** [comment]
Is it possible to also fix the token-permission (like #6088)?

**Comment by JorTurFer** [comment]
> Is it possible to also fix the token-permission (like #6088)?

let me update the PR, nice catch!

**Review by wozniakjan — APPROVED** [review]

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
