### PR TITLE
feat: introduce `activationThreshold` for Graphite Scaler

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs/pull/817

Fixes #

Relates to https://github.com/kedacore/keda/issues/2800

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
have you changed all the metadata keys intentionally? From `grap***` to `graphite**`

**Comment by zroubalik** [comment]
> have you changed all the metadata keys intentionally? From `grap***` to `graphite**`

Yeah, to give more clarity to those fields as they are shared across to whole package.

**Comment by JorTurFer** [comment]
> Yeah, to give more clarity to those fields as they are shared across to whole package.

I didn't notice that this are constants, not the keys their self 🤦 ignore me xD

**Review by JorTurFer — APPROVED** [review]

**Pull request merged**
