### PR TITLE
fix scale with windows nodes in cluster issue 4908

### PR DESCRIPTION
**Pull request by Doofus100500**
Add 

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #
https://github.com/kedacore/keda/issues/4908

### CODE REVIEW

**Comment by Wolfe1** [comment]
In terms of simply ignoring any windows nodes I think this would do the trick. a few things that i think you would need before this got merged:

- [ ] Add to the unit tests for scenarios with windows nodes present
- [ ] Add End 2 end tests with windows nodes present
- [ ] Update documentation to show that windows nodes are currently ignored

**Review by zroubalik — COMMENTED** [review]
What would happen if user would like to scale windows nodes?

**Comment by Wolfe1** [comment]
> What would happen if user would like to scale windows nodes?

With this implementation, it would not work.

Looking at the code again, we already say what platform we wish to scale from in the Keda settings. Now that we pull the platformName from the grid sessions I would think we just use that to make sure it matches the expected platformName in our Keda settings rather than just completely excluding windows.

**Comment by Doofus100500** [comment]
In my case, it’s enough to simply exclude Windows. This is because Windows nodes live in a VM. However, even before my PR, the user wouldn’t have been able to scale Windows nodes. I don’t quite understand which settings you are referring to, as I am not that deeply involved in your project.

**Comment by Doofus100500** [comment]
> Now that we pull the platformName from the grid sessions I would think we just use that to make sure it matches the expected platformName in our Keda settings rather than just completely excluding windows.

@Wolfe1 Like that?

**Comment by Doofus100500** [comment]
@zroubalik @Wolfe1 Hi, is there a chance this PR will be accepted?

**Review by zroubalik — COMMENTED** [review]
@Doofus100500 could you please keep here only relevant commits?

**Pull request closed without merging**
