### PR TITLE
add ScaledJob's label to its job

### LINKED ISSUE #1311: Support metadata labels in ScaledJob template
in version 2.0 `metadata` portion of ScaledJob `template` is ignored so it is impossible to setup a label for job to be created

### Use-Case

To support managed identity in AKS, a label "aadpodidbinding" has to be added to the object that needs pods to be running under managed identity. 

To use ScaledJob to create pods that run under managed identity, ScaledJob should support `metadata` section when defining job template.

 

### Specification

Allow adding labels to pod template using `metadata` section

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {scaled-job-name}
spec:
  jobTargetRef:
    template:
       metadata:
          labels:
            aadpodidbinding: "myidentity"
      spec:
         ...
```

### PR DESCRIPTION
**Pull request by mosesyou**
Signed-off-by: mosesyou <mosesyou1994@gmail.com>

This PR is about to add ScaledJob's label to its job.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [x] Changelog has been updated

Fixes #1311

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by zroubalik** [comment]
@mosesyou could you please add this feature to the Changelog? to the Improvements section in Unreleased, thanks!

**Comment by mosesyou** [comment]
> @mosesyou could you please add this feature to the Changelog? to the Improvements section in Unreleased, thanks!

Sure

**Comment by erichorwath** [comment]
@zroubalik I have big interest in this PR and tested it, here are my findings:

1. With this PR labels can be added to the "jobs" but not to the "pods" created by the job (see pictures). Was this intended?
2. Annotations are still not working :( This would be needed to disable istio, see here: https://github.com/istio/istio/issues/11659#issuecomment-625263887 (this annotation is needed in the pod spec but not in the job spec)

image
image

**Comment by zroubalik** [comment]
@ericbottard sad to hear that. Thanks for the confirmation! We should fix this. Could you please open an issue with the details. And are you willing to contribute this? Or @mosesyou do you want to take a look?

**Comment by erichorwath** [comment]
@zroubalik Can you maybe just reopen https://github.com/kedacore/keda/issues/1311 since the issue described there still exists?

**Comment by ycabrer** [comment]
Hi, I would like to help if I can. 

I took a look at the code and it seems to do a deep copy of the scaledjob spec.template to job template.spec on creation.

If we want a label or annotation to appear in the pod, wouldn't we would add it in the scaledjob spec.template metadata?

@erichorwath would you provide a snip of your scaledjob? To help me better understand the issue.

**Comment by erichorwath** [comment]
@ycabrer sure, the interesting part is here spec.template.metadata part. It would be great to be able to set this in an scaledJob yaml (->  spec.jobTargetRef.template.spec.metadata).

```
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-job
spec:
  activeDeadlineSeconds: 96000
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        my-workload: app
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: redis-worker
        env: []
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 5747
          name: status
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: worker-data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 259200
      volumes:
      - emptyDir: {}
        name: worker-data
```

**Comment by mosesyou** [comment]
https://github.com/kedacore/keda/blob/af5254dd2bf8f2b70eb73ddc6428b4fb01dc2fb2/pkg/scaling/executor/scale_jobs.go#L83-L90

I'm not sure,  `Spec: *scaledJob.Spec.JobTargetRef.DeepCopy(), ` Doesn't this line of code mean copy ScaledJob's Job Spec including PodTemplate to Job? So why we can't pass labels or annotations from ScaledJob's JobSpec{PodTemplate{ObjectMeta}} to Job{PodTemplate{ObjectMeta}}?

**Comment by julienperignon** [comment]
Hi there

I know this has been merged in and apparently works for labels but we still cannot add annotations on the PodSpec (to disable istio injection for example). Do we have a rough idea of when this feature will be brought back in Keda ?

Cheers

**Comment by tomkerkhove** [comment]
@julienperignon I've opened https://github.com/kedacore/keda/issues/1627 for it.

**Pull request merged**
