### PR TITLE
Feature ActiveMQ Artemis scaler

### PR DESCRIPTION
**Pull request by balchua**
_Added `artemis_scaler.go` and modified `scale_handler.go`_

This PR adds a new ActiveMQ Artemis Scaler, this feature will finally support Java based applications using Java Messaging Service Broker like ActiveMQ Artemis
### Checklist

- [X] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [X] Commits are signed with Developer Certificate of Origin (DCO)
- [X] Tests have been added

### CODE REVIEW

**Comment by balchua** [comment]
Sorry guys accidentally closes the previous PR.  This is the good one now. :)

**Comment by ahmelsayed** [comment]
qq about naming. Is artemis mainly for queues or are there other potential event sources there that qualifying the scaler as `artemis-queue` would make sense.

**Comment by balchua** [comment]
Aaaa true artemis supports queue and topics.  `artemis-queue` sounds less ambiguous. Which is good.

**Comment by zroubalik** [comment]
> Aaaa true artemis supports queue and topics. `artemis-queue` sounds less ambiguous. Which is good.

@balchua do you plan to include this change?

**Comment by balchua** [comment]
Yes i will. Tomorrow. Don't have too much time on weekdays. 😊 Releasing 1.5 soon?

**Comment by zroubalik** [comment]
@balchua thanks! Take your time, no need to rush :)  Yeah, we would like to release 1.5 at the end of the next week, but that's not a strict date.

**Comment by balchua** [comment]
I have updated the PR as well as the docs https://github.com/kedacore/keda-docs/pull/203
Thanks for reviewing.

**Comment by tomkerkhove** [comment]
Docs are great, thanks!

**Pull request merged**
