### PR TITLE
fix: apply rule trailofbits.go.questionable-assignment.questionable-assignment

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

This PR solves some cases where we use assigned values even we have an error

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to https://github.com/kedacore/keda/issues/3961

### CODE REVIEW

**Comment by zroubalik** [comment]
> /run-e2e **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/3648499826)

@JorTurFer I am gonna cancel this one, need to proceed with other PRs, then we can follow up with this, Sorry

**Comment by JorTurFer** [comment]
Sure, no problem, this code doesn't introduce any urgent change. I'll trigger the e2e tests after release

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
