### PR TITLE
Migrate to GitHub Issue Forms

### PR DESCRIPTION
**Pull request by tomkerkhove**
Migrate to GitHub Issue Forms which gives better UX around opening issues.

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@zroubalik Let me merge it please, in case it's messed up I can fix it asap then 😅

**Review by ahmelsayed — APPROVED** [review]

**Review by zroubalik — APPROVED** [review]
LGTM

@tomkerkhove I can see that your commit includes some changes that are already merged?  🤷‍♂️ Could you try to rebase please?

**Review by turbaszek — APPROVED** [review]

**Comment by turbaszek** [comment]
@tomkerkhove this look nice! Is this feature in GA?

**Comment by tomkerkhove** [comment]
Nope, not yet

**Pull request merged**
