### PR TITLE
fix: Added support for vault kv-v1 (#2645)

### LINKED ISSUE #2645: Using Hashicorp Vault secrets with TriggerAuthentication results in unable to convert Vault Data value error
### Report

Configuring a `TriggerAuthentication` object to use `hashiCorpVault` to get the values for various parameters on a ScaledObject.  The scale_resolvers returns `unable to convert Vault Data value`

### Expected Behavior

The result of the `queryKey` to be used for the `new-relic` scaler

### Actual Behavior

The following error related to the `new-relic` scaler

```
keda-operator-ddd8757f-9bnnv keda-operator 1.6449390228145654e+09	ERROR	scalehandler	Error trying to convert Data secret vaule	{"type": "ScaledObject", "namespace": "keda-test", "name": "newrelic-ta-scaledobject", "error": "unable to convert Vault Data value"}  
```

### Steps to Reproduce the Problem

1. Create kind cluster `kind create cluster --name keda-test`
2. `kubectl create namespace keda`
3. `helm install keda kedacore/keda --namespace keda`
4. Setup vault server: `vault server -dev -dev-root-token-id="root" -dev-listen-address=0.0.0.0:8200 >> /dev/null &`
5. `export VAULT_ADDR='http://0.0.0.0:8200'`
6. `vault login root`
7. `export VAULT_SA_NAME=$(kubectl get sa keda-operator -n keda --output jsonpath="{.secrets[*]['name']}")`
8. `export SA_JWT_TOKEN=$(kubectl get secret -n keda $VAULT_SA_NAME --output 'go-template={{ .data.token }}' | base64 --decode)`
9. `export SA_CA_CRT=$(kubectl config view --raw --minify --flatten --output 'jsonpath={.clusters[].cluster.certificate-authority-data}' | base64 --decode)`
10. `export K8S_HOST=$(kubectl config view --raw --minify --flatten --output 'jsonpath={.clusters[].cluster.server}')`
11. `vault auth enable kubernetes`
12. Write vault config
```
vault write auth/kubernetes/config \
        token_reviewer_jwt="$SA_JWT_TOKEN" \
        kubernetes_host="$K8S_HOST" \
        kubernetes_ca_cert="$SA_CA_CRT" \
        issuer="https://kubernetes.default.svc.cluster.local"

vault write auth/kubernetes/role/keda \
        bound_service_account_names=keda-operator \
        bound_service_account_namespaces=keda \
        policies=keda \
        ttl=24h
```
13. Create the TriggerAuthentication object `triggerauthentication.yaml`
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-vault
spec:
  hashiCorpVault:
    address: http://192.168.0.4:8200
    authentication: kubernetes
    role: keda
    mount: kubernetes
    credential:
      serviceAccount: /var/run/secrets/kubernetes.io/serviceaccount/token
    secrets:
    - parameter: queryKey
      key: keda-nr-key
      path: /kv-v1/keda/secret
```
14. Create ScaledObject `scaledobject.yaml`
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: newrelic-ta-scaledobject
spec:
  scaleTargetRef:
    name: deployment-nr-ta
  minReplicaCount: 1
  maxReplicaCount: 50
  cooldownPeriod: 5
  idleReplicaCount: 0
  triggers:
  - type: new-relic
    metadata:
      account: '1234567'
      region: "US"
      noDataError: "true"
      nrql: "SELECT latest(allocatablePods) from K8sNodeSample WHERE clusterName = 'cluster-name'"
      threshold: '10'
    authenticationRef:
     name: keda-trigger-auth-vault
```
15. Create deployment object `deployment.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nr-ta
spec:
  replicas: 0
  selector:
    matchLabels:
      app: deployment-nr-ta
  template:
    metadata:
      labels:
        app: deployment-nr-ta
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            name: deployment-nr-ta
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            name: deployment-nr-ta
      terminationGracePeriodSeconds: 0
      containers:
        - name: pause-deployment-nr-ta
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 250m
              memory: 250m
```
16. Create namespace `kubectl create ns keda-test`
17. Apply deployment `kubectl apply -f deployment.yaml -n keda-test`
18. Apply TriggerAuthentication object `kubectl apply -f triggerauthentication.yaml -n keda-test`
19. Apply ScaledObject `kubectl apply -f scaledobject.yaml -n keda-test`
20. Review the logs using `stern` or `kubectl logs`

### Logs from KEDA operator

```
keda-operator-ddd8757f-9bnnv keda-operator 1.6449390227989428e+09	INFO	controller.scaledobject	Creating a new HPA	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "newrelic-ta-scaledobject", "namespace": "keda-test", "HPA.Namespace": "keda-test", "HPA.Name": "keda-hpa-newrelic-ta-scaledobject"}
keda-operator-ddd8757f-9bnnv keda-operator 1.6449390228145654e+09	ERROR	scalehandler	Error trying to convert Data secret vaule	{"type": "ScaledObject", "namespace": "keda-test", "name": "newrelic-ta-scaledobject", "error": "unable to convert Vault Data value"}    

```

### KEDA Version

2.6.0

### Kubernetes Version

v1.21.1

### Platform

Other

### Scaler Details

- new-relic and rabbitmq

### Anything else?

Create Vault v1 secret `vault secrets enable -path="kv-v1" -description="Test V1" kv`
Added NR key `vault kv put kv-v1/keda/secret keda-nr-key=NRAK-12345678901234`
Also tested using a v2 and got same error.

### PR DESCRIPTION
**Pull request by chaunceyt**
Signed-off-by: Chauncey Thorn <chaunceyt@gmail.com>

Adding support for HashiCorp Key-Value v1 secrets backend. Also fixed a typo in log output.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #2645

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
LGTM!
Thanks for the fix and the research you have done ❤️ 
Could you update the changelog?

**Review by zroubalik — COMMENTED** [review]
Thanks, do you think you can add a simple unit test for this?

**Comment by chaunceyt** [comment]
I'll work to get the changelog update and unit test in. Hopefully I'll be able to get it done this weekend.

@zroubalik I was looking for the test for the v2 secret engine. Can you point me to that so I can extend that test?

Thanks

**Comment by zroubalik** [comment]
> I'll work to get the changelog update and unit test in. Hopefully I'll be able to get it done this weekend.
> 
> @zroubalik I was looking for the test for the v2 secret engine. Can you point me to that so I can extend that test?
> 
> Thanks

Unfortunately there isn't any specific tests for this :(

**Comment by zroubalik** [comment]
@chaunceyt we have added HashiCorp E2E tests, do you think you can extend them to cover kv-v1? https://github.com/kedacore/keda/pull/2849

**Comment by chaunceyt** [comment]
@zroubalik Yes following the pattern in `tests/scalers/postgresql-hashicorp-vault.test.ts` I can extend to cover `kv-v1`.  This pattern seems less work that trying to add it to `scale_resolvers_test.go`

Thanks for pointing me to this.

**Comment by JorTurFer** [comment]
one thing @chaunceyt 
Please take into account that if you create another test file, they can run in parallel sometimes. I said because I had errors installing 2 instances of vault because Clusterroles, maybe the parameters need to be updated in any way

**Comment by zroubalik** [comment]
@chaunceyt any update on thia please? We are going to release 2.7.0 soon (May 7). So would be great if we can include this as well.

**Comment by chaunceyt** [comment]
@zroubalik 
Currently on vacation, will return beginning of the month and will work to get the test written and submitted. Sorry for the long delay been really busy.

**Comment by zroubalik** [comment]
@chaunceyt just FYI we plan to do the release May 5

**Comment by tomkerkhove** [comment]
@chaunceyt Any thought if we can close this PR soon? We are planning to release in 2 weeks.

**Comment by zroubalik** [comment]
@chaunceyt ping :)

**Comment by JorTurFer** [comment]
You will need to rebase your PR too

**Comment by chaunceyt** [comment]
Hi, sorry for lack of response and delay getting back to this.  I am going to close the PR.  I accidentally noticed the lack of v1 support using incorrect path for v2 setup. After fixing that the Vault integration works as desired without the change.

I'm going to speculate that very few if anyone is using v1 for Vault these days.

Thanks for the patience shown due to my lack of response.
Keep up the good work.

**Pull request closed without merging**
