### PR TITLE
`beta.kubernetes.io/os` nodeSelector is deprecated

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

```
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
```

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
LGTM!

**Comment by tomkerkhove** [comment]
@zroubalik Would you mind sending a PR to our Helm chart as well or prefer me to pick this up? If so, feel free to open a quick issue.

**Comment by zroubalik** [comment]
@tomkerkhove I haven't found this property in charts. So it should be ok.

**Comment by tomkerkhove** [comment]
Created https://github.com/kedacore/charts/issues/200 since we should enforce Linux

**Pull request merged**
