### PR TITLE
Optionally exclude Unacknowledged message counts from RabbitMQ QueueLength

### PR DESCRIPTION
**Pull request by sl1pm4t**
This change adds a new parameter to the RabbitMQ scaler (`excludeUnacknowledged`) that optionally modifies the scaler behaviour to return only `Ready` messages in the QueueLength counts. 
Only applies to hosts using the `http` protocol which currently (before this PR) return message counts that include both `Ready` & `Unacknowledged` messages.
When enabled, this also makes the `http` protocol mode consistent with the `amqp` protocol that only returns `Ready` message counts.

### CODE REVIEW

**Comment by sl1pm4t** [comment]
Looks like the changes I made to `parseRabbitMQMetadata()` have tipped it over the complexity threshold and is now failing the golangci lint. 
How would you like this to be handled? Split up the func or add an override?

**Comment by JorTurFer** [comment]
> How would you like this to be handled? Split up the func or add an override?

Maybe we should create a function for http protocol parsing but it's true that rabbit metadata is becoming huge

**Comment by sl1pm4t** [comment]
@JorTurFer - I extracted the http metadata parsing to a new func.

**Review by JorTurFer — APPROVED** [review]
LGTM! 
Thanks for his improvement! 😄 
Let's wait till e2e tests finish before merging it

**Review by JorTurFer — APPROVED** [review]
LGTM! 
Thanks for his improvement! 😄 
Let's wait till e2e tests finish before merging it

**Comment by tomkerkhove** [comment]
They passed! Thanks for this @sl1pm4t!

**Pull request merged**
