### PR TITLE
1114 Updated .devcontainer dockerfile, added pip and pre-commit in de…

### PR DESCRIPTION
**Pull request by kashifsoofi**
…v container

Signed-off-by: Kashif Jamal Soofi <kashif.soofi+git@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

### CODE REVIEW

**Comment by kashifsoofi** [comment]
I believe that is the only change needed, please let me know if there is anything else required.

**Comment by zroubalik** [comment]
Thanks!

I don't use devcontainer, so don't have hands on experience. But the Operator SDK version should be set to 1.0.0

And I am not sure about `revive` @turbaszek ?

**Comment by turbaszek** [comment]
> I don't use devcontainer, so don't have hands on experience.

Me too but it looks interesting

> And I am not sure about `revive` @turbaszek ?

On CI we do:
https://github.com/kedacore/keda/blob/d2ab1ad3a7f1c1999446aece270fe0b7dbd87581/.github/workflows/pr-validation.yml#L44-L45

**Comment by kashifsoofi** [comment]
> Thanks!
> 
> I don't use devcontainer, so don't have hands on experience. But the Operator SDK version should be set to 1.0.0
> 
> And I am not sure about `revive` @turbaszek ?

I was not too sure about operator SDK version will update that. In my last PR i used it everything worked (build, format, lint) except the pre-commit so i installed that here. So I guess it should be fine unless someone using dev container more extensively can suggest some updates.

**Review by zroubalik — APPROVED** [review]
Thanks!

**Pull request merged**
