### PR TITLE
Add SSL support to RabbitMQ Scaler

### PR DESCRIPTION
**Pull request by ansonauhk**
Signed-off-by: Anson Au <ansonau@gmail.com>

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Fixes # https://github.com/kedacore/keda/issues/967

### CODE REVIEW

**Comment by zroubalik** [comment]
@ansonauhk could you please fix DCO?

**Comment by ansonauhk** [comment]
> @ansonauhk could you please fix DCO?

Hey, just followed the instruction on fixing the DCO

**Comment by zroubalik** [comment]
Seems like your PR and commit is broken, contains multiple not related nad already merged changes. Could you please fix that?

**Comment by ansonauhk** [comment]
Sure. I will raise a new PR to make thing easier

**Pull request closed without merging**
