### PR TITLE
Add Bearer Auth for Metrics API scaler

### PR DESCRIPTION
**Pull request by JorTurFer**
Adds an authorization method named `bearer` for Metrics API scaler

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)* https://github.com/kedacore/keda-docs/pull/513
- [x] Changelog has been updated

Relates to https://github.com/kedacore/keda/issues/1081

### CODE REVIEW

**Comment by JorTurFer** [comment]
I'm not sure if it's better to create a new `AuthType` or reuse the existing [`BearerAuthType`](https://github.com/kedacore/keda/blob/main/pkg/scalers/authentication/authentication_types.go#L14)

Maybe `bearer` is a specific case of jwt but ... 🤔
any opinion @zroubalik @ahmelsayed ?

**Comment by ahmelsayed** [comment]
JWT would be a specific case, or format, of a bearer token, right? I'm assuming the value of `jwtToken` is expected to be `Bearer <jwt>` in this case, correct?

**Comment by tomkerkhove** [comment]
> JWT would be a specific case, or format, of a bearer token, right? I'm assuming the value of `jwtToken` is expected to be `Bearer <jwt>` in this case, correct?

I'd say that the JWT would just be the JWT token and we add the bearer for you, no?

**Comment by JorTurFer** [comment]
I'm not an expert here, but [I think that JWT is more like the format and Bearer is one use case of the format](https://stackoverflow.com/a/40375722), but as I said, I'm not an expert :( 
I will try to get some help from an expert

**Comment by tomkerkhove** [comment]
> I'd say that the JWT would just be the JWT token and we add the bearer for you, no?

This remark is purely from a user-perspective and making it simple/straight-forward - Not saying this is how JWT works

**Comment by JorTurFer** [comment]
Maybe the auth method should be named as `Bearer` instead JWT, we can simplify the process to the final user just placing the token, and we automatically add the `Authorization` header with the value `Bearer {given token}`

**Comment by zroubalik** [comment]
> Maybe the auth method should be named as `Bearer` instead JWT, we can simplify the process to the final user just placing the token, and we automatically add the `Authorization` header with the value `Bearer {given token}`
> This could be clearer than naming it JWT auth for a Bearer auth.
> WDTY?

I like this approach.

**Comment by JorTurFer** [comment]
I have just changed it @zroubalik :)
I think that it's ready for review

**Review by zroubalik — APPROVED** [review]
LGTM :)

**Review by ahmelsayed — APPROVED** [review]

**Comment by ahmelsayed** [comment]
@JorTurFer one merge conflict in `CHANGELOG.md`

**Comment by JorTurFer** [comment]
> @JorTurFer one merge conflict in `CHANGELOG.md`

I see... I had another merge conflict in the same file with the other PR that I have and I have just fixed it. I will update this but when one of them is merged, the other will need changes again :(

**Pull request merged**
