### PR TITLE
chore: add aws-pod-identity e2e tests

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

~[This other PR](https://github.com/kedacore/keda/pull/3684) needs to be merged before continue with this~

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added

Relates to https://github.com/kedacore/keda/issues/3659

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by JorTurFer** [comment]
Let's see if I did the federation correctly for both clusters 🤞  xD

**Pull request merged**
