### PR TITLE
feat(metrics-api): allow user to configure metrics API server port

### LINKED ISSUE #3570: Setting portHttpTarget and portHttpsTarget in the helm chart should change the port the adapter listens on. It does not.
### Report

Even though the container in a pod is correctly started with a custom port via the helm chart, the logs show the metric server is listening on the wrong port.

This manifests as a crash on hostNetwork: true when the port is in use, as it is for me.

Based on the logs and pod, it looks like the error is that `keda-adapter` in the chart and distribution yamls is invoked only with a `--secure-port` arg and not a corresponding one for an insecure (?) port.

Description of pod (relevant section only):
```
Containers:
  keda-operator-metrics-apiserver:
    Container ID:  docker://db6bdc91142c8c03850e0befa1855487e97964a66d7bc5173a2a24a5b45ddda8
    Image:         ghcr.io/kedacore/keda-metrics-apiserver:2.8.0
    Image ID:      docker-pullable://ghcr.io/kedacore/keda-metrics-apiserver@sha256:4afe231e9ce5ca351fcf10a83479eb0ee2f3e6dc0f386108b89d1b5623d56b14
    Ports:         19902/TCP, 19901/TCP
    Host Ports:    19902/TCP, 19901/TCP
    Args:
      /usr/local/bin/keda-adapter
      --secure-port=19902
      --logtostderr=true
      --v=0
```

Logs (relevant only):
```
I0819 18:28:44.205364       1 logr.go:261] keda_metrics_adapter/controller-runtime/metrics "msg"="Metrics server is starting to listen" "addr"=":8080"
E0819 18:28:44.205578       1 logr.go:279] keda_metrics_adapter/controller-runtime/metrics "msg"="metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
E0819 18:28:44.205591       1 main.go:126] keda_metrics_adapter "msg"="failed to setup manager" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
E0819 18:28:44.205599       1 main.go:231] keda_metrics_adapter "msg"="making provider" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
E0819 18:28:44.205605       1 main.go:190] keda_metrics_adapter "msg"="unable to run external metrics adapter" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
```

Helm chart values:
```
metricsServer:
  # calico workaround
  useHostNetwork: true
service:
  type: ClusterIP
  portHttp: 80
  portHttpTarget: 19901
  portHttps: 443
  portHttpsTarget: 19902
```

### Expected Behavior

`keda-adapter` should be called with all the ports I configure.

### Actual Behavior

It is only called with `--secure-port`.

### Steps to Reproduce the Problem

1. Deploy the helm chart with the following values:
```
    metricsServer:
      # calico workaround
      useHostNetwork: true
    service:
      type: ClusterIP
      portHttp: 80
      portHttpTarget: 19901
      portHttps: 443
      portHttpsTarget: 19902
 ```
2. `curl http://pod-ip:19901/healthz` and observe it isn't listening on that port.
3. `curl http://pod-ip:8080/healthz` and observe it is.

### Logs from KEDA operator

```
I0819 18:28:44.205364       1 logr.go:261] keda_metrics_adapter/controller-runtime/metrics "msg"="Metrics server is starting to listen" "addr"=":8080"
E0819 18:28:44.205578       1 logr.go:279] keda_metrics_adapter/controller-runtime/metrics "msg"="metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
E0819 18:28:44.205591       1 main.go:126] keda_metrics_adapter "msg"="failed to setup manager" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
E0819 18:28:44.205599       1 main.go:231] keda_metrics_adapter "msg"="making provider" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
E0819 18:28:44.205605       1 main.go:190] keda_metrics_adapter "msg"="unable to run external metrics adapter" "error"="error listening on :8080: listen tcp :8080: bind: address already in use" 
```

### KEDA Version

2.8.0

### Kubernetes Version

1.22

### Platform

Amazon Web Services

### Scaler Details

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by doctorpangloss**
This allows the user to specify which port the metrics API server container should use.

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [X] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Relates to kedacore/keda#3576
Relates to https://github.com/kedacore/charts/pull/308

### CODE REVIEW

**Review by zroubalik — CHANGES_REQUESTED** [review]
Looking good, could you please fix the linter problems and fix DCO?

https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what

**Comment by doctorpangloss** [comment]
> https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what

but I did sign my commit

**Comment by doctorpangloss** [comment]
I am so sorry, I have tried everything to get the DCO check to pass. I acknowledge the DCO.

**Review by zroubalik — APPROVED** [review]
LGTM

but hold with the merge for now

**Comment by doctorpangloss** [comment]
let's do it with the corresponding chart change

let me know if there's anything else I should do, `keda` is great

**Comment by tomkerkhove** [comment]
We're definitely open for PRs on our Helm chart as well - Thank you!

Happy you like KEDA - We are always looking for new end-users!
https://github.com/kedacore/keda-docs#become-a-listed-keda-user

**Comment by JorTurFer** [comment]
I think we can merge this. We held it before the hotfix release but next we can proceed. @zroubalik ?

**Review by JorTurFer — APPROVED** [review]

**Pull request merged**
