### PR TITLE
feat: add seccompProfile

### LINKED ISSUE #3561: Add seccompProfile.type RuntimeDefault for secure-by-default
### Proposal

Add seccompProfile.type RuntimeDefault to Deployments as per PSS/restricted spec:

https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

### Use-Case

This would bring the default manifests into compliance with PSS/restricted policies.

The policies currently fail because the containers in the two Deployments are missing an explicit seccompProfile type.

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build https://github.com/kedacore/keda//config/default) \
  -
```

### Anything else?

seccompProfile is supported in Kubernetes 1.19+

Relates to https://github.com/kedacore/charts/issues/306

### PR DESCRIPTION
**Pull request by joebowbeer**
Add/update securityContext configs:
* seccompProfile.type RuntimeDefault is needed for compliance with restricted policies in Kubernetes 1.19+
* Updated comment in metrics Deployment regarding readOnlyRootFilesystem

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] N/A - Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) => https://github.com/kedacore/charts/pull/307
- [x] N/A - A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #3561

### CODE REVIEW

**Comment by joebowbeer** [comment]
@zroubalik I can't find any details about e2e failure

**Comment by zroubalik** [comment]
@joebowbeer that failure is transient, unrelated :)

**Comment by zroubalik** [comment]
Could you please update Changelog to reflect this addition?

**Comment by joebowbeer** [comment]
@zroubalik PTAL

Since seccompProfile requires Kubernetes 1.19+ (otherwise validation fails), I think this is the best that can be done until the minimum version is raised from 1.17 to 1.19.

**Comment by tomkerkhove** [comment]
As per https://github.com/kedacore/governance/blob/main/SUPPORT.md#kubernetes-support we should just add it given 1.19 has been out for a while

**Comment by joebowbeer** [comment]
@tomkerkhove PTAL

I restored the seccompProfile changes.

Will you bump the k8s minVersion to 1.19?

**Comment by joebowbeer** [comment]
@JorTurFer @zroubalik the e2e tests failed in 0s - flake?

**Comment by JorTurFer** [comment]
yes, it looks as flaky test, I have opened an issue to review them https://github.com/kedacore/keda/issues/3594

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
Thanks for your contribution!

**Comment by JorTurFer** [comment]
hey @joebowbeer 
I think this PR is ready to merge but we are going to do a hotfix release soon with only some fixes. After the hotfix release is done, I'll continue with this PR. Sorry for the incovenient

**Comment by joebowbeer** [comment]
@JorTurFer rebased

**Comment by JorTurFer** [comment]
Thanks a lot! :heart:

**Pull request merged**
