### PR TITLE
Fix typo and reuse predefined value

### PR DESCRIPTION
**Pull request by yoongon**
1. Fix typo: then => than
2. Use predefined variable to increase consistency.

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #

Relates to #

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
❤️

**Comment by yoongon** [comment]
some checks didnt pass, but I don't think it's related with this change.

Please let me know, if something is missing :)

**Review by zroubalik — APPROVED** [review]

**Comment by tomkerkhove** [comment]
@JorTurFer @zroubalik I presume we can skip semgrep

**Comment by JorTurFer** [comment]
it's not Semgrep, it's the e2e tests check. IDK why, even though we create it in other check, it randomly appears...
image

**Pull request merged**
