### PR TITLE
moving rabbitMq host to resolved value

### LINKED ISSUE #89: Move rabbitmq password to environment.
I think the current rabbitmq spec contains a password 'guest' https://github.com/Azure/Kore/blob/master/examples/rabbitmq_scaledobject.yaml#L15

This should probably move to env vars like we handled all other secrets, right?

/cc @yaron2

### PR DESCRIPTION
**Pull request by jeffhollan**
resolve #89 

Making a WIP PR as there is a big question on how we release this as it will be breaking.

### CODE REVIEW

**Comment by jeffhollan** [comment]
Actually one thought here that may add consistency and make non-breaking too.

Potentially we can add a new property called `connection` that resolves from Env.  For the time being we could support both (`host` as a literal value, `connection` as a resolved value).  Before we 1.0 we would remove support for `host` and only accept `connection`.  This would also make naming more in line with other scalers.

**Comment by tomkerkhove** [comment]
@jeffhollan 	Given this is still in "alpha"/"beta" and we have the auth changes coming up, I would just consider it as breaking change.

We've discussed this as well for the auth changes and would suggest to introduce a versioned image tag which contains the new features for more stable images

**Comment by jeffhollan** [comment]
Ok great - yeah let's just do as-is and change how host behaves.  @ahmelsayed is going to take a snapshot version of current keda:latest so that people can easily roll back to it as needed if they break from this PR, and the many more around auth spec that will start rolling out

**Comment by ahmelsayed** [comment]
Thanks @jeffhollan :)

**Comment by ahmelsayed** [comment]
btw, `kedacore/keda:0.2` is the snapshot. I updated `:latest` to `:master` right before this merge. Will update it again to include this once the build is done on dockerhub.

**Pull request merged**
