### PR TITLE
Use CNCF Runners

### PR DESCRIPTION
**Pull request by JorTurFer**
### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory


:(

**Comment by JorTurFer** [comment]
yeah, we are still working on this, it's the last pending task 😄

**Comment by JorTurFer** [comment]
Ignore semgrep messages, I had an issue rebasing and it detected a lot of commits

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
