### PR TITLE
Make lightning white in logo

### PR DESCRIPTION
**Pull request by turbaszek**
Change lightning in logo to be white except white logo where it's looks weird

CC: @tomkerkhove 

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Tests have been added
- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ] Changelog has been updated

Fixes #

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks!

**Comment by tomkerkhove** [comment]
Can you fix the static checks please? Not sure if it's possible in the PNG file

**Comment by turbaszek** [comment]
@tomkerkhove should be good now

**Comment by turbaszek** [comment]
Hey, btw what is the sparkle feature? I've never seen it before anywhere  else 👀 
Screenshot 2020-10-21 at 11 23 42

**Comment by tomkerkhove** [comment]
> Hey, btw what is the sparkle feature? I've never seen it before anywhere else 👀
> Screenshot 2020-10-21 at 11 23 42

I'll show you, if you earn it ;)

**Comment by turbaszek** [comment]
> I'll show you, if you earn it ;)

@tomkerkhove I see that it adds an even to timeline, but my main question is - how to turn it on in other repo? Or is it only a beta feature?

**Comment by tomkerkhove** [comment]
You can't, it's in closed beta

**Pull request merged**
