### PR TITLE
change stripDeadJobs to ReservedAgent

### PR DESCRIPTION
**Pull request by ramondegoede**
Change the function in which the scaler looks for jobs to filter out from succeeded to reserved agent. This makes will make the filtering of jobs which have been taken over even quicker, because jobs which are running but not succeeded yet will also be filtered out.

### Checklist

- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [ ] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [ ] Tests have been added
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #

Relates to #

### CODE REVIEW

**Comment by JorTurFer** [comment]
@Eldarrin , WDYT about this change?

**Comment by Eldarrin** [comment]
I see no issue with the change directly, seems like a good idea. I do not know what unintended consequences there *may* be though. Would it be better to test a direct variable instead? It seems that ReservedAgent is a consequence of being assigned and not a direct variable saying it has been assigned.

**Comment by Eldarrin** [comment]
damn, written and deleted a response twice. I see it now, but does it really matter as the system is working and the change will at most affect microseconds? But yeah, could be an improvement if it was tested thoroughly at scale

**Comment by JorTurFer** [comment]
I'm worried about it because I have executed e2e tests twice and both times `azure_pipelines_test` has failed

**Comment by Eldarrin** [comment]
> I'm worried about it because I have executed e2e tests twice and both times `azure_pipelines_test` has failed. Could you check it @ramondegoede ?

quick check pat tokens didn't expire? :) can't see results

**Comment by JorTurFer** [comment]
> quick check pat tokens didn't expire?

I don't think so. The other AzPipeline e2e test passes: https://github.com/kedacore/keda/actions/runs/6513120951/job/17694623703#step:9:1840

```log
EXECUTION SUMMARY
##############################################
##############################################
Passed tests:
	Execution of tests/scalers/azure/azure_pipelines_adv/azure_pipelines_adv_test.go, has passed after "one" attempts
Failed tests:
	Execution of tests/scalers/azure/azure_pipelines/azure_pipelines_test.go, has failed after "three" attempts
```

**Comment by Eldarrin** [comment]
So, not for merging IMHO

**Pull request closed without merging**
