### PR TITLE
AWS SDK V2 Upgrade and update scalers

### LINKED ISSUE #4905: AWS Go SDK Upgrade
### Proposal

In the Keda project, we are currently using below AWS Go SDK version.

`github.com/aws/aws-sdk-go v1.44.287`

But AWS released a V2 version long back which has few advantages over V1.

Below are the snippets from their docs.

> The AWS SDK for Go v2 requires Go 1.15 or higher, and offers significant performance improvements in CPU and memory utilization over version 1. Review our [Developer Guide](https://aws.github.io/aws-sdk-go-v2/docs/) to get started with AWS SDK for Go v2 or review the [migration guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/) if you already use version 1.

> The AWS SDK for Go V2 has been updated to take advantage of the Go modules which became the default development mode in Go 1.13. A number of packages provided by the SDK have been modularized and are independently versioned and released respectively. This change enables improved application dependency modeling, and enables the SDK to provide new features and functionality that follows the Go module versioning strategy.

Docs
https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/

Migrating to the AWS SDK for Go V2
https://aws.github.io/aws-sdk-go-v2/docs/

We can upgrade to AWS SDK V2.

### Use-Case

_No response_

### Is this a feature you are interested in implementing yourself?

Maybe

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jeevanragula**
In the Keda project, we are currently using below AWS Go SDK version.

github.com/aws/aws-sdk-go v1.44.287

But AWS released a V2 version long back which has few advantages over V1.
This PR is to update the code to use AWS SDK V2.

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4905

Relates to #4905

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
LGTM! Thanks for the contribution 🙇

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
