### PR TITLE
fix(e2e): uninstall KEDA properly

### PR DESCRIPTION
**Pull request by JorTurFer**
### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Comment by tomkerkhove** [comment]
> /run-e2e potato **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/4852288398)

Your potato test failed, too bad

**Review by tomkerkhove — APPROVED** [review]

**Comment by JorTurFer** [comment]
> Your potato test failed, too bad

But it failed successfully 🤣

**Pull request merged**
