### PR TITLE
Refactor CPU/Memory scaler config

### PR DESCRIPTION
**Pull request by rickbrouwer**
- Refactor the scaler to match the new metadata guidelines.
- The parameter `type` is already from release 2.7 deprecated. I think it's time to announce the removal  and remove the deprecated code in version 2.18.

### Checklist

- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [X] Tests have been added
- [X] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Related: [5797](https://github.com/kedacore/keda/pull/5797)
Docs: https://github.com/kedacore/keda-docs/pull/1484

### CODE REVIEW

**Comment by rickbrouwer** [comment]
> /run-e2e

Hi @wozniakjan. It seems that the e2e run does not start, or takes a bit longer than normal. That is also possible. Or should an extra parameter be given so that it does start?

**Comment by wozniakjan** [comment]
looks like the github actions runner has a hard time - https://github.com/kedacore/keda/actions/runs/11320727466/job/31478704705

```
Job is waiting for a runner from 'equinix-2cpu-8gb' to come online.
```

I will check in with others to see what happened

**Review by JorTurFer — APPROVED** [review]

**Pull request merged**
