### PR TITLE
General: Bubble up AuthRef TriggerAuthentication errors as ScaledObject events

### PR DESCRIPTION
**Pull request by BojanZelic**
Bubble up triggerauth errors for things like hashicorp vault / azure keyvault config/connectivity issues whenever there are problems; 

example mis-configuring vault with a bad role will now create an k8s event on the scaledObject:

```
Warning  KEDAScalerFailed         38s (x17 over 6m6s)    keda-operator  Error making API request.\n\nURL: PUT https://my-vault-server/v1/auth/cluster/login\nCode: 403. Errors:\n\n* permission denied
```

example mis-configuring the vault url
```
Warning  KEDAScalerFailed         30s (x13 over 51s)  keda-operator  Get "bad-vault-url/v1/auth/token/lookup-self": unsupported protocol scheme "" 
```

### Checklist

- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/5190

### CODE REVIEW

**Comment by BojanZelic** [comment]
For the E2E failures; they look unrelated to me

1) `gcp_storage_workload_identity_test.go` - seems this test can't be run in parallel?
```
/__w/keda/keda/tests/scalers/gcp/gcp_storage_workload_identity/gcp_storage_workload_identity_test.go:***76
2023-12-07T18:20:03.3063023Z         	Error:      	Received unexpected error:
2023-12-07T18:20:03.3063980Z         	            	Creating gs://gcp-storage-workload-identity-test-bucket/...
2023-12-07T18:20:03.3066748Z         	            	ServiceException: 409 A Cloud Storage bucket named 'gcp-storage-workload-identity-test-bucket' already exists. Try another name. Bucket names must be globally unique across all Google Cloud projects, including those outside of your organization.
2023-12-07T18:20:03.3067530Z         	            	command terminated with exit code ***
2023-12-07T18:20:03.3068071Z         	Test:       	TestScaler
2023-12-07T18:20:03.3069390Z         	Messages:   	Failed to create GCS bucket - Creating gs://gcp-storage-workload-identity-test-bucket/...
2023-12-07T18:20:03.3072153Z         	            	ServiceException: 409 A Cloud Storage bucket named 'gcp-storage-workload-identity-test-bucket' already exists. Try another name. Bucket names must be globally unique across all Google Cloud projects, including those outside of your organization.
```

2) `azure_pipielines_adv_test` seems like it's connectivity issues to Azure? & doesn't use TriggerAuthentication object
```
2023-12-07T18:20:08.6082758Z ***0***3-***-07T***7:50:30Z	ERROR	azure_pipelines_scaler	error getting pipelines queue length	***"type": "ScaledJob", "namespace": "azure-pipelines-demands-test-ns" , "name": "golang-alldemand-sj", "error": "Get \"***/_apis/distributedtask/pools/***3/jobrequests?$top=***50\": context canceled"***

```

**Review by zroubalik — APPROVED** [review]
LGTM

**Pull request merged**
