### PR TITLE
feat: add a way to always have job running

### PR DESCRIPTION
**Pull request by guilhem**
_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)* 
- [x] Changelog has been updated

https://github.com/kedacore/keda-docs/pull/422

### CODE REVIEW

**Comment by coderanger** [comment]
Why would you use this instead of a Deployment? It seems like you're just reinventing Deployments :)

**Comment by guilhem** [comment]
@coderanger ahaha yes, look like this at first sight :)

for azure devops runners, we must always have a runner active (job scheduler fail if no job at all).
But using deployment is a problem because job can alterate the runner container between runs (installing packages, files etc) and we want to always have a clean runner environment.

**Comment by coderanger** [comment]
Hmm, the azure pipelines agent doesn't exit after a single job though?

**Comment by coderanger** [comment]
Aha, that explains it better :D (the --once bit)

**Comment by guilhem** [comment]
For The Record, we found a workaround for Azure DevOps pipeline:
we have created a `dummy-DoNotDelete` agent which is always offline (created not removed).
Jobs are now scheduled to the pool and _keda_ spawn agents according to queue.

**Comment by tomkerkhove** [comment]
Might be something nice to add to the Azure Pipelines scalers docs maybe as well?

**Comment by zroubalik** [comment]
@guilhem Interesting, so this feature is not needed for your usecase?

**Comment by guilhem** [comment]
> Might be something nice to add to the Azure Pipelines scalers docs maybe as well?

We are improving the workload and images right now.
We will push something when everything is good to go for anyone :)

> @guilhem Interesting, so this feature is not needed for your usecase? So I am not sure if we should proceed with this feature then.

I understand :)

**Comment by zroubalik** [comment]
> > Might be something nice to add to the Azure Pipelines scalers docs maybe as well?
> 
> We are improving the workload and images right now.
> We will push something when everything is good to go for anyone :)
> 
> > @guilhem Interesting, so this feature is not needed for your usecase? So I am not sure if we should proceed with this feature then.
> 
> I understand :)

So if you don't mind and I will close this and we can reopen if needed?

**Comment by guilhem** [comment]
> So if you don't mind and I will close this and we can reopen if needed?

I don't ;)

**Pull request closed without merging**
