### PR TITLE
Delete the cache entry when a ScaledObject is deleted

### LINKED ISSUE #2407: Metric name (and other values) is not updated with the changes in the SO
### Report

Metric name is not updated with the changes in the SO when instead of updating you delete and create it again.
I found that cache is not purged after ScaledObject deletion and if you delete and create the SO instead of updating, the generation will be 1 in both cases, so the old entry is used instead of building the scaler again.

### KEDA Version

2.5.0

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: jorturfer <jorge_turrado@hotmail.es>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated

Fixes #2407

### CODE REVIEW

**Comment by JorTurFer** [comment]
I'm not sure about the best way to test this change. Maybe as a test inside `scaledobject_controller_test` 🤔 
WDYT?

**Comment by JorTurFer** [comment]
I'm not sure if waiting with sleep is worth (I guess that it isn't... Is there a better way to do that test?

**Comment by VerstraeteBert** [comment]
> I'm not sure if waiting with sleep is worth (I guess that it isn't... Is there a better way to do that test?

I'm guessing you want to wait until the SO is deleted right? If so, you can try passing the foreground deletion option ([ref](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#DeleteOptions))

**Review by zroubalik — APPROVED** [review]
Good catch! And +1 for the test :)

**Pull request merged**
