### PR TITLE
Kafka: Ability to set upper bound to the number of partitions with lag

### PR DESCRIPTION
**Pull request by DmitrySenin**
Added a way to configure the Kafka scaler to limit the max number of spun-up replicas to the number of partitions with non-zero lag.
This flag is definitely not compatible with `allowIdleConsumers`. Hence, added the respective validation
Also I don't see much sense in not having a topic when using the new setting. So added a validation check for this case as well

### Checklist

- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes https://github.com/kedacore/keda/issues/3997

Relates to https://github.com/kedacore/keda-docs/pull/1107

### CODE REVIEW

**Comment by DmitrySenin** [comment]
I would need to some help with testing. Do I need to test all locally? Or there is a test env(with a Kafka scaler) which gets automatically spun up?

**Comment by zroubalik** [comment]
> I would need to some help with testing. Do I need to test all locally? Or there is a test env(with a Kafka scaler) which gets automatically spun up?

There are e2e tests that you can run locally (against k8s cluster) and then we can also trigger them on the PR:
https://github.com/kedacore/keda/blob/main/tests

You should extend this test: https://github.com/kedacore/keda/blob/main/tests/scalers/kafka/kafka_test.go

**Comment by zroubalik** [comment]
any update on this please?

**Comment by DmitrySenin** [comment]
I've been busy at work. I should be back with e2e tests by Monday

**Comment by zroubalik** [comment]
> I've been busy at work. I should be back with e2e tests by Monday

gentle ping :)

**Review by zroubalik — COMMENTED** [review]
To fix the Static Checks, please add exception rule here: https://github.com/kedacore/keda/blob/main/.golangci.yml#L53

**Comment by BojanZelic** [comment]
@DmitrySenin any update on this feature? I could give implementing the tests & anything left over a try to get this merged; Would love to see this implemented

**Comment by DmitrySenin** [comment]
@BojanZelic , I'm unlikely to get back to this one in the next two months. So feel free to pick up.
I think [Static Checks](https://github.com/kedacore/keda/pull/4453#pullrequestreview-1432625443) need to be fixed and unit tests need to be added

**Comment by zroubalik** [comment]
Resolved in https://github.com/kedacore/keda/pull/5060

**Pull request closed without merging**
