### PR TITLE
Reference ScaledObject's/ScaledJob's name in the scalers log

### LINKED ISSUE #3419: Reference ScaledObject's/ScaledJob's name in the scalers log
### Proposal

Reference ScaledObject's/ScaledJob's name in the scalers log, together with a namespace of the SO/SJ.

This should help with debugging KEDA logs, when there are hundreds of SOs/SJs it is hard to assign particular log message to a SO/SJ.

### Use-Case

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

Reference ScaledObject's/ScaledJob's name in the scalers log.

Sorry for the huge PR :(

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Relates #3419

### CODE REVIEW

**Comment by JorTurFer** [comment]
Tomorrow morning I'll take a look with a long coffee xD

**Comment by zroubalik** [comment]
> Tomorrow morning I'll take a look with a large coffee xD

Thanks 😄 

I don't understand what is the problem with the Static Checks and build, it complains about part of the code (`kafkaLog` variable) that is no longer present in the code 💩 It seems like some corrupted cache in the git? I tried to force push again, to rewrite the stuff, but no help.

**Comment by zroubalik** [comment]
@JorTurFer for some reason GitHub wasn't able to process that huge PR. So I am going to split the change into multiple PRs. Once this first one is going to be merged, I will open the following PRs.

**Review by JorTurFer — APPROVED** [review]

**Pull request merged**
