### PR TITLE
Job annotations

### PR DESCRIPTION
**Pull request by InbarRose**
* Update scale_jobs.go
* Update CHANGELOG.md

add annotations from scaledjob spec to job spec
add new improvement to changelog

Relates to https://github.com/kedacore/keda/issues/4594

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
looking good! Could you add a unit test to validate the annotations?
Please, update docs as well 🙏

**Comment by InbarRose** [comment]
> looking good! Could you add a unit test to validate the annotations? Please, update docs as well pray

would be happy to add tests.
Can you help me understand where I should add them?

**Comment by JorTurFer** [comment]
> Can you help me understand where I should add them?

You can use this test as example: https://github.com/kedacore/keda/blob/main/pkg/scaling/executor/scale_jobs_test.go#L202-L214
I'd add a test case calling to `scaleExecutor.createJobs` and checking the generated job

**Comment by InbarRose** [comment]
> > Can you help me understand where I should add them?
> 
> You can use this test as example: https://github.com/kedacore/keda/blob/main/pkg/scaling/executor/scale_jobs_test.go#L202-L214 I'd add a test case calling to `scaleExecutor.createJobs` and checking the generated job

those are all using mocks to simulate the scaling decision.
I am happy to add a new test to an existing framework, but I don't think this is the write scope to generate a whole new test framework.
If there is already an existing test framework which will generate a new job from a scaled job, please share where i can find it.

**Comment by JorTurFer** [comment]
> I am happy to add a new test to an existing framework, but I don't think this is the correct scope to generate a whole new test framework.

You don't need to generate the whole tests framework. There are other tests (I didn't link the correct one, sorry) that mock the client to test only the executor: https://github.com/kedacore/keda/blob/main/pkg/scaling/executor/scale_jobs_test.go#L216-L287

You could do something similar, calling the client mock with an empty slice, implementing the Create function mock which just adds the new job to the slice, and checking the slice elements at the end of the call:

1. Implement the mock function for client.Create, storing the new created jobs in the slice that the mock receives during the creation
2. Add a test which starts the mock with an empty array and generate the scalerExecutor.
3. Call to `scaleExecutor.createJobs` with the needed info
4. After the end of the call, check the slice and evaluate if the job/jobs contain the annotations that you added in the ScaledJob

With this, you could check your code and you don't need to create the whole test framework, just adding the required mock functions is enough IMO

**Review by zroubalik — COMMENTED** [review]
Agree with @JorTurFer, adding a test would be great.

**Review by zroubalik — COMMENTED** [review]
@InbarRose any update on this please? We are about to do a new release.

**Comment by zroubalik** [comment]
Implemented in: https://github.com/kedacore/keda/pull/5106

**Pull request closed without merging**
