### PR TITLE
chore: reduce infra costs during e2e tests

### PR DESCRIPTION
**Pull request by JorTurFer**
I have reviewed e2e tests to execute them just in 2 nodes instead of 4 nodes. 
I have removed all the pod requests, where they aren't 100% required to not enforce more nodes

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Comment by JorTurFer** [comment]
I have executed the e2e tests [here](https://github.com/kedacore/keda/pull/5058#issuecomment-1751783114) with 2 nodes thanks to a modification in the Makefile.

**Review by zroubalik — COMMENTED** [review]
Where is the Makefile modification you mentioned?

**Comment by JorTurFer** [comment]
This commit the change: https://github.com/kedacore/keda/pull/5058/commits/b3eae4462be9ff238749fde4c9f854d7652bc750

**Comment by zroubalik** [comment]
> This commit the change: [b3eae44](https://github.com/kedacore/keda/commit/b3eae4462be9ff238749fde4c9f854d7652bc750)

I dont' see this change in the final diff?

**Comment by zroubalik** [comment]
> > I dont' see this change in the final diff?
> 
> No, we don't need it because I changed the github workflow (because it's the correct place). I just did it for testing how e2e test works with 2 instances.

Okay, It was a little bit confusing to me 😄

**Review by zroubalik — APPROVED** [review]

**Comment by JorTurFer** [comment]
I meant that I testes the e2e tests 2 just 2 nodes, even though the values in main branch (where the workflow is executed from) say 4. I "hacked" it modifying the Makefile to override given values (4 and 1) to scale to 1 and 1. After validating that 2 nodes were enough, I reverted the "hack"

**Pull request merged**
