### PR TITLE
Patch to make the HTTPClient proxy-aware

### PR DESCRIPTION
**Pull request by wltbenade**
This patch addresses #2577

- Simple implementation to allow the HTTPClient to read proxy variables, if available, from the environment.
- Not sure where this should be documented.
- No tests updated, as all scalers should behave as normal.

_Provide a description of what has been changed_

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
LGTM!
Thanks for this improvement! ❤️ 

Let's wait till e2e tests finish. Apart from this, could you create a PR in keda-docs adding information about this?  Maybe in the section `operate`, you could create another subsection like [`HTTP Timeouts`](https://github.com/kedacore/keda-docs/blob/main/content/docs/2.7/operate/cluster.md?plain=1#L50) explaining how to configure this.
Do you think that those environment variables should be added also to the helm chart?

**Comment by JorTurFer** [comment]
We also need that you sign all the commits that you do. [This link ](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what)explains how to solve with already created commits

**Comment by wltbenade** [comment]
Thanks, @JorTurFer! Appreciate the quick response :)

I'll resubmit the PR with signed commits, and submit a PR to keda-docs.

**Pull request closed without merging**
