### PR TITLE
Adds e2e test for PostgreSQL scaler

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: jorturfer <jorge_turrado@hotmail.es>

This PR adds e2e test for Postgres scaler. It's a draft until this other PR is merged ~~https://github.com/kedacore/test-tools/pull/18~~ https://github.com/kedacore/test-tools/pull/20  (I need it to use the PostgreSQL docker image here :) )
### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added

### CODE REVIEW

**Comment by JorTurFer** [comment]
This afternoon, I'll update the image and open the PR :)

**Review by zroubalik — APPROVED** [review]
LGTM, thanks a lot for doing that!

**Comment by zroubalik** [comment]
Does it still need to be a Draft

**Comment by JorTurFer** [comment]
> Does it still need to be a Draft

Yes, I want to double-check the image because I'm getting weird concurrency errors inside Postgres container. The e2e test is working since it checks the amount of instances only, but I prefer to fix the problem with the e2e image before. The image can be used for other stuffs, and it must work well also with concurrency
Today I'll do it :)

**Comment by zroubalik** [comment]
OK, no rush :)

**Comment by JorTurFer** [comment]
> OK, no rush :)

It was a problem related with the isolation level (sorry, I'm not an expert, in Postgres 😢). [I have set the isolation level to default](https://github.com/kedacore/test-tools/pull/19) and now it seems that it's working.
When that PR in test-tools is merged, this PR is ready to be opened 😄

**Comment by JorTurFer** [comment]
I have checked again with the new image, and it's working without any extra error, so it's ready to merge :)

**Pull request merged**
