### PR TITLE
Respect optional param for ConfigMaps and Secrets

### PR DESCRIPTION
**Pull request by tomislater**
I am working on tests, but it might take some time :) I am new here.

#555

### CODE REVIEW

**Comment by zroubalik** [comment]
LGTM, thanks @tomislater

**Comment by tomislater** [comment]
Uhh, I do not know how to start writing tests here for something other than `scalers`.
Handlers do not have any tests currently.

I wanted to use fake client like [here](https://github.com/kubernetes/ingress-nginx/blob/master/internal/k8s/main_test.go) or [here](https://medium.com/@e_frogers/unit-testing-with-kubernetes-client-go-283b11aaa7db). But, I have got this error:

```
pkg/handler/scale_handler_test.go:22:2: cannot use "k8s.io/client-go/kubernetes/fake".NewSimpleClientset() (type *"k8s.io/client-go/kubernetes/fake".Clientset) as type client.Client in field value:
        *"k8s.io/client-go/kubernetes/fake".Clientset does not implement client.Client (missing Create method)
```

when I want to create test ScaleHandler:

```
var testScaleHandler = ScaleHandler{
	client:           testclient.NewSimpleClientset(),
	reconcilerScheme: scheme.Scheme,
}
```

Do you have any suggestions? Or maybe someone is working on writing tests for handlers currently?

**Comment by ahmelsayed** [comment]
We're using operator-sdk for interacting with kuberentes, so you'll have to create the fake client like this https://github.com/operator-framework/operator-sdk/blob/master/doc/user/unit-testing.md 

That part is currently only partially covered by the integration tests under [`tests/`](https://github.com/kedacore/keda/blob/master/tests/)

**Comment by tomislater** [comment]
Thanks, I am going to add tests.

**Comment by ahmelsayed** [comment]
Thank you very much @tomislater

**Comment by siva-27** [comment]
Hi, Keda is still throwing an error when we use the secretkeyref in the deployment with the latest version too, for example
```    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
            optional: true 
```
Please let me know if need any other info.

**Pull request merged**
