### PR TITLE
Migrate e2e test for MongoDB to Go.

### LINKED ISSUE #3241: Migrate e2e test for MongoDB to Go
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

### Use-Case

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by v-shenoy**
Signed-off-by: Vighnesh Shenoy <vshenoy@microsoft.com>

_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added

Fixes #3241 

Relates to #2737

### CODE REVIEW

**Comment by v-shenoy** [comment]
Any idea why the tests are queued for so long? @JorTurFer

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
> Any idea why the tests are queued for so long? @JorTurFer

I have changed the previous approach of using GH concurrency to the approach of using a single runner to not lose any execution during the process. Now we are working 3 people running e2e tests, and it could produce longer delays waiting for the resources.
It's true that we have "higher" concurrency than usually . With e2e tests migration, we are enqueueing more e2e tests and even thought I optimized the process, it's not enough.
Let's see if we need to address this with other solution or if it's only a temporal problem related with the migrations.

**Comment by JorTurFer** [comment]
> The only cases where it might be a problem is when some PR requires the entire e2e suite to be run.

yes, and that it's not really often

**Comment by zroubalik** [comment]
@v-shenoy do you think that you can also implement the `activation*` for this scaler?
https://github.com/kedacore/keda/issues/2800

https://github.com/kedacore/keda/pull/3383

**Comment by v-shenoy** [comment]
@zroubalik Sorry, I don't think I will be able to take this up. Have some personal things going on.

**Comment by JorTurFer** [comment]
I'll do it

**Pull request merged**
