### PR TITLE
use correct index in `ScalerBuilder.Factory`

### LINKED ISSUE #2381: Keda 2.5 does not cleanly update from 2.4
### Report

There appears to be a bug that prevents a clean and safe upgrade from keda 2.4 to keda 2.5, possibly related to [this PR which changed metric names](https://github.com/kedacore/keda/pull/2161) or [This one](https://github.com/kedacore/keda/pull/2099/files) . This affects pre-existing ScaledObjects are are present at the time of the 2.4 upgrade.

The symptom would be that the HPA loop would be attempting to evaluate a metric which did not actually exist within the Kubernetes external metrics API. Below is a snippet of the output of a `kubectl describe hpa` where the new keda 2.5 format of metrics would be queried and the log output of the external-metrics API

```
Metrics:                                               ( current / target )
  "s1-prometheus-burrow_lag" (target average value):   <unknown> / 120M
  resource cpu on pods  (as a percentage of request):  108% (3267m) / 100%
```
  
```
  Warning  FailedGetExternalMetric  3m6s (x791 over 3h22m)  horizontal-pod-autoscaler  unable to get external metric s001/s1-prometheus-burrow_lag/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: No matching metrics found for s1-prometheus-burrow_lag
```
    
```
kubectl get --raw '/apis/external.metrics.k8s.io/v1beta1/namespaces/s001/s1-prometheus-burrow_lag?labelSelector=app=myApp' | jq
Error from server: No matching metrics found for s1-prometheus-burrow_lag
```

Reverting to Keda 2.4 would immediately fix the issue and resume using the old names.
When in an errored state, remediation was possible by deleting all ScaledObjects and recreating them. This appeared to cause a reconciliation for the recreated scaledObject to the point the new-style metric becomes available.

### Expected Behavior

Expect Keda 2.5 to immediately and reliably work out of the box for existing scaledObject definitions.

### Actual Behavior

Upgrading from Keda 2.4 to Keda 2.5 is disruptive for pre-existing scaledObject-managed HPAs. New style metrics are inaccessible from the keda metrics APIserver

### Steps to Reproduce the Problem

1. Deploy Keda 2.4
2. Create scaledObjects of Prometheus
3. Upgrade to Keda 2.5

This issue may be difficult to reproduce. This only occurred in 2 out of my 30 kubernetes clusters. But it consistently happened within those 2. I am entirely unclear as to why the 2 clusters persistently had the issue: they should be identically configured as the rest.

### Logs from KEDA operator

```
 Warning  FailedGetExternalMetric  3m6s (x791 over 3h22m)  horizontal-pod-autoscaler  unable to get external metric s001/s1-prometheus-burrow_lag/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name=myApp:,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: No matching metrics found for s1-prometheus-burrow_lag
```

### KEDA Version

2.5.0

### Kubernetes Version

1.20

### Platform

Other

### Scaler Details

Prometheus

### Anything else?

_No response_

### LINKED ISSUE #2592: Metric names become incorrect if any of ScaledObject's triggers is unavailable
### Report

After some amount of time of successful operation, the HPA reports that some of the metrics it is looking for are not available. This is because the name of the metric in the HPA has been changed to something that appears to be incorrect. Restarting the operator and metrics-apiserver will temporarily correct the metric names in the HPA.

Initial report from Slack: https://kubernetes.slack.com/archives/C01JGDP8MB8/p1643049613000900

I first observed this with 2.5.0 and it is still occurring with 2.6.0. Prior to 2.5.0 we were running 2.2.0 so I don't know about the versions in between.

Initial list of metrics in HPA when it's working (note the s`n`- prefix is all unique numbers strictly increasing):
```
  externalMetricNames:
  - s0-rabbitmq-Europa-OnlinePlayerStatus-processUpdateIssueOnlineStatusRequest
  - s1-rabbitmq-Europa-OnlinePlayerStatus-processUpdateIssueOnlineStatusRequest
  - s2-rabbitmq-Europa-OnlinePlayerStatus-processSyncRequest
  - s3-rabbitmq-Europa-OnlinePlayerStatus-processSyncRequest
  - s4-rabbitmq-Europa-OnlinePlayerStatus-processIssueResolved
  - s5-rabbitmq-Europa-OnlinePlayerStatus-processIssueResolved
  - s6-rabbitmq-Europa-OnlinePlayerStatus-processIssueCreated
  - s7-rabbitmq-Europa-OnlinePlayerStatus-processIssueCreated
```

That same HPA later stops scaling appropriate (scales out to max instances) and reports the following metric names (note the duplicate s7- prefixes and the absence of an s1- prefix. The `s7-rabbitmq-Europa-OnlinePlayerStatus-processUpdateIssueOnlineStatusRequest` metric is reported as being unavailable which makes sense since it is actually `s1-rabbit...` on the metrics server) 
```
  externalMetricNames:
  - s0-rabbitmq-Europa-OnlinePlayerStatus-processUpdateIssueOnlineStatusRequest
  - s7-rabbitmq-Europa-OnlinePlayerStatus-processUpdateIssueOnlineStatusRequest
  - s2-rabbitmq-Europa-OnlinePlayerStatus-processSyncRequest
  - s3-rabbitmq-Europa-OnlinePlayerStatus-processSyncRequest
  - s4-rabbitmq-Europa-OnlinePlayerStatus-processIssueResolved
  - s5-rabbitmq-Europa-OnlinePlayerStatus-processIssueResolved
  - s6-rabbitmq-Europa-OnlinePlayerStatus-processIssueCreated
  - s7-rabbitmq-Europa-OnlinePlayerStatus-processIssueCreated
```

### Expected Behavior

The metric names written to the HPA should match the metrics being sent to the metrics server. 

### Actual Behavior

The metric names deviate from what is being sent to the metrics server.

### Steps to Reproduce the Problem

1. Install KEDA 2.5.0 or 2.6.0
2. Deploy ScaledObject with RabbitMQ triggers (8 triggers in the above example)
3. Wait...
4. Sometimes the metric names will change as noted above

I'm running KEDA on 12 identical clusters right now and most of them don't run in to this issue. For those that do, it can be as little as a few hours to a few days before this shows up. 

### Logs from KEDA operator

```
example
```

### KEDA Version

2.6.0

### Kubernetes Version

1.21

### Platform

Google Cloud

### Scaler Details

RabbitMQ

### Anything else?

`scalerIndex` is pulled from this `for` loop which is where the number for the s`n`- prefix of metric names is pulled from:
https://github.com/kedacore/keda/blob/e44a31e2527e4016cd0441bf5ad274bc9e279c57/pkg/scaling/scale_handler.go#L285

Given that, I'm not clear on how, in the above example, there is no `s1-` prefix and there are duplicate `s7-` prefixes.

Initially there was thought that this might be related to https://github.com/kedacore/keda/issues/2407 which was implemented in 2.6.0, but after upgrading to 2.6.0, this is still occurring.

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

We have passed a wrong reference to scaler index in the for loop in the factory method. And subsequent calls to `factory()` resulted in the last index has been populated for this particular scaler.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #2592
Fixes #2381

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]
Nice catch!!! ❤️  ❤️

**Comment by tomkerkhove** [comment]
After this we can also close https://github.com/kedacore/keda/issues/2381 I presume?

**Comment by zroubalik** [comment]
> After this we can also close #2381 I presume?

Yeah, I think we can, good catch.

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
❤️

**Pull request merged**
