### PR TITLE
Adding changes for configuring unsafe ssl for self signed certs use case

### PR DESCRIPTION
**Pull request by mayurvaid-redvest**
_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #

Relates to #

### CODE REVIEW

**Comment by mayurvaid-redvest** [comment]
@JorTurFer   , I messed up while merging it .. in git Can you please review this one

**Comment by mayurvaid-redvest** [comment]
Keda Docs Link : https://github.com/kedacore/keda-docs/pull/913/files

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
Thanks for the improvement! ❤️

**Comment by mayurvaid-redvest** [comment]
> Thanks for the improvement! ❤️

Thanks for quick help

**Pull request merged**
