### PR TITLE
Add ActiveMQ Classic Scaler

### PR DESCRIPTION
**Pull request by melisatanrverdi**
Signed-off-by: melisatanrverdi <melisatanrverdi@gmail.com>

Add ActiveMQ Classic Scaler

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated

Relates to  #2120

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thank you for your PR!

**Comment by tomkerkhove** [comment]
Just for my reference as an ActiveMQ newbie - What's the difference between classic and Artemis that we support today?

**Review by zroubalik — COMMENTED** [review]
Thanks for this PR! I have a couple of questions/remarks:
1. I wonder whether `AciveMQ Classic` is the correct name for the scaler, I mean the `Classic` part, if I am not mistaken there is no such project/product. I think we can name this scaler just `ActiveMQ`, what do you think?
2. please fix the DCO https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work
3. please format the code and fix all the linter related problems: https://github.com/kedacore/keda/pull/2121/checks?check_run_id=3726021740
4. please add unit tests
5. please add e2e tests: https://github.com/kedacore/keda/tree/main/tests

**Comment by melisatanrverdi** [comment]
> Thanks for this PR! I have a couple of questions/remarks:
> 
>     1. I wonder whether `AciveMQ Classic` is the correct name for the scaler, I mean the `Classic` part, if I am not mistaken there is no such project/product. I think we can name this scaler just `ActiveMQ`, what do you think?
> 
>     2. please fix the DCO https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work
> 
>     3. please format the code and fix all the linter related problems: https://github.com/kedacore/keda/pull/2121/checks?check_run_id=3726021740
> 
>     4. please add unit tests
> 
>     5. please add e2e tests: https://github.com/kedacore/keda/tree/main/tests

Yes you are right, I changed the name as ActiveMQ. I am working on tests.

**Comment by melisatanrverdi** [comment]
My branch is behind with a ton of commits so I am closing this PR. I will open a new one.

**Comment by arschles** [comment]
@melisatanrverdi sounds good 👍

**Pull request closed without merging**
