### PR TITLE
Allow disable custom metrics

### PR DESCRIPTION
**Pull request by aminebizid**
Let the user disable installing custom metrics APIService.

**config.yaml example**

```yaml
customMetrics:
  create: false
```

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Just curious - Why would you want to do this?

**Comment by aminebizid** [comment]
@tomkerkhove Keda does not work with ambassador because of custom metrics 
#90

**Comment by bbrowning** [comment]
It's not that Ambassador needs custom metrics to be disabled. It's that KEDA shouldn't register a custom metrics api service unless it's actually serving custom metrics, which it appears to not be doing. I think? If KEDA doesn't need to serve custom metrics to work and works fine on just external metrics, we could just remove the custom metrics bits entirely.

**Comment by aminebizid** [comment]
Anyway, this PR do not remove custom metrics but allow us to disable it if needed.

**Comment by tomkerkhove** [comment]
I think it's fair to see if we need the custom metrics first.

If not, throw it out.
If yes, provide the capability to opt out.

**Comment by Aarthisk** [comment]
KEDA does not need custom metrics. Please see latest PR: https://github.com/kedacore/keda/pull/251

**Comment by ahmelsayed** [comment]
@Aarthisk we can close this, right?

**Pull request closed without merging**
