### PR TITLE
Allow HPA min value to 0

### PR DESCRIPTION
**Pull request by chrisliu1995**
_Provide a description of what has been changed_

### Checklist

- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [ ] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [ ] Tests have been added
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #

Relates to #

https://github.com/kedacore/keda/issues/4697

### CODE REVIEW

**Comment by tomkerkhove** [comment]
This relates to https://github.com/kedacore/keda/issues/208.

That change is nice, but you don't take in to account if the feature flag is on that is required or not. Because of that, we cannot use this approach.

**Review by zroubalik — COMMENTED** [review]
Yeah, agree with @tomkerkhove on this. Also we have the concept of activation which is not compatible with this.

**Comment by ringtail** [comment]
> Yeah, agree with @tomkerkhove on this. Also we have the concept of activation which is not compatible with this.

Maybe we should check the feature gates when keda start up. Scaling to 0 would be extremely slow before(about 5min).

**Comment by JorTurFer** [comment]
> Scaling to 0 would be extremely slow before(about 5min).

Do you mean using KEDA? If you mean using KEDA, there is a parameter to reduce the cooldown period before scaling to 0: https://keda.sh/docs/latest/concepts/scaling-deployments/#cooldownperiod

**Comment by ringtail** [comment]
> > Scaling to 0 would be extremely slow before(about 5min).
> 
> Do you mean using KEDA? If you mean using KEDA, there is a parameter to reduce the cooldown period before scaling to 0: https://keda.sh/docs/latest/concepts/scaling-deployments/#cooldownperiod As default is 300 seconds but you can set the value that you prefer

That's not the key point. even you set the window to 30s, the duration is still slow (from 1 to 0) but others not (from 10 to 1 .e.g.）

**Comment by JorTurFer** [comment]
> but others not (from 10 to 1 .e.g.）

The scaling phase is managed by the [HPA behavior policies.](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior) 
If this is your case, you can configure these policies using the advanced section of the HPA: https://keda.sh/docs/2.10/concepts/scaling-deployments/#advanced

I'm not against using k8s native tools (I prefer that option, indeed), but we cannot trust on them until they are in GA. In general, we support the same behavior on any cluster, not depending on the feature gates enabled (for example in Azure, they don't enable any feature gate, so this won't work).

If there is any way to check the enabled feature gates from KEDA, we could add support to this but if there isn't any way to check it, I prefer to not support it yet

**Comment by zroubalik** [comment]
And actually I think that KEDA can be faster in 0->1 scaling (you just need to set low pollingInterval). HPA interval is usually 15s.

**Comment by zroubalik** [comment]
Closing this PR for now as we don't plan to go this direction. Feel free to suggest a solution with the feature gate approach (the best is to start with an issue with the specific proposal). Thanks!

**Pull request closed without merging**
