### PR TITLE
Limit Kafka Partitions KEDA operates on

### LINKED ISSUE #3830: Limit  Kafka Partitions KEDA operates on
### Proposal

Instead of scaling on all *Partition*s, provide (sparse) lists and ranges of *Partition*s.
A particular KEDA instance should then only listen and act upon metrics on these *Partition*s.

### Use-Case

1. A Test deployment which should test data semantics on live _Topic_ (hundreds of *Partition*s). To ensure that costs are not getting out of hand for the test only one or a few of these *Partition*s should actually be tested.
2. A Limited Kubernetes Cluster where it is not possible to spawn a consumer for every *Partition*. E.g. *Topic* has 1000 *Partition*s but only able to spawn 500 Consumers on that Cluster. Thus shard *Topic* consuming to two Kubernetes Clusters which each handling 500 *Partition*s.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tobiaskrause**
Signed-off-by: Tobias Krause <tobias.krause@otto.de>

Limit Kafka Partitions KEDA operates on. #3830 

### Checklist

- [X] Commits are signed with Developer Certificate of Origin
- [X] Tests have been added
- [X] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Relates to #3830

Relates to https://github.com/kedacore/keda-docs/pull/981

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
LGTM but I'm not kafka expert, WDYT about this feature @zroubalik ?

**Review by zroubalik — COMMENTED** [review]
Looking good, @tobiaskrause do you think you can add e2e test for this feature? Then we can go ahead and merge this. Thanks

https://github.com/kedacore/keda/tree/main/tests

**Comment by tomkerkhove** [comment]
We are going to release KEDA v2.9 on Thursday. Do you think you can add e2e tests by Wednesday @tobiaskrause?

**Comment by tobiaskrause** [comment]
> We are going to release KEDA v2.9 on Thursday. Do you think you can add e2e tests by Wednesday @tobiaskrause?

Not sure, do be honest. Till now I wasn't able to find a reliable way to send a message to a specific partition with the *kafka-console-producer* script. I would need a custom producer on a pod. Do you have any idea to solve this @tomkerkhove?

**Review by zroubalik — APPROVED** [review]
LGTM, 

I think we can merge it without e2e test, as it is something not very easy testable. WDYT @tomkerkhove @JorTurFer ?

**Comment by JorTurFer** [comment]
> LGTM,
> 
> I think we can merge it without e2e test, as it is something not very easy testable. WDYT @tomkerkhove @JorTurFer ?

You are the kafka expert xD

**Comment by zroubalik** [comment]
@JosephABC would you mind looking at this as well, since you are doing a Kafka PR in parallel?

**Pull request merged**
