### PR TITLE
Migrate e2e test for /scale subresource to Go.

### LINKED ISSUE #3260: Migrate e2e test for /scale subresource in CRDs to Go
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

### Use-Case

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by v-shenoy**
Signed-off-by: Vighnesh Shenoy <vshenoy@microsoft.com>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added

Fixes #3260 

Relates to #2737

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]

**Review by zroubalik — APPROVED** [review]
/lgtm

thanks!

**Pull request merged**
