### PR TITLE
removed 'disableScaleToZero' attribute from Prometheus scaled ob…

### LINKED ISSUE #381: Prometheus scaler "disableScaleToZero" attribute
The example for [Prometheus ScaledObject](https://github.com/kedacore/keda/blob/master/examples/prometheus_scaledobject.yaml#L19) includes the `disableScaleToZero` attribute. I don't see it being used in the [metadata definition](https://github.com/kedacore/keda/blob/master/pkg/scalers/prometheus.go#L31-L36). Is this valid ?

### PR DESCRIPTION
**Pull request by abhirockzz**
fixes #381

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@Aarthisk [You've mentioned](https://github.com/kedacore/keda/issues/381#issuecomment-542924272) that minreplicas=1 defined is sufficient.

What are you referring to exactly?

**Comment by abhirockzz** [comment]
@tomkerkhove what it means is that `minReplicaCount` [in the spec](https://github.com/kedacore/keda/blob/master/spec/ScaledObject.md) is used to define the minimum number of `Pod`s and `disableScaleToZero` is not required

**Comment by tomkerkhove** [comment]
Oh I see, thanks.

**Comment by balchua** [comment]
@abhiRockzz thanks for clarifying for me. 😁

**Comment by abhirockzz** [comment]
@balchua huge props on the NATS streaming scaler!

**Comment by balchua** [comment]
Thanks!! I forgot to add nats streaming to the list in the readme.  I will send a pr to update it. And perhaps an example too.

**Pull request merged**
